### ISSUE TITLE
RFC: callback guards

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#1029]
This is a kind of "request for comments" rfc, rather than a suggested change rfc. I outline the problem, a solution and then ask if it is possible in codegen from webidl.

# The problem - tracking callbacks.

For the sake of demonstration, suppose that `EventTarget` has the following shape

```rust
pub struct EventTarget;

impl EventTarget {
    fn register_listener(&self, fn: OpaqueFunctionType);
    fn unregister_listener(&self, fn: OpaqueFunctionType);
    fn dispatch_event(&self);
}
```

This is a pain because we are responsible for storing our function pointer somewhere and then remembering to call the deregister function. If we don't, it's a memory leak (is this true - I'm not 100%). This is in some ways analogous to manual memory management.

# A solution - RAII

The standard solution for this problem is RAII. The RAII version of this interface is

```rust
impl EventTarget {
    fn register_listener(&self, fn: OpaqueFunctionType) -> Guard;
    fn dispatch_event(&self);
}
```

In this implementation, the `register_listener` function returns a `Guard` that, and when that guard goes out of scope the listener is removed. This is easy to use, we can just store the guard inside objects that are interested in listening for events, so that when they go out of scope (maybe because part of a virtual dom is unmounted), the listener is automatically unregistered in the `Drop` implementation.

# RFC

Is there any way of generating bindings following this pattern, and is it even desirable. My gut feeling is that it's not possible, but it would be such an ergonomics win if it was.

**Comment by Pauan** [comment]
@derekdreery It's not really possible to automatically create nice bindings like that from WebIDL.

However, it is quite easy to create Rust abstractions which can wrap the WebIDL and provide nicer APIs.

I believe the current plan is that such wrappers will live in a crate outside of web-sys. That crate doesn't even need to be maintained by wasm-bindgen: it could be created by anyone!

As an example of an RAII wrapper for `EventTarget`:

```rust
pub struct EventListener<A> {
    node: EventTarget,
    type: &'static str,
    callback: Closure<FnMut(A)>,
}

impl<A> Drop for EventListener<A> {
    #[inline]
    fn drop(&mut self) {
        self.node.remove_event_listener_with_callback(self.type, self.callback.as_ref().unchecked_ref()).unwrap();
    }
}
```

In order to actually create an `EventListener`, I recommend something like this:

```rust
pub trait Event {
    const TYPE: &'static str;
}
```

```rust
// Type for the "click" event
pub struct ClickEvent {
    // ...
}

impl ClickEvent {
    // Various methods/properties specific to the "click" event
}

impl Event for ClickEvent {
    const TYPE: &'static str = "click";
}
```

```rust
// Type for the "change" event
pub struct ChangeEvent {
    // ...
}

impl ChangeEvent {
    // Various methods/properties specific to the "change" event
}

impl Event for ChangeEvent {
    const TYPE: &'static str = "change";
}
```

```rust
impl<A> EventListener<A> where A: Event {
    #[inline]
    pub fn new<F>(node: &EventTarget, f: F) -> Self where F: FnMut(A) + 'static {
        let callback = Closure::wrap(Box::new(f) as Box<FnMut(A)>);

        node.add_event_listener_with_callback(A::TYPE, callback.as_ref().unchecked_ref()).unwrap();

        Self {
            node: node.clone(),
            type: A::TYPE,
            callback,
        }
    }
}
```

And now you can create nice RAII event listeners like this:

```rust
let listener1 = EventListener::new(&node, |event: ClickEvent| {
    // ...
});

let listener2 = EventListener::new(&node, |event: ChangeEvent| {
    // ...
});
```

The reason I recommend this pattern is that the `ClickEvent` might have various methods which are specific to the `"click"` event, and the `ChangeEvent` might have various methods which are specific to the `"change"` event, so we want to ensure that everything is fully statically type safe.

The `Event` trait ensures that a `ClickEvent` is always tied to a `"click"` event in the DOM (and `ChangeEvent` is always tied to `"change"`), thus guaranteeing correct static types. [This is a pattern which was pioneered by stdweb.](https://github.com/koute/stdweb/blob/3c8f62f06fc884778409ea79a9fb3f4f2a1c1972/src/webapi/event.rs#L195-L200)

Without the `Event` trait you would need to do something like this:

```rust
let listener1 = EventListener::new(&node, "click", |event| {
    let event: ClickEvent = event.unchecked_into();
    // ...
});

let listener2 = EventListener::new(&node, "change", |event| {
    let event: ChangeEvent = event.unchecked_into();
    // ...
});
```

This is much more error prone, since *you* must carefully guarantee that the static types are correct. With the `Event` trait, the compiler guarantees everything is correct, so you cannot make mistakes.

As you can see, creating nice idiomatic Rust APIs cannot be done automatically, such wrappers must be written by hand, because they need to take JavaScript idioms and convert them into Rust idioms. Thankfully the wrappers only needs to be written once and then put into a crate, so everybody can use them.

**Comment by alexcrichton** [comment]
I agree that while the issue here (auto-deregistering event listeners) is ripe for an abstraction such an abstraction probably wants to live externally of wasm-bindgen, built on the various web-sys APIs and such.

**Comment by derekdreery** [comment]
I've made a repository for experimenting with abstractions over web-sys called [dommer], if anyone is interested. It's currently wired for my personal directory structure, but reading the code in the example still works. :)

Interesting stuff
 - The guard pattern for event listeners (this issue)
 - Trying to write type-safe abstractions over stringly-typed stuff in web-sys
 - Unwrapping when errors never occur, either because they never do on the javascript side, or because we can control the input to functions using the type system.
 - *rustifying* stuff - like implementing standard traits, iterator patterns, that kinda stuff

Also I've not done it yet, but I want to experiment with integrating with serde, so you can pass serealizable structs as the body of a request, or receive structs from a response - and race the built-in json decoder :P

Just flagging it in case it's interesting to anyone.
