### ISSUE TITLE
Mutability in web-sys

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#1061]
I noticed that some methods on `Range` (e.g. [set_start_before](https://docs.rs/web-sys/0.3.5/web_sys/struct.Range.html#method.set_start_before)) accept a `&self` reference, even though the state on the range is changed by that method. Shouldn't those require a mutable reference? Or are all DOM objects treated as having interior mutability?

**Comment by alexcrichton** [comment]
A good question! Currently everything takes `&self` because everything in JS can have multiple references and effectively has interior mutability. There's no need for `&mut self` in Rust as we can't really do anything with the uniqueness guarantees! All JS objects are `!Send` and `!Sync`

**Comment by dbrgn** [comment]
Thanks! Then I guess multiple threads/workers could simply fetch multiple references to the same object and mutate it in parallel, without data races happening. Feels strange to modify a non-mut object in a Rust code base, but you're right that it doesn't make sense to limit borrowing if it's not necessary :slightly_smiling_face:

**Comment by Pauan** [comment]
@dbrgn We *could* use `&mut` instead, but that doesn't buy us anything, since even though Rust can guarantee a single writer (in Rust), the JavaScript code can still write to the object, which means there are multiple writers!

In other words, because Rust cannot guarantee that JS won't write to the object, using `&mut` would basically be a lie.

As for multiple threads/workers, that's a much trickier situation, which we haven't fully figured out yet. It might involve a `JsValueSync` wrapper (or similar) which uses atomic synchronization between workers to manage a `JsValue` (which is stored in the thread that created it).
