### ISSUE TITLE
Return type of Document.create_range

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#1062]
In web-sys, [Document.create_range](https://docs.rs/web-sys/0.3.5/web_sys/struct.Document.html#method.create_range) returns a `Result<Range, JsValue>`. But in [the WebIDL](https://www.w3.org/TR/2000/REC-DOM-Level-2-Traversal-Range-20001113/ranges.html#Level-2-DocumentRange-idl), that method is marked as not throwing any exceptions.

What type of error could the `create_range` return in web-sys?

**Comment by alexcrichton** [comment]
Thanks for the report! You can see some more information [here](https://github.com/rustwasm/wasm-bindgen/issues/908) but the tl;dr; is that the WebIDL we use [does have a `Throws` attribute](https://github.com/rustwasm/wasm-bindgen/blob/bbde39fe66db388bebd8d51a99c75109772b436f/crates/web-sys/webidls/enabled/Document.webidl#L90-L91). That may be firefox-specific, however, and we've since learned that the `[Throws]` attribute is also somewhat ephemeral, even for Firefox!

**Comment by alexcrichton** [comment]
I'm gonna close this as this matches the WebIDL we have, so I don't think we're going to be changing this. I do think, however, that an improvement in the ecosystem to create more ergonomic wrappers around the web-sys primitives would be a great thing to have!
