### ISSUE TITLE
How to pass a slice?

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1085]
Looking at the [nalgebra docs](https://nalgebra.org/cg_recipes/#conversions-for-shaders) it seems that it can extract a slice (or pointer) from its matrices

What would be the (or one) correct way to pass these slices to JS?

Thanks!

**Comment by alexcrichton** [comment]
Currently the best way to do so is to invoke an imported function inline rather than returning it directly to JS. https://github.com/rustwasm/wasm-bindgen/pull/918 was an attempt to implement this and otherwise I think this is covered by https://github.com/rustwasm/wasm-bindgen/issues/811 so we can convert it to a `JsValue` and return it, so I'm gonna close in favor of https://github.com/rustwasm/wasm-bindgen/issues/811!
