### ISSUE TITLE
clippy error for imported js types

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-bindgen#1112]
Tried to run clippy in our project and got an error. Can be reproduced here in examples folder:
```bash
cd examples/duck-typed-interfaces
cargo clippy
```
The error is
```
error: calls to `std::mem::drop` with a reference instead of an owned value. Dropping a reference does nothing.
 --> examples/duck-typed-interfaces/src/lib.rs:9:1
  |
9 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^
  |
  = note: #[deny(clippy::drop_ref)] on by default
  = note: argument has type &wasm_bindgen::JsValue
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/master/index.html#drop_ref
```

**Comment by alexcrichton** [comment]
Thanks for the report! I don't think this is really our bug per se but rather than a bug in clippy. Clippy shouldn't be linting against code that was produced by a macro because we're writing very generic (and unidiomatic) code, and the major purpose of clippy is to write idiomatic code. I'm gonna close this, but I'm sure upstream clippy would appreciate a bug report!

**Comment by fitzgen** [comment]
We could also consider generating `#[allow(clippy::*)]` or whatever the right invocation is in our generated code.

**Comment by alexcrichton** [comment]
Ah yes, indeed!

**Comment by fitzgen** [comment]
FYI: I filed #1200 for adding `#[allow(clippy::*)]` to our macro-generated code.
