### ISSUE TITLE
Allow explicitly naming imported function

### ISSUE THREAD

**Issue by tiziano88** [rustwasm/wasm-bindgen#1128]
I am embedding the resulting Wasm code into a custom runtime that I am writing, and currently I need to de-mangle exported function names to remove the prefix and suffix that wasm-bindgen generates. I would like to have full control over the exported name, something like `#[no_mangle]` but also allowing setting an arbitrary name different from the Rust one. I am happy to look into this, if this does not sound like a terrible idea?

**Comment by alexcrichton** [comment]
Does the [`js_name` attribute on exports](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/js_name.html) solve your use case here?

**Comment by Pauan** [comment]
@tiziano88 Your custom runtime runs JavaScript code? Why does it need to demangle the names, rather than resolving them in the same way as [the standard Wasm<->JS spec](https://webassembly.github.io/spec/js-api/index.html)?

Note that even though the imports/exports are mangled, they refer to an *unmangled* name in the generated `.js` code:

```js
// Mangled name here
__exports.__wbg_f_renamed_test_function_test_function_n = function(arg0, arg1) {
    let varg0 = getStringFromWasm(arg0, arg1);

    // Unmangled name here
    renamed_test_function(varg0);
};
```

So as long as your `renamed_test_function` function exists in the global scope, then it will work.

Alternatively your runtime could expose a magical built-in module (similar to `fs`, `path`, etc. in Node), and then you could import that:

```rust
#[wasm_bindgen(module = "my-magical-module")]
extern "C" {
    #[wasm_bindgen(js_name = renamed_test_function)]
    fn test_function(s: &str);
}
```

This avoids polluting the global scope, but is otherwise the same.

**Comment by tiziano88** [comment]
@Pauan thanks for the link, I had not seen it before, though it does not seem to explain the way mangling works? For my use case, I do not have any JS running at all, I have basically a Wasm interpreter running as a server, and implementing some host calls natively (e.g. to log or access the network etc). Because the runtime is agnostic of how the code was compiled (i.e. it should work for code compiled from Rust, C++, Go, etc), I would like to avoid coupling it to the naming conventions of `wasm-bindgen` specifically.

**Comment by Pauan** [comment]
@tiziano88 The name mangling is an implementation detail of wasm-bindgen, you shouldn't be relying upon it.

The link I gave is for JS code communicating with wasm code (which is wasm-bindgen's purpose).

If you don't have JS running, how do you intend to use wasm-bindgen? Wasm-bindgen generates JS code, and requires JS to run. It is intended for JS environments.

If you are running pure wasm (no JS), then you don't need wasm-bindgen at all, you can just do `cargo build --target wasm32-unknown-unknown`, since Rust has built-in support for wasm.

As for renaming, you can just create a thin `fn` wrapper:

```rust
extern "C" {
    fn renamed_test_function(s: &str);
}

#[inline]
pub unsafe fn test_function(s: &str) {
    renamed_test_function(s);
}
```

By making `renamed_test_function` private and only exposing `test_function`, that effectively "renames" the binding.

That also gives you the opportunity to provide safe/convenient wrappers, do pre/post validation, etc.

This article is written for C, but it will probably help you as well:

https://doc.rust-lang.org/nomicon/ffi.html

Similarly, you can go the other way, and expose functions to wasm:

```rust
#[no_mangle]
pub extern "C" fn foo(x: i32, y: i32) -> i32 {
    x + y
}
```

None of this requires wasm-bindgen.

However, wasm only supports simple types (i32 and floats), so for more complex things (like structs or vec) you'll need to do some marshalling.

wasm-bindgen does marshalling, however the marshalling is all done assuming that it is running in a JS environment, so I don't think that will work for you.

So you'll need to create your own marshalling system. It *might* be possible to reuse the C marshalling (probably not?).

You can also take a look at how wasm-bindgen does marshalling (it won't be exactly what you need, but it might give you some good ideas).

**Comment by tiziano88** [comment]
@Pauan thanks, you are correct, it turns out I actually don't need wasm-bindgen at all; I can do almost everything using plain FFI compiling for `wasm32-unknown-unknown` (here is how to control the module of the expected imports https://rustwasm.github.io/book/reference/js-ffi.html , which is what I was missing). Also it seems that there is already some sort of serialisation built in, though I have not investigated what the actual format of that is?

I am still missing how to actually mark a Wasm [start function](https://github.com/WebAssembly/design/blob/master/Modules.md#module-start-function) using plain Rust FFI, which AFAICT using wasm-bindgen can be done using the `#[wasm_bindgen(start)]`. Any ideas how to do that?

**Comment by alexcrichton** [comment]
Ah ok, thanks for the update @tiziano88 and the help here @Pauan!

As for serialization, the default FFI boundary has no serialization, just a definition of what the ABI should look like. While wasm-bindgen provides some utilities for serialization, they're all opt-in and library-defined.

@Pauan is right in that the `start` function is "somewhat uncomfortable" in the sense that it's best to provide a symbol that the runtime manually calls. Rust currently has no native support for configuring the `start` function in the wasm output module, but we'd like to add that one day!

In any case I think this is probably a solved issue now (turns out wasm-bindgen wasn't the right target!), so I'm going to close this.

**Comment by tiziano88** [comment]
Yes, I just managed to do everything I need (except start function) using standard FFI, so indeed there is no need to use wasm-bindgen for my use case. Thanks everyone for your support, much appreciated!
