### ISSUE TITLE
Adding `#[wasm_bindgen]` means you can't run `cargo bench` anymore

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#114]
You get link errors and things like that.

Ideally, we should make all the wasm-bindgen generated code guarded by `#[cfg(target_arch = wasm32)]` or something like that.

The

```toml
[lib]
crate-type = ["cdylib"]
```

stuff is a little harder. It can be commented out just when running `cargo bench`, but that is clunky. Ideally that would not be necessary either.

**Comment by alexcrichton** [comment]
One idea would be to use binaries as the output target rather than `cdylib`, and wasm-bindgen could presumably perform wasm-gc and keep the binaries small (and strip the `main` function or something like that)

That would still require you to separate code, however, into a binary and a library as only the library would be available for writing benchmarks and tests.

Overall I think the situation isn't great and this is somewhat of a Cargo issue. Ideally you'd be able to customize the `crate-type` more aggressively than only by what's written in the Cargo.toml. 

---

I wonder, though, perhaps the project template for wasm could have two crates? One crate, the primary one, is an rlib which is benchmark-able and testable (and using `wasm-bindgen`). The other, a `cdylib`, is purely a reexport of the public contents of the rlib (aka `pub use other_crate::*`). I believe that should still produce a working wasm target and would be relatively low overhead? (maybe a pain to remember to build a different target for wasm, but scripts may be able to automate this)

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/cargo/pull/5367
