### ISSUE TITLE
Allowing for usage of JsValue across threads.

### ISSUE THREAD

**Issue by Pauan** [rustwasm/wasm-bindgen#1154]
According to [this comment](https://github.com/WebAssembly/reference-types/issues/26#issuecomment-451916658) Tables will eventually be sharable between workers, which I believe will allow for `JsValue` to be `Send` and `Sync`.

This won't happen anytime soon, but I wanted to get this tracked somewhere.

**Comment by rossberg** [comment]
The generalisation of sharable things in Wasm will not have any immediate impact on JS values, see my [follow-up comment](
https://github.com/WebAssembly/reference-types/issues/26#issuecomment-451933685). I doubt that we'll ever want to allow sharing random JS values, since that would fundamentally break the guarantees currently provided by the JS/DOM programming model and essentially require reimplementing all browsers from scratch.

**Comment by Pauan** [comment]
@rossberg Ah, that's unfortunate, but understandable.

Thanks for the clarification!
