### ISSUE TITLE
text-encoding is archived

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-bindgen#1182]
The repo is archived and seems no longer maintained
https://github.com/inexorabletash/text-encoding

Is there a way to load wasm without this dependency?

**Comment by alexcrichton** [comment]
A good question! FWIW this isn't required to work with `wasm-bindgen`, it's only currently required (or something like it) if you want to load wasm code using strings in Edge which doesn't have support for these types.

**Comment by ibaryshnikov** [comment]
There is also a case when building with --no-modules and running in Edge.

**Comment by alexcrichton** [comment]
When we first talked about this a long time ago we wanted to avoid pulling a polyfill directly into wasm-bindgen and maintaining it, but that was also under the assumption that there was a community-provided solution available. If that doesn't seem to be the case, then we may want to rethink!

@ibaryshnikov our thinking was also that if you want wide browser compatibility that you'd want to be using a bundler anyway because we're using newish JS syntax in wasm-bindgen as well. 

@Pauan that looks pretty small, and presumably the decoder is also small enough. We could consider adding a CLI flag to wasm-bindgen to include those if they're small enough! (and copy/pasting examples from MDN seems pretty reliable)

**Comment by ibaryshnikov** [comment]
Actually, the polyfill from MDN doesn't work in edge in strict mode
```
if (typeof TextEncoder === "undefined") {
    TextEncoder=function TextEncoder(){};
```
fails with error "variable undefined in strict mode"
But the following works:
```
if (typeof TextEncoder === "undefined") {
    window.TextEncoder=function TextEncoder(){};
```
@alexcrichton your reasoning is good, probably there is no need to include polyfill in wasm-bindgen, since there are still could be problems like the one with strict mode.
My point was that the polyfill from examples is not maintained anymore, but more likely that it doesn't need maintanance because it's old and well-tested.

**Comment by alexcrichton** [comment]
Ah ok, good find! I think we'll probably stick with the polyfill for now, but if there turn out to be problems with it we can figure out an alternative!
