### ISSUE TITLE
Name conflict when a struct is called "Context"

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#1249]
As discussed in #1242: I'm getting the following error when a struct is called `Context` when calling `wasm-pack test --headless --firefox`:

```
  [3/6] Compiling tests to WASM...
     Compiling compose-area v0.1.0 (/home/danilo/Projects/compose-area)
  error: linking with `rust-lld` failed: exit code: 1
    |
    = note: "rust-lld" "-flavor" "wasm" "--no-threads" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--no-entry" "--fatal-warnings" "--export-dynamic" "--no-
    = note: rust-lld: error: duplicate symbol: __wbg_context_free
            >>> defined in /home/danilo/Projects/compose-area/target/wasm32-unknown-unknown/debug/deps/libcompose_area.rlib(compose_area.1zjlr9g8cstvtdrr.rcgu.o)
            >>> defined in /home/danilo/Projects/compose-area/target/wasm32-unknown-unknown/debug/deps/libwasm_bindgen_test-258015b5016fb118.rlib(wasm_bindgen_test-258015b501
```

Probably a name mangling issue.

**Comment by alexcrichton** [comment]
Thanks again for spinning this off!

This is actually somewhat difficult to support now that I think about it. Right now all the exports from Rust are generated into a flat namespace in JS, so this is actually a legitimate namespace conflict. I'm not sure we can really support duplicate-ly named types in separate crates being linked together because we wouldn't know what to call the names in JS!

What I do think, however, is that the test framework should be using less common names :)

**Comment by dbrgn** [comment]
Do we have access to the source crate of a symbol? Maybe that could be integrated into the name?

**Comment by alexcrichton** [comment]
We do! All that would end up with though is a better error message here, which is certainly an improvement! I'm nto sure we could actually allow this still

**Comment by alexcrichton** [comment]
I've posted a rename for our own `Context` in https://github.com/rustwasm/wasm-bindgen/pull/1280

**Comment by dbrgn** [comment]
Thank you!

Feel free to close this issue, unless it should stay open to discuss further namespacing / name mangling.

**Comment by alexcrichton** [comment]
Ok I think in that case I'll go ahead and close

**Comment by dimitri-lenkov** [comment]
Thank you *so much* for [this comment](https://github.com/rustwasm/wasm-bindgen/issues/1249#issuecomment-463688572) --- it got me unstuck.

I found this issue when looking up "wasm_bindgen duplicate symbol". 

In my particular case, I have **multiple** crates in a cargo workspace that followed similar `strut` & method naming patterns, e.g. both workspace crates "foo" and "bar" had structs with names and methods like this:

```rust
impl Consume {
   //  . . .

   #[wasm_bindgen]
   pub fn start(/* ... */) {}
}
```

and the solution was to re-name the structs to be "crate specific", e.g. `FooConsume` and `BarConsume` respectively. By doing this, the generated symbol names would be `*_foo_consume_start` & `*_bar_consume_start` instead of the duplicate-ly generated name `*_consume_start`.

- - -

> I'm not sure we can really support duplicate-ly named types in separate crates being linked together because we wouldn't know what to call the names in JS!

As a complete noob: Is it possible for `#[wasm_bindgen]` to automatically shove-in the current crate's name into the link_name to help "mangle" the name a bit more? `wasm_bindgen` is still sort of voo-doo magic for me lol.
