### ISSUE TITLE
_bg.wasm Unexpected section: 0x86

### ISSUE THREAD

**Issue by kpp** [rustwasm/wasm-bindgen#1251]
How to reproduce:
```
cd ~/wasm-bindgen/examples/webaudio
npm install
npm build
```

Output:

```
ERROR in ./pkg/webaudio_bg.wasm
Module parse failed: Unexpected section: 0x86
You may need an appropriate loader to handle this file type.
Error: Unexpected section: 0x86
    at new CompileError (~/wasm-bindgen/examples/webaudio/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseSection (~/wasm-bindgen/examples/webaudio/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1542:11)
    at Object.decode (~/wasm-bindgen/examples/webaudio/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1559:25)
```

Because of (I believe so):

```
$ head -n2 pkg/webaudio.js
/* tslint:disable */
import * as wasm from './webaudio_bg';
```

How do I fix it?

Linked issue: https://github.com/rustwasm/wasm-bindgen/issues/1114

**Comment by kpp** [comment]
Well. Looks like I failed twice reporting the issue. Duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1249

**Comment by BigBigos** [comment]
Are you sure this is a duplicate of another bug?

I had a similar issue, regarding WASM module parse failure. It turned out it was the old version of wasm-parser npm package. Updating webpack to 4.29.4 (which has a newer wasm-parser version as a dependency) fixed this issue.

It seems the webpack version in examples/webaudio has already been bumped in 5e7187a95f11caa6b36872f7850634def72edc0a.

**Comment by kpp** [comment]
How to update it?

**Comment by BigBigos** [comment]
Open package.json and update the webpack version inside:

```
    "webpack": "^4.29.4",
```

Or, if you just want to run the webaudio example, pull the recent changes from this repo as it has already been bumped 20h ago.
