### ISSUE TITLE
wasmbindgen with const name

### ISSUE THREAD

**Issue by AlbanMinassian** [rustwasm/wasm-bindgen#1268]
i would like inject const class name inside #[wasm_bindgen]. how write like this ?

```rust
const NAME: &'static str = "__hello__"; // in another file

#[wasm_bindgen(js_name = NAME)] // how inject **__hello__** here ?
pub struct JsTmp { }
#[wasm_bindgen(js_class = NAME)] // how inject **__hello__** here ?
impl JsTmp {
    // ...
}
```

Is it possible ?
Thanks

**Comment by alexcrichton** [comment]
Unfortunately we can't support this at this time because the macro has to have access to the actual contents of the name which during macro expansion we can't resolve. This would be an interesting future feature to implement though! (not that I know how we'd do it, I just don't think it's *impossible*)

**Comment by AlbanMinassian** [comment]
Thank you for the answer.
