### ISSUE TITLE
No safe way to create an ArrayBuffer from a &[u8]

### ISSUE THREAD

**Issue by tomaka** [rustwasm/wasm-bindgen#1303]
### Motivation

I'm trying to use an existing JS library (from NPM). One of the methods in this library's API expects to get passed an `ArrayBuffer` object. Therefore, I need to be able to generate an `ArrayBuffer` from the Rust code.

It is already possible to do so by doing:
```rust
let arr = unsafe { Uint8Array::view(my_buf) };
let arr_clone = Uint8Array::new(arr).buffer();
```

However that requires using unsafe code.

### Proposed Solution

Add an `ArrayBuffer::from_data(&[u8])` function in order to move the safety issues within wasm-bindgen.
Similarly, we can also add similar `from_data` methods to the `Uint8Array` types and similar.

**Comment by alexcrichton** [comment]
Thanks for the report! This is somewhat fundamental though because `ArrayBuffer` represents a mutable chunk of memory which can be safely passed to things like [`Int8Array::new`](https://docs.rs/js-sys/0.3.14/js_sys/struct.Int8Array.html#method.new), so if we had a safe constructor it could then be unsafely actually mutated behind the scenes.

If you're interested in just the `ArrayBuffer` that backs wasm memory you should be able to safely acquire that via `wasm_bindgen::memory()`, casting that to `WebAssembly::Memory`, and then using `buffer()`

**Comment by tomaka** [comment]
> so if we had a safe constructor it could then be unsafely actually mutated behind the scenes.

My suggestion would be to clone the data, not to hold a reference the `&[u8]`.
In other words, something similar to `Slice::to_vec()` in the standard library.

**Comment by alexcrichton** [comment]
Oh sure yeah, that'd definitely be safe, but that can be built with a function that uses `unsafe` internally, right? Is this a feature request to add such a function that uses `unsafe` internally to `wasm-bindgen` itself?

**Comment by tomaka** [comment]
> Is this a feature request to add such a function that uses `unsafe` internally to `wasm-bindgen` itself?

Exactly!

**Comment by Pauan** [comment]
This [has been implemented](https://github.com/rustwasm/wasm-bindgen/pull/1620), you can now do `Uint8Array::from(my_buf).buffer()`
