### ISSUE TITLE
webAudio mistypo with --target no-modules

### ISSUE THREAD

**Issue by simdax** [rustwasm/wasm-bindgen#1311]
## 🐛 Bug description
When building the webaudio example, the main .js file instantiate a
` new lAudioContext ` instead of a simple ` new AudioContext `

#### 🤔 Expected Behavior
It should call `AudioContext`, not `lAudioContext`

#### 👟 Steps to reproduce
simply copy the [webaudio example of wasm-bindgen package](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/webaudio), build it with `wasm-pack --target no-modules && grep -rn lAudio pkg` and you'll see the error

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.5.1
rustc version: 1.32.0-nightly

**Comment by ibaryshnikov** [comment]
After a short debug I found
```
[crates/cli-support/src/js/mod.rs:2105] name = "AudioContext"
[crates/cli-support/src/js/mod.rs:2141] class.to_string() = "lAudioContext"
[crates/cli-support/src/js/rust2js.rs:664] c = "lAudioContext"
```
https://github.com/rustwasm/wasm-bindgen/blob/master/crates/cli-support/src/js/mod.rs#L2105

what's the purpose of `format!("l{}", name)` ?

**Comment by alexcrichton** [comment]
Thanks for the report @simdax! This is definitely a bug in `wasm-bindgen` right now due to the internal branch we have on no-modules vs not. That's being refactored in https://github.com/rustwasm/wasm-bindgen/pull/1295 and this issue is actually inadvertently fixed by that PR. I suspect that won't take too long to land, so we can fix this with that!

**Comment by alexcrichton** [comment]
Thanks for the report @simdax! This is definitely a bug in `wasm-bindgen` right now due to the internal branch we have on no-modules vs not. That's being refactored in https://github.com/rustwasm/wasm-bindgen/pull/1295 and this issue is actually inadvertently fixed by that PR. I suspect that won't take too long to land, so we can fix this with that!
