### ISSUE TITLE
wasm-bindgen-futures: how do you test with assert for async code?

### ISSUE THREAD

**Issue by najamelan** [rustwasm/wasm-bindgen#1364]
### Motivation

Async blocks and other executors swallow panics. wasm-bind-futures::spawn_local is no different. That means that assert and family for tests won't work. 

The usual advice for testing async code is to use block_on and call assert outside of the async code. However wasm does not have block_on and if I understand it well, in javascript you can't block the current thread, hence no go.

As far as I can tell right now, the only solution is to print test results to the console of the browser... I suppose futures::LocalPool won't work either, because that uses thread::park...

### Proposed Solution

I dunno...

### Workaround

print test results in browser console

**Comment by alexcrichton** [comment]
This is a good question! I think what you may be running into is a number of bugs and limitations of wasm now though rather than a fundamental bug in the system. WebAssembly doesn't support unwinding right now, so a `panic!` is intended to completely abort the program and not allow reentrancy. With WebAssembly, however, it just turns into a JS exception and you can indeed catch that and reenter a module.

This notably means that on wasm if you `panic!` then destructors aren't wrong. Destructors, especially in an async system, are often critical to run to keep everything progressing smoothly, such as terminating a channel to let another thread know that it won't ever wake up.

This doesn't mean that there's not bugs in the code here though! Can you gist a concrete example of what you're seeing and what the expected behavior is?

**Comment by najamelan** [comment]
I'm sorry, I filed this to fast. I only now found this:
https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/asynchronous-tests.html#example

And it seems to work. I don't know how you pulled it off, but this works with `assert_eq!`. It shows a quite massive stacktrace however. Since I tested it on just one test, that's ok, but if I would have a lot of failing tests, that would be unworkable. It also shows things that go to the browser console. On the failing test it shows  all the console output per loglevel. It's actually really nice. If only it could show a concise backtrace it would be perfect.

**Comment by najamelan** [comment]
I understand things a bit better after diving into the wasm-bindgen code, but still can't figure out how to use quickcheck to test an async function... It really seems we would need block_on for something like that. I'll let it rest for now.
