### ISSUE TITLE
What does the path in #[wasm_bindgen(module = "wu/tan/clan")] actually refer to?

### ISSUE THREAD

**Issue by jjpe** [rustwasm/wasm-bindgen#1375]
### Summary

The [docs](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/module.html) don't exactly make clear to where the path `"wu/tan/clan"` refers in this snippet:
```rust
#[wasm_bindgen(module = "wu/tang/clan")]
extern "C" {
    type ThirtySixChambers;
}
```
Initially I assumed that that path was relative to `$PROJECT_ROOT` (i.e. the dir that contains `Cargo.toml`  and `package.json`) but that seems not to be the case, because of [this](https://users.rust-lang.org/t/wasm-bindgen-doesnt-support-relative-paths-anymore/26492) issue I'm having. 
 
So here are my (interrelated) questions: 
1. To where _does_ the path refer? 
2. What is the path relative to? 
3. And why doesn't the example outlined in [this topic](https://users.rust-lang.org/t/wasm-bindgen-doesnt-support-relative-paths-anymore/26492) on urlo work?

### Additional Details
N/A

**Comment by alexcrichton** [comment]
Thanks for the report! The path there is actually left to interpretation of whatever will eventually interpret ES module strings. That may be a bundler, the browser, etc. A recent [RFC 6](https://github.com/rustwasm/rfcs/blob/master/text/006-local-js-dependencies.md) attaches meaning to paths starting with `../`, `./`, or `/`, but all other paths are left up to the bundler and/or browser.

So to answer your question, `"wu/tang/clan"` isn't a local path interpreted by `wasm-bindgen`, and we can't actually say what it refers to since it depends on what ES module runtime you're using (aka bundlers or browsers).

Your urlo topic is fallout of RFC 6 unfortunately, and it's *intended* to work as relative to the current file, but we unfortunately don't have the tools to implement that just yet so `/` paths are instead always relative to the crate root. 

Does that help clear things up?

**Comment by jjpe** [comment]
>  so / paths are instead always relative to the crate root.

Do you mean any path that contains a `/`, or any path that starts with `/`?

As for which modules I'm using, they're essentially simple modules (at least in this context) using `require()`. The intent there is that the code is ultimately usable both in the browser and in NodeJS (though it seems that `wasm_bindgen` needs to treat the browser and NodeJS as separate targets, which in and of itself is perfectly workable).

**Comment by alexcrichton** [comment]
Oh sorry, only paths that start with `/` are recognized as "relative to the crate root"

It sort of depends on what you're doing how you'd want to organize it. The intention or recognize the relative paths is to support the [js snippets feature](https://rustwasm.github.io/docs/wasm-bindgen/reference/js-snippets.html) recently added, but this unfortunately doesn't work with the Node.js target just yet. 

For now your best bet is probably going to be a Webpack-style setup where you use the default target and then configure Webpack to generate output for a browser and output for node, although it's definitely something that we hope to improve in the future!

**Comment by alexcrichton** [comment]
I'm gonna go ahead and close this since I think the question was answered here, but let us know if there's anything still lingering!
