### ISSUE TITLE
Allocator won't use the provided memory when using `--import-memory` 

### ISSUE THREAD

**Issue by darionco** [rustwasm/wasm-bindgen#1389]
### Describe the Bug

I have a program that needs uses a big amount of heap memory but it grows sequentially, so say, I need to use 1GB of heap memory by allocating chunks of ~20MB every iteration of a loop.

I thought I could avoid the performance hit of growing the memory a bunch of times by adding `--import-memory` to my lld flags, using the flag works as expected, the generated `wasm` and the `init` method in the generated `js` file expect a WebAssembly.Memory instance.

The problem arises when I try to use that memory, for example, if I initialize my WASM instance like this:
```
const memory = new WebAssembly.Memory({initial: 24,576, maximum: 24,576}); // ~1.5GB
wasm(module, memory);
```
The program crashes immediately after I call an exported wasm function because the stack is pointing at the end of the 1.5 GB of memory and the first thing the allocator tries to do is grow the memory, which can't be done because I specified a maximum memory size of 1.5 GB.

Interestingly, if I allow the memory to grow and make heap allocations with `Vec` or `Box`, the heap is then placed after the stack, which is at the end of the 1.5GB of preallocated memory. I can access the memory by writing some bytes from JavaScript and then passing the memory address as a raw pointer to the Rust code, but this is unsafe and some times crashes the program.

I read a reference to changing the stack pointer in the [Multithreading Rust and Wasm
](https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html) article, but looking through the code I couldn't find an obvious reference and I am too new in Rust to understand half of the PRs in the list at the bottom of the article. Also, I can't use passive memory segments since I must support all modern browsers.

### Steps to Reproduce

1. Create a simple WASM project from the hello world template:
```
cargo generate --git https://github.com/rustwasm/wasm-pack-template
```
2. Create a `.cargo/config` file with the following content:
```
[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-args=--import-memory",
]
```
3. Build with the `--target web` argument:
```
wasm-pack build --target web
```
4. In your JavaScript code load the module and provide it with custom memory:
``` javascript
import * as wasm from 'path/to/the/generated/js';

// ...

WebAssembly.compileStreaming(fetch('path/to/generated/wasm')).then(module => {
    const memory = new WebAssembly.Memory({initial: 64, maximum: 64}); // way more than what the program needs
    wasm(module, memory).then(instance => {
        wasm.run();
    });
});
```
5. Run and watch it crash

### Expected Behavior

The program uses the provided memory.

### Actual Behavior

The program tries to allocate its own memory after the provided memory.

### Additional Context

For now I settled by not importing memory and allocating a big chunk of heap memory on startup so the allocator grows the memory to the desired size, then I deallocate it and start doing computations. This method, although it works, it's not acceptable as it is convoluted and generally a hack.

**Comment by alexcrichton** [comment]
Thanks for the report! 

This is all unfortunately working as intended, however, due to the way that the current wasm target works. The heap is fundamentally allocated via `memory.grow` instructions and can't be preallocated with the wasm32-unknown-unknown target's default allocator. Put another way, the default allocator provided by wasm32-unknown-unknown will unconditionally consider the current memory at startup as part of the wasm's own image (rodata, bss, static data, etc), so the only way it can get memory for it to manage is to call `memory.grow`.

Now this is an issue when the initial/maximum size of `WebAssembly.Memory` is the same. That means the memory can't be grown at all! That's why you're seeing the failure you're seeing, because the first allocation is attempting to grow memory to get memory to hand out, but it's failing.

What you may want in this use case is one of two avenues:

* First, you can turn down `initial` to what's specified in the wasm file's imported memory. That way the initial memory is big enough for all the initial wasm data, and then it'll dynamically grow from there up to the maximum. I don't know the performance implications though of this. Engines may take the `maximum` as a size hint for reserving virtual memory so the memory never moves, but they may also just always allocate 4GB chunks for wasm modules (I'm not entirely sure).

* Second, you could override the default global allocator with your own. Your own global allocator would probably never call `memory.grow` and would instead use linker symbols to figure out where the end of heap data is and start using that to the end of wasm memory as a region to manage.

I'd recommend though benchmarking to see if setting a maximum or pre-reserving is a benefit for your use case. It may end up not actually costing much to use the default settings!

**Comment by darionco** [comment]
Thanks for the response, I did do benchmarks and found very interesting results, for one WASM code generated by `wasm-bindgen` runs incredibly slow in Chrome (about 3x slower) while reasonably fast in Firefox and Safari. I wrote an equivalent program in C and used `emscripten` the resulting code runs very fast in Chrome and equally fast in Firefox and Safari as the `wasm-bindgen` version.

Regarding memory allocations, letting the memory grow as the program runs did incur a performance hit , although I am not sure if it was the allocator or actually memory being copied around.

Preallocating a big buffer to grow the heap, then deallocating it and running the program yields good results but because the code just runs much slower on Chrome I am not sure memory allocations are my biggest bottleneck anymore.

Chrome being slow might be a deal breaker for me since it represents [over 60% of browsers accross platforms, followed by Safari with over 15%, while firefox sits at less than 5%](http://gs.statcounter.com/browser-market-share)

**Comment by alexcrichton** [comment]
Interesting! @darionco would you be able to share the program to poke around what's going on? Do you know what emscripten was architecturally doing differently to be fast in Chrome?

**Comment by darionco** [comment]
Sure, I'll open a new issue with the details.
Unfortunately, I haven't looked at the differences between the produced `wasm` files too closely, a quick conversion to `wat` shows that they are very different, in size at least.

**Comment by alexcrichton** [comment]
Ok no worries! An issue for that performance bug would be very much appreciated!

**Comment by darionco** [comment]
Good news! Rust in fact runs as fast as C in WASM in Chrome!  

 Turns out I am using [`@wasm-tool/wasm-pack-plugin`](https://github.com/wasm-tool/wasm-pack-plugin#readme) which by default builds in debug mode, contrary to the [`wasm-pack` documentation](https://rustwasm.github.io/docs/wasm-pack/commands/build.html) which states:
> The build command accepts an optional profile argument: one of --dev, --profiling, or --release. If none is supplied, then --release is used.  

I got confused because the plugin's documentation doesn't state that the default is `debug`, it does log what configuration it is building though, I should have paid more attention.

My bad, either way, thanks for your help!

**Comment by alexcrichton** [comment]
Oh no worries, glad it ended up working out!

**Comment by mantou132** [comment]
@alexcrichton hi

Does this mean that I can't use [shared memory](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory/Memory#shared)?

**Comment by Liamolucko** [comment]
> Does this mean that I can't use [shared memory](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory/Memory#shared)?

No; the issue only occurred because the wasm module's memory was initialised to its maximum size, which broke the allocator when it attempted to grow the memory. Importing memory works fine as long as you don't do that.

https://github.com/rustwasm/wasm-bindgen/issues/1389#issuecomment-476224477 provides a bit more detail.
