### ISSUE TITLE
Can we have a CI check for code formatting?

### ISSUE THREAD

**Issue by c410-f3r** [rustwasm/wasm-bindgen#1415]
It is not rare to work on a feature, run `cargo fmt` and see many unrelated files being formatted. Is anything preventing the enforcement of code formatting in CI with the default `rustfmt` rules?

**Comment by alexcrichton** [comment]
A good question! We used to have this but we turned it off because it was too much of a hassle on CI to keep up with. That being said we're more than willing to take PRs with a commit to rustfmt everything, and PRs that rustfmt everythign are also ok! We should probably update the README/CONTRIBUTING to reflect this...
