### ISSUE TITLE
why isn't IntoWasmAbi impl for Box<[usize]>and Box<[isize]>?

### ISSUE THREAD

**Issue by DenialAdams** [rustwasm/wasm-bindgen#1426]
### Summary

Since IntoWasmAbi is implemented for usize (which I think is u32 on wasm?), u32, i32, Box<[u32]>, and Box<[i32]>: shouldn't it be implemented for Box<[usize]> and Box<[isize]>? Looking at the source, I suppose this question also applies for all the other WasmSlice types

### Additional Details

Filing as a question, because I'm probably missing something :)

**Comment by DenialAdams** [comment]
I'm going to add another question if that's ok :o

Why does this work:
```rust
#[wasm_bindgen]
pub fn pathfind(start: usize, goal: usize, pathfind_algo: &str) -> Box<[u8]>
```

but no this?
Why does this work:
```rust
#[wasm_bindgen]
pub struct FinalizedDiagMapWasm {
   pub inner: Box<[u8]>,
   pub generated_history: Box<[u32]>,
   pub expanded_history: Box<[u32]>,
   pub num_generated_history: Box<[u32]>,
}

#[wasm_bindgen]
pub fn pathfind(start: usize, goal: usize, pathfind_algo: &str) -> FinalizedDiagMapWasm
```

I get the error message `the trait bound `std::boxed::Box<[u8]>: std::marker::Copy` is not satisfied`. But if we can pass a Box<[u8]> without an issue when it is alone, why can't we pass it in a struct?

**Comment by alexcrichton** [comment]
Thanks for the report @DenialAdams! For the first question, I think it may just be an accidental omission. Would you be interseted in sending a PR for adding these impls?

For the latter question all struct fields must currently be `Copy` if they're `pub` to be exported to JS

**Comment by DenialAdams** [comment]
Yes, I'll try working on a PR myself. Thanks for following up!

I understand that Copy is required, but I'm not understanding why it's
required. Specifically: if we can return a value of type Foo that does not
impl Copy, what is preventing us from returning that same value in a
struct? i.e. what changes when the value is in a struct?

And finally, what's the workaround if I need to return multiple non-Copy
types?

**Comment by alexcrichton** [comment]
Calling `clone` can be accidentally very expensive or otherwise cause surprising behavior because state is duplicated (not necessarily in the case of `String`, but in the general case). As a result we wanted to make sure that a call to `clone` was explicitly written by the user rather than implicitly inserted by accident.

The intention is that instead of having a `pub` field you'd write a method like `pub fn inner(&self) -> Box<[u8]>` which would do the `clone`. Today that means in JS you'd do `foo.inner()`, but we'd like to add a `#[wasm_bindgen]` attribute which says "this is the getter for the `inner` field" which means it'd turn into `foo.inner` in JS
