### ISSUE TITLE
Bindings' long unformatted lines does not work well with RLS

### ISSUE THREAD

**Issue by LaylConway** [rustwasm/wasm-bindgen#1457]
### Describe the Bug

RLS (and by extension vscode-rust) doesn't like really long lines. It expects the code to be formatted reasonably. This as a result causes some issues. Errors are shown about RLS not being able to tokenize long lines for performance reasons, and tooltips show the entire line, slowing down VSCode in the process:

![Code_2019-04-14_19-59-57](https://user-images.githubusercontent.com/3094382/56097092-5e5fa800-5ef0-11e9-9af8-8936fb5f7fa7.png)

### Expected Behavior

It would be nice if these bindings were run through rustfmt, or just formatted a bit more friendly to RLS.

**Comment by alexcrichton** [comment]
Heh this is quite the interesting issue!

We actually [already have support](https://github.com/rustwasm/wasm-bindgen/blob/526b253b4790230e819aa78de21f03b94ec141bb/crates/web-sys/build.rs#L114-L124) for formatting the generated binding by setting the `WEBIDL_RUSTFMT_BINDING=1` env var, but we turned it off by default at the time it was added because the bindings were so large and executing `rustfmt` took far too long. 

Nowadays though with `web-sys` being much slimmer by default, I suspect we could flip the defaults! Could you try building with that env var locally and see if it improves the IDE experience?

**Comment by Pauan** [comment]
@alexcrichton Also, we should change [the docs](https://rustwasm.github.io/wasm-bindgen/api/web_sys/) so they properly format things.

I often try to use the `[src]` link to see how a particular type/method is implemented, but right now it's completely useless.

**Comment by Pauan** [comment]
I'm not sure when this regressed, but it seems that the `web-sys` docs are not being formatted, so they appear as a huge blob of unreadable code.

**Comment by alexcrichton** [comment]
This only works if `rustfmt` installed, so perhaps docs.rs was updated to not have `rustfmt` installed?
