### ISSUE TITLE
The type of the return of web_sys::MouseEvent::offset_* different from the spec

### ISSUE THREAD

**Issue by moshg** [rustwasm/wasm-bindgen#1471]
spec: https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface
api doc: https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.MouseEvent.html#method.offset_x

**Comment by alexcrichton** [comment]
In the WebIDL [that we use to generate bindings](https://github.com/rustwasm/wasm-bindgen/blob/68e6b4f1875d190a8b12ce1dfe9e316884539587/crates/web-sys/webidls/enabled/MouseEvent.webidl#L25) this is listed as `long` rather than `double`, so there's definitely a discrepancy!

I'm not entirely sure myself what the source of truth is, but out of curiosity did this cause issues for you locally?

**Comment by moshg** [comment]
No. This is just my curiosity.

I found this when I was following the link of the api doc. I think we should change the signature or the link (is there a document that says the return type is `long`?), remove the link or write the reason of discrepancy on the api doc.

**Comment by Pauan** [comment]
@moshg The link you posted is the Editor's Draft (as you can see on the left side of the page), which means it is not official. At the very top of the page it says this:

> ## Status of this document
>
> This is a public copy of the editors’ draft. It is provided for discussion only and may change at any moment. Its publication here does not imply endorsement of its contents by W3C. Don’t cite this document other than as work in progress. 

On the other hand, [the official Recommendation (not Editor's Draft) spec](https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-MouseEvent) uses `long` (which is `i32`).

It is likely that the Editor's Draft will one day become official, but right now it isn't.

This particular situation is rather complicated, since `offsetX` and `offsetY` have de-facto existed in browsers long before the spec: they existed all the way back in IE6, but they don't appear in the DOM Level 2 spec.

In practice the browsers have always used `long`. So this is actually a situation where the spec does not align with the actual behavior of browsers. Instead the spec is trying to *change* the behavior of browsers to use `double`, but the CSSOM spec hasn't been finalized yet.

So for now, `long` is correct, but after the CSSOM spec is finalized then `double` will be correct.

**Comment by moshg** [comment]
@Pauan
Thank you for your clear explanation!

It seems that MDN document should change or API doc should do if it's MDN doc's policy to follow the draft. I don't have the confidence to edit the documents well so can anyone do this?

Shoud I close this issue, or keep open until official coinsides with draft?

**Comment by alexcrichton** [comment]
Indeed thanks for the explanation @Pauan! In light of that  yeah I think we can go ahead and close this.

**Comment by Pauan** [comment]
> @moshg It seems that MDN document should change or API doc should do if it's MDN doc's policy to follow the draft.

MDN [pretty clearly says](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX#Return_value) "A `double` floating point value. Early versions of the spec defined this as an integer. See the Browser compatibility section for details."

It also [pretty clearly shows](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX#Browser_compatibility) when it was changed from `long` to `double` (apparently only in Chrome).

It also [says that the spec is a working draft](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX#Specifications), *and* it marks `offsetX` as experimental (using the beaker icon).

I don't think there's much more that MDN can do, their docs seem solid to me.

As for changing our own docs, I'm not sure what we would say, I think MDN covers it fairly well. Do you have any suggestions?

**Comment by moshg** [comment]
@Pauran

I think one might not understand MDN properly if he/she isn't well informed on the process of spec development.

In the Syntax section, MDN says "Early versions of the spec" and I read it as "Early versions of the draft spec" because MDN says "This is an experimental technology" and I didn't know there is the official spec.
If it says "officially `long` but `double` in the working draft" as you says above, I can understand it properly.

In the Specification section, there is only the link to the working draft. This also made me guess there is only the working draft.

In the Browser compatibility section, other than Chrome is marked with `?` not `✗`. Have it changed from `long` to `double` only in Chrome *apparently*?

**Comment by Pauan** [comment]
>  If it says "officially `long` but `double` in the working draft" as you says above, I can understand it properly.

On the [`clientX` page](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX#Return_value) it says:

```
A double floating point value, as redefined by the CSSOM View Module.
Originally, this property was defined as a long integer.
```

And [in the Specifications section](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX#Specifications) it links to the DOM Level 2 and 3 specs (where it is defined as `long`). I think this is basically what you want.

The difference with `offsetX` is that it *isn't* official, because it it was never in the official spec. It was only de-facto implemented by all browsers. So MDN saying that it is "officially `long`" would be incorrect.

> In the Specification section, there is only the link to the working draft. This also made me guess there is only the working draft.

Yes, your guess is correct, officially it only exists in the CSSOM working draft. So MDN is correct to only list the CSSOM working draft.

However, even though `offsetX` never existed in the spec before, it was de-facto implemented by all the browsers.

Unfortunately, because of the messy history of browsers, things are not always straightforward or easy to understand. This is one of those tricky cases.

> Have it changed from `long` to `double` only in Chrome *apparently*?

I'm actually not sure if it changed even in Chrome. It's quite rare to actually have a non-integer mouse/page/element position (since that implies sub-pixel positioning).

So even if Chrome did change to `double`, in practice it usually doesn't matter.

I think it would be nice to run some tests to verify which browsers return sub-pixel values.
