### ISSUE TITLE
Question about TodoMVC example

### ISSUE THREAD

**Issue by suyoshi** [rustwasm/wasm-bindgen#1554]
### Summary
I'm not sure if this is the right place to ask, but I'm currently studying the source code of the examples and can't wrap my head around this:
https://github.com/rustwasm/wasm-bindgen/blob/master/examples/todomvc/src/lib.rs#L41

How come the created structs are not dropped when the `app` call finishes? 
https://github.com/rustwasm/wasm-bindgen/blob/master/examples/todomvc/src/lib.rs#L65

Shouldn't at least this be called once the page is loaded?
https://github.com/rustwasm/wasm-bindgen/blob/master/examples/todomvc/src/view.rs#L423

Many thanks in advance and sorry if this is the wrong place.

**Comment by Pauan** [comment]
The key thing to note is that `Scheduler` is wrapped in an `Rc`, which is basically a reference-counted garbage collected object.

So when something is wrapped in `Rc`, that means it's possible for multiple parts of the program to have ownership of that object *at the same time* (in other words, the `Rc` can have multiple owners).

When *all* of the owners drop the `Rc`, then the underlying memory will be freed. But if at least one owner has access to the `Rc`, then the underlying memory will be kept alive, and won't be dropped.

This is the same as how garbage-collected languages work (except unlike a true garbage collector, `Rc` can't deal with cycles).

So let's follow what happens to the `Rc<Scheduler>`:

1. In `app`, [it is created](https://github.com/rustwasm/wasm-bindgen/blob/5233139b31e240bded7237788680a2831452fa3a/examples/todomvc/src/lib.rs#L42). So there is one owner for the `Rc` (which is the `app` function).

2. It calls `Rc::downgrade`, which does *not* create a new owner, so we can ignore that.

3. It calls `sched.clone()`, which *does* create a new owner, and then it passes that to `View::new`.

   So now there are two owners: `app` owns the `Rc`, and `View` also owns the `Rc` ([in its `sched` field](https://github.com/rustwasm/wasm-bindgen/blob/5233139b31e240bded7237788680a2831452fa3a/examples/todomvc/src/view.rs#L48)).

4. It [mutates the `Scheduler`, putting the `View` inside of itself](https://github.com/rustwasm/wasm-bindgen/blob/5233139b31e240bded7237788680a2831452fa3a/examples/todomvc/src/lib.rs#L51).

   This means that [the `Scheduler` owns the `View`](https://github.com/rustwasm/wasm-bindgen/blob/5233139b31e240bded7237788680a2831452fa3a/examples/todomvc/src/scheduler.rs#L11), and the `View` also owns the `Scheduler` (within its `sched` field). This creates a cycle.

5. Lastly, the `app` function ends, which drops the `sched` variable, and so `app` has now removed ownership of the `Scheduler`.

   But remember, `View` still owns the `Scheduler`, so the `Scheduler` will not be dropped until after the `View` is dropped.

   And `Scheduler` owns the `View`, so the `View` will not be dropped until after the `Scheduler` is dropped.

   Because the `Rc` is reference-counted, it cannot clean up cyclic memory, so the `Scheduler` and the `View` are never dropped.

   The only way to free the memory is to mutate the `View` or `Scheduler` and break the cycle.

**Comment by suyoshi** [comment]
Wow, that's really clever. Thank you for the sophisticated answer. It all makes sense now, thanks! :+1:

**Comment by Pauan** [comment]
(Personally, I think it's a bit *too* clever, I think a more explicit system would be better, rather than relying upon implicit `Rc` cycles. But that's a different topic)
