### ISSUE TITLE
clone vs Rc for HtmlElement (and other JS objects)

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1595]
### Summary

What does it mean that HtmlElement is `Clone`?

Specifically - if I have an element, and I clone it, am I getting a brand new copy of that element (i.e. under the hood it might be calling a `document.createElement`, copying props over, etc.) - or is it purely a Rustism that refers to cloning some sort of wrapper?

In other words, if I need to pass an element to multiple callbacks that each need to take ownership - do I gain anything by wrapping the element in a `Rc` or should I just `clone()` the element directly?

My use case right now is about HtmlElement but this might apply to other JsValues in general...

**Comment by Pauan** [comment]
You can think of `JsValue` as being the same as `Rc`, so cloning is cheap and does *not* make a copy.

There is a bit of overhead since it has to call into JS in order to allocate a new slot in the slab and return that to Rust, but the overhead should be constant.

What that means is that if you're doing a *lot* of clones (like say, thousands in a tight loop) then using `Rc` might give a small performance boost. But otherwise I wouldn't worry about it, using `clone` should be perfectly fine.

**Comment by dakom** [comment]
Great, thanks!
