### ISSUE TITLE
feat(cli-support) Emit other languages than JS/TS

### ISSUE THREAD

**Issue by Hywan** [rustwasm/wasm-bindgen#1628]
Howdy,

I would like to discuss about the possibility for `wasm-bindgen` to emit bindings for other languages than JavaScript/TypeScript (JS/TS). One can mention C, Python, PHP, Go etc.

Above the technical constraints, is it something you would agree with? If yes, then what are the difficulties? Do you think the rise of Web IDL can help to achieve that goal?

As I understand `wasm-bindgen`, the project is pretty modular. The source language (that is compiled to Wasm) is not necessarily Rust. So supporting bindings for different languages inside `wasm-bindgen` could make the project as the common tool to support Wasm bindings in various hosts.

Thoughts?

**Comment by alexcrichton** [comment]
Thanks for the report, and this is an interesting idea! Historically `wasm-bindgen` has always assumed that it would only ever be used to target JS, and a lot of our current structures reflect that. There's a lot that would need to be overhauled to get wasm-bindgen producing bindings for other languages, such as:

* Many APIs in `wasm-bindgen`-the-crate are very oriented towards JS: `JsValue`, all of `js-sys` and `web-sys`, many configuration of imports attributes in `#[wasm_bindgen]`, etc.
* The CLI tooling all assumes JS everywhere, especially in the flags taken by the CLI tooling.
* Conventionally most of the ecosystem around `wasm-bindgen` all assume that wasm-bindgen is equated with running on the web or in Node (aka JS)

These are all surmountable given the right amount of effort I think, but I also feel pretty strongly that `wasm-bindgen` should basically always follow the standards set in the wasm CG and conventions intended there. This seems like a much larger question than just `wasm-bindgen` to see how WebIDL bindings (or snowman bindings) interact with languages other than JS. 

The last part about standardization makes me feel that this conversation should probably happen on the WebIDL bindings repository rather than just `wasm-bindgen`. This is likely to affect the design of the bindings story itself if we decide to go down this road, and there's more consumers of the bindings story on that repository than this one!

I'm going to close this for now, but I would highly encourage starting discussions in the official WebIDL bindings repository!

**Comment by Pauan** [comment]
(The WebIDL discussions are happening [here](https://github.com/WebAssembly/webidl-bindings/issues))

**Comment by alexcrichton** [comment]
Oh one thing I should also mention is that binding to other languages is definitely in scope for WebIDL/☃ bindings, in addition to the DOM case. That story is emerging, and in `wasm-bindgen` we should make sure we follow those discussions, rather than trying to build something entirely different!

**Comment by Hywan** [comment]
Thanks for the reply, I appreciate the details. We are already discussing in various places of WebAssembly/design. I just wanted to know the position of `rustwasm/wasm-bindgen` regarding supporting different languages. Thank you very much :-)!
