### ISSUE TITLE
Dart binding

### ISSUE THREAD

**Issue by toxub23** [rustwasm/wasm-bindgen#1634]
For a long time in my company, we use Dart instead of JavaScript and recently we use Rust on our servers with the appropriate frameworks. Is there any chance that the work will expand and additionally you will make a binding not only to JavaScript but also to Dart? This would greatly simplify the work and Dart is more developmental than JavaScript.

**Comment by fitzgen** [comment]
Thanks for filing an issue; I think this question is largely answered in https://github.com/rustwasm/wasm-bindgen/issues/1628 for now.

**Comment by Pauan** [comment]
@toxub23 wasm-bindgen isn't designed to be run on the server, it's designed to be run in the web browser.

Since you're running on the server, you don't need wasm-bindgen.

Instead, I recommend trying [Dart's C FFI](https://dart.dev/server/c-interop) combined with [Rust's C FFI](https://doc.rust-lang.org/nomicon/ffi.html).
