### ISSUE TITLE
Build wasm during regular build?

### ISSUE THREAD

**Issue by justinmchase** [rustwasm/wasm-bindgen#1644]
### Summary
How can I build just the wasm file during a regular cargo build?

### Additional Details
I am not interested in building an entire npm package or running in nodejs even, so I don't really want the full `wasm-pack` route. I want to use [`paritytech/wasmi`](https://github.com/paritytech) to basically interpret wasm binaries directly. I want to have some libraries that get set as imports that can be referenced from the wasm modules I'm interpretting.

Ideally I would have a sub project which is a lib and referenced via:
```toml
[dependencies]
context = { path = "context" }
```

And the context is just a lib similar to the [add](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/add) example (sans nodejs).

I would like to do a single `cargo build` and have it produce a wasm file which I can load from disk at runtime.

Is this possible right now? How could I modify the `add` example library to produce a .wasm file during `cargo build`?

When I build today it appears to only generate a `.so` file by default.

**Comment by Pauan** [comment]
You can just do `cargo build --target wasm32-unknown-unknown` to generate a `.wasm` file (it will be in the `target/wasm32-unknown-unknown/{release/debug}` folder)

Since you're using a wasm interpreter, you can't use wasm-bindgen, since wasm-bindgen is designed for JS, therefore it generates JS shims.

So you'll have to create your own bindings, like this:

```rust
#[no_mangle]
pub extern "C" fn add(a: i32, b: i32) -> i32 {
    a + b
}
```

Or if you want to import wasm functions from the host:

```rust
extern "C" {
    fn foo(x: i32) -> i32;
}
```

You'll want to read these:

https://doc.rust-lang.org/std/keyword.extern.html

https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#using-extern-functions-to-call-external-code

https://doc.rust-lang.org/reference/items/external-blocks.html

https://doc.rust-lang.org/nomicon/ffi.html

Keep in mind that the Rust FFI is generally based around C, and wasm is more restrictive than C, so not everything will work.

**Comment by alexcrichton** [comment]
@Pauan has you covered for executing Cargo to produce a wasm file, and currently Cargo has no capability to produce both a native binary and a wasm binary as part of the same build, but a feature could be requested on Cargo for that!

**Comment by justinmchase** [comment]
Thanks! The `--target` flag was the key I was missing.
