### ISSUE TITLE
No documentation on docs.rs

### ISSUE THREAD

**Issue by mstange** [rustwasm/wasm-bindgen#167]
https://docs.rs/wasm-bindgen/0.2.5/wasm_bindgen/ shows "The requested resource does not exist".

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately this is due to the nightly requirement of this crate and the fact that the nightly version on docs.rs isn't quite as up-to-date as necessary to build documentation. I don't think there's much that can be done about that unfortunately but hopefully soon the features that wasm-bindgen uses will be more stable!
