### ISSUE TITLE
Lazy Static / Global JsValue Support

### ISSUE THREAD

**Issue by Warfields** [rustwasm/wasm-bindgen#1714]
## Summary

I'm not sure if the following is a bug report or a feature request. So if some could help me identify what it is and how to proceed that'll answer this question.

### The Issue/Bug
I have an external JS module keep track of a couple of things, the details aren't too important. I need to access this module in several locations so I'm using lazy_static to allow for this. Unfortunately this does not work.

```
...
#[wasm_bindgen(module = "src/js/shim.js")]
extern "C" {
    type WasmBinList;

    #[wasm_bindgen(constructor)]
    fn new() -> WasmBinList;
}

lazy_static! {
    static ref GLOBAL_BINARY_CONTROLLER: WasmBinList = WasmBinList::new();
}
...
```

Which results in the following error:

```
error[E0277]: `*mut u8` cannot be shared between threads safely
  --> src/lib.rs:49:5
   |
49 |     static GLOBAL_BINARY_CONTROLLER: WasmBinList = WasmBinList::new();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `*mut u8` cannot be shared between threads safely
   |
   = help: within `WasmBinList`, the trait `std::marker::Sync` is not implemented for `*mut u8`
   = note: required because it appears within the type `std::marker::PhantomData<*mut u8>`
   = note: required because it appears within the type `wasm_bindgen::JsValue`
   = note: required because it appears within the type `WasmBinList`
   = note: shared static variables must have a type that implements `Sync`
```

If anything is there another way to get a globally scoped object that contains a JsValue or a way to fix the issue caused by the mutable pointer? (Bug fix or new feature?)

**Comment by Pauan** [comment]
The reason for this is because it is not possible to use or send JS values between threads. This is a limitation in Wasm, not Rust, so there's not much we can do about it right now.

This is actually a great example of how Rust's compile-time guarantees prevent potential bugs, since Rust is preventing you from causing thread unsafety.

The solution is to use [`thread_local`](https://doc.rust-lang.org/nightly/std/macro.thread_local.html), which creates a new value per thread:

```rust
thread_local! {
    static GLOBAL_BINARY_CONTROLLER: WasmBinList = WasmBinList::new();
}
```

As a bonus, it no longer needs to be thread safe, so you can now use `Rc`, `RefCell`, etc.

To access the variable you use the [`with` method](https://doc.rust-lang.org/nightly/std/thread/struct.LocalKey.html#method.with):

```rust
GLOBAL_BINARY_CONTROLLER.with(|x| { ... })
```

**Comment by Warfields** [comment]
Ah thank you @Pauan for the clear a concise explanation!

**Comment by paytonrules** [comment]
I know this is a closed thread but @Pauan do you mind clarifying what threads have to do with it? I ran into this same problem and while your explanation (and the error) makes sense if I was using threads, I'm not, so why does it come up.

**Comment by Pauan** [comment]
@paytonrules Rust is designed to *always* be thread-safe, even if you happen to be using a single thread.

This means all libraries are guaranteed to be thread safe, so you never need to worry about threading (unlike C/C++ where threading is a huge problem). Imagine if you couldn't use a library because it was designed for single threading only, Rust prevents that.

And it makes it easier to upgrade your program to be multi-threaded later.

In the future wasm-bindgen will become multi-threaded by default (just like native Rust), so making your programs thread-safe will prevent future breakage.

**Comment by H2CO3** [comment]
@paytonrules Statics are accessible to all threads, hence they _must_ be thread-safe. The compiler can't possibly prove/know whether or not you dynamically happen to use multithreading.
