### ISSUE TITLE
spawn_local demands unnecessary static lifetime

### ISSUE THREAD

**Issue by UnHumbleBen** [rustwasm/wasm-bindgen#1733]
### Summary

`spawn_local` requires `'static` lifetime. I have a type `T` owned by a shared pointer, `Rc<RefCell<T>>`. Doesn't this share pointer have static lifetime? After all, `T` does not get dropped until `Rc<RefCell<T>>` gets dropped. 

### Additional Details
I have a function here that takes a shared pointer to an `ReactiveComponent` and calls its render method whenever a message is received from the `MPMCFutReceiver`
```rust

fn spawn_listener<T>(
    component: Rc<RefCell<T>>,
    reciever: MPMCFutReceiver<Render>,
) where
    T: ReactiveComponent,
{
    let component_clone = Rc::clone(&component);

    spawn_local(reciever.for_each(move |_| {
        //-- Use `component_clone`  to render --

        Ok(())
    }));
}
```
The compiler complains:
```
error[E0310]: the parameter type `T` may not live long enough
   --> src/view.rs:110:5
    |
100 | fn spawn_listener<T>(
    |                   - help: consider adding an explicit lifetime bound `T: 'static`...
...
110 |     spawn_local(reciever.for_each(move |_| {
    |     ^^^^^^^^^^^
    |
```
This does not make sense to me because the closure takes ownership of the shared pointer and therefore `T`, so surely `T` itself doesn't need to meet the `static requirement since the shared pointer does?

**Comment by Pauan** [comment]
The error is correct, you need to add a `where T: 'static` bound.

The reason is because `T` might be a reference, like `&Foo`. Consider this:

```rust
let foo = Foo::new();
let foo = &foo;
let rc = Rc::new(RefCell::new(foo));
```

In this case `rc` has the type `Rc<RefCell<&Foo>>`, which means that the `Rc` is not allowed to outlive the variable `foo`.

But when you spawn a Future, it is executed asynchronously, so when the Future runs, the variable `foo` no longer exists, so that would be a use-after-free (which is not allowed).

To prevent that, `spawn_local` requires a `'static` lifetime, so that way it prevents you from putting a reference inside of the `Rc<RefCell<T>>`.

**Comment by alexcrichton** [comment]
I believe @Pauan is right here in that `T: 'static` is required, so I'm going to close this.

**Comment by rkuhn** [comment]
Given that `spawn_local` is offered by a thread-local executor, there is an upper bound on when the Future may be executed; this is very similar to an iterator that captures a reference and then carries that reference’s lifetime with it. As long as the executor lives longer than the Future, all is good, right?

So would a patch be acceptable that added a lifetime parameter to LocalPool and used that as a lifetime bound in `spawn_local`?

**Comment by Pauan** [comment]
@rkuhn The problem isn't the lifetime of the executor (the executor already lives basically forever). The problem is with the *stack*.

Futures are run asynchronously, therefore they will always outlive the stack, therefore they cannot contain stack references, because if they contained stack references they could trigger use-after-free by accessing the stack reference after the stack frame is gone.

That's why they must be `'static`, which restricts them to contain only owned values or `'static` references (no stack references). This isn't something which can be "fixed", it's just fundamentally how Futures (and Rust) works. It's the same reason why [`thread::spawn`](https://doc.rust-lang.org/nightly/std/thread/fn.spawn.html) requires `'static`.

Consider a program like this:

```rust
{
    let x = vec![];

    let r = &x;

    spawn_local(async move {
        sleep(5000).await;
        println!("{:?}", r);
    });
}
```

Here is what happens:

1. It allocates `x` on the stack.

2. It creates a reference to `x` (called `r`).

3. It creates a Future (using `async`) and moves the reference `r` into it.

4. It spawns the Future asynchronously.

5. It reaches the end of the scope, so it drops `x`.

6. The Future will wait for 5 seconds and then print `r`.

Do you see the problem? The problem is that immediately after spawning the Future, it then drops `x`, because it reached the end of the scope. This happens long before the Future prints `r`. Therefore, when 5 seconds have passed, the Future would be accessing `r` after `x` had been freed. That's use-after-free, which is undefined behavior.

This is exactly the sort of undefined behavior that `'static` prevents.

The important thing to understand is that `spawn_local` does *not* wait for the Future to finish, it starts the spawning process and then immediately returns `()` (before the Future has finished), which means the Future is running in parallel with your code. That's what "asynchronous" means.

Why doesn't it wait for the Future to finish? Because that's impossible with JavaScript, there is no API for blocking.

**Comment by rkuhn** [comment]
What you’re saying is all correct for an executor that runs at some later point. The LocalPool, however, lives on the stack: I have a use-case (in a test) where the LocalPool is started in a function and dropped within that same function, with a Future being run in between. This Future is needlessly required to have `'static` lifetime.

**Comment by rkuhn** [comment]
Just to be very clear: your point 4 above is not correct, LocalPool is not asynchronous — if you don’t run the pool on the current thread nothing happens, and nothing will happen after the LocalPool is dropped, either.

**Comment by Pauan** [comment]
@rkuhn As I said, `LocalPool` and `block_on` and similar do not work in Wasm, because JavaScript does not provide a blocking API. But hypothetically, if they did work... you could just use them instead of `spawn_local`.

The `spawn_local` function is equivalent to [`tokio::spawn`](https://docs.rs/tokio/0.2.0-alpha.6/tokio/fn.spawn.html) or [`runtime::spawn`](https://docs.rs/runtime/0.3.0-alpha.8/runtime/fn.spawn.html) or [`LocalSpawn`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures_core/task/trait.LocalSpawn.html) (all of which accept `'static`).

They are designed that way because being able to run Futures concurrently in the background is *very* useful, and is the normal way of using Futures. Using `block_on` (et al) is only recommended inside of unit tests, because it blocks *all* Futures (and all computation in general) on the current thread.

Therefore, `spawn_local` *cannot* be changed, but even if it *could* change, it shouldn't, because the current design is correct and idiomatic.

**Comment by rkuhn** [comment]
My apologies, I searched the web for `spawn_local` and found this issue but didn’t check which repo it is in: I was talking about [LocalPool](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-executor/src/local_pool.rs) while you were talking about [something else entirely](https://github.com/rustwasm/wasm-bindgen/blob/bdcf27c7cb0f8d01f59b770e75daf256c72e960d/crates/futures/src/lib.rs#L75).
