### ISSUE TITLE
How to get navigator.webdriver?

### ISSUE THREAD

**Issue by Elufimov** [rustwasm/wasm-bindgen#1755]
### Summary

Webdriver getter exists in NavigatorAutomationInformation https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.NavigatorAutomationInformation.html#method.webdriver and obviously this code
```rust
 let window = window().expect("no global `window` exists");
 let navigator = window.navigator();
 let webdriver = navigator.webdriver();
```
will result to error
```
error[E0599]: no method named `webdriver` found for type `web_sys::Navigator` in the current scope
  --> src\lib.rs:27:32
   |
27 |     let webdriver = navigator.webdriver();
   |                                ^^^^^^^^^
```
And I cant cast Navigator to NavigatorAutomationInformation.

**Comment by Pauan** [comment]
@Elufimov [`navigator.webdriver`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) is an experimental API which has not been standardized yet. We only support standardized APIs.

We've [discussed](https://github.com/rustwasm/wasm-bindgen/pull/1712#issuecomment-519590260) adding in support for unstable APIs, with the caveat that they can break at any time, so you can't rely upon them.

On the other hand, perhaps we can make an exception here, since it seems to be supported in all browsers, and it's just a simple `bool`, nothing complex.

**Comment by Elufimov** [comment]
Supporting only stable set of api is completely reasonable. 
> On the other hand, perhaps we can make an exception here, since it seems to be supported in all browsers, and it's just a simple bool, nothing complex.

If this is possible it would be great.

**Comment by alexcrichton** [comment]
Seems reasonable to me to add if everything already supports it!

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/rustwasm/wasm-bindgen/issues/1950 which tracks how we'll be handling unstable web features (or at least not yet standardized)
