### ISSUE TITLE
WebGl2RenderingContext cast to WebGlRenderingContext

### ISSUE THREAD

**Issue by zvxryb** [rustwasm/wasm-bindgen#1767]
A WebGL 2.0 rendering context cannot be cast to a 1.0 context using `dyn_ref`, but `unchecked_ref` succeeds and appears to produce the expected result, at least in my test application.  From an API standpoint, the available methods in 2.0 appear to be a superset of calls in 1.0.  There's a few differences in terms of behavior of a 2.0 context vs a 1.0 context, but I'm not sure if these differences are really significant from a practical standpoint (one would assume if you're casting between these types you're aware of what that implies).  MDN docs even suggest that `WebGl2RenderingContext` "inherits" from `WebGlRenderingContext`, though I'm not sure if that's actually part of the spec.

So my questions are:

1. Is the omission of a `dyn_ref` cast by design or simply something that was overlooked?
2. Is an `unchecked_ref` cast to a 1.0 context a well-defined operation, or is it possible I might encounter trouble in the future?  (assuming I'm writing my code with either possible version in mind)

Being able to cast from 2.0 to 1.0 would really be an advantage for cross-browser support in the case where you want to use a few 2.0 features, when available.  The alternative (if such a cast is not meant to be supported) seems like it would require a lot of code duplication and indirection.

**Comment by Pauan** [comment]
According to [the spec](https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7) (which is currently in draft and isn't final), `WebGL2RenderingContext` does **not** inherit from `WebGLRenderingContext`.

I don't know why they decided to make it not inherit. But in any case, web-sys is auto-generated from the official WebIDL, so web-sys's behavior is correct (at least according to the spec).

And after running some tests, it seems that in the browsers it doesn't inherit either:

```rust
var canvas = document.createElement('canvas');
var gl = canvas.getContext('webgl2');
gl instanceof WebGL2RenderingContext // true
gl instanceof WebGLRenderingContext // false
```

So the browsers are following the spec, and therefore have the same behavior as web-sys.

> Is an unchecked_ref cast to a 1.0 context a well-defined operation, or is it possible I might encounter trouble in the future?

Right now it will work, but in the future when we switch to host bindings then it will probably break.

And even if it doesn't break, it will perform slower than it should. So I recommend **not** using `unchecked_ref` in this situation.

> The alternative (if such a cast is not meant to be supported) seems like it would require a lot of code duplication and indirection.

That's rather tricky. You basically have two options: an enum...

```rust
enum WebGlContext {
    V1(WebGlRenderingContext),
    V2(WebGl2RenderingContext),
}
```

...or a trait:

```rust
trait WebGlContext {
    // methods which are in common between WebGlRenderingContext and WebGl2RenderingContext
}
```

In either case I would *highly* suggest using a macro to generate the code, so that way you avoid code duplication.

**Comment by zvxryb** [comment]
Thanks for the clarification.  It sounds like a trait and a macro is the way to go.

**Comment by zvxryb** [comment]
This is what I ended up with: [gl_context.rs](https://gist.github.com/zvxryb/be1405e45b5a5ac2244c191e84723736)

It only forwards the methods I'm using, but it's trivial to add others (just write out method name + type signature).  It also doesn't forward numeric constants, but the spec draft (linked above) shows they're identical between 1.0/2.0 so you can use them from WebGlRenderingContext directly:

> WebGL2RenderingContext includes WebGLRenderingContextBase;
