### ISSUE TITLE
performance.now() throws bootstrap.js:122 Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by Duddino** [rustwasm/wasm-bindgen#1770]
### Describe the Bug

performance.now() throws bootstrap.js:122 Uncaught TypeError: Illegal invocation

### Steps to Reproduce

1. Create a new project
2. write ```#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = performance)]
    pub fn now()->f64;
}```
3. Use now() in a function

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Actual Behavior

A clear and concise description of what actually happened.

**Comment by Pauan** [comment]
This happens because wasm-bindgen generates the equivalent of this code:

```js
var x = performance.now;
x();
```

As you can see, that gives the same error. So I guess we need to tweak the behavior of `js_namespace`.

However, you don't need to create your own bindings for `performance.now`, since we already have them in the [`web-sys`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Performance.html#method.now) crate.

**Comment by Duddino** [comment]
Ok, I guess I can close this.
