### ISSUE TITLE
(Partially) generate Rust type & function declarations from TypeScript type definiton file or JSDoc

### ISSUE THREAD

**Issue by adiba** [rustwasm/wasm-bindgen#18]
Of course this does not work for some types..
This might belong in another repo.

**Comment by alexcrichton** [comment]
Nah definitely! I could totally see something like

```rust
wasm_bindgen_typescript!("foo.d.ts");
```

being used

**Comment by adiba** [comment]
I thought of it as a separate nodejs tool since the Typescript parser is a node module. I could attempt writing a provisional script, but I know nothing about macros... yet.

**Comment by adiba** [comment]
TypeScript also has modules and interfaces, which could be directly translated to Rust modules and traits with ease, so support for these would be great.

**Comment by alexcrichton** [comment]
Yeah I'm not sure what the best way to do this would be. I'd naively prefer to start off with a syn-based parser (just in the procedural macro itself) rather than picking up a dependendy through node, but I'm not sure how easily that'll work. 

Alternatively there could be a JS tool which takes a `foo.d.ts` and emits a `foo.rs` with `#[wasm_bindgen]` anntoations maybe

**Comment by alexcrichton** [comment]
This is similar to https://github.com/alexcrichton/wasm-bindgen/issues/42 as well

**Comment by alexcrichton** [comment]
Experimental support for this is now in the repository and future work is tracked with a [label](https://github.com/rustwasm/wasm-bindgen/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Afrontend%3Atypescript+), so I'm gonna close this for now
