### ISSUE TITLE
Reduce amount of web-sys features

### ISSUE THREAD

**Issue by kpcyrd** [rustwasm/wasm-bindgen#1821]
There's currently a discussion going on about web-sys: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942487

To summarize, web-sys has around 1.2k features which causes our tooling to generate a 256k `Provides:` line of virtual packages. This package caused issues in tooling used by debian downstreams, including kali linux and tails.

Any chance the number of features can be reduced to a reasonable amount?

**Comment by alexcrichton** [comment]
Thanks for the report, but the features of the crate are a feature of how the crate works, so this isn't going to change.

**Comment by Pauan** [comment]
(The reason for the large number of features is because [compilation would be exceptionally slow otherwise](https://github.com/rustwasm/wasm-bindgen/pull/790), because web-sys is quite large)

**Comment by sdroege** [comment]
Maybe instead of doing it on a per-function basis, per-category like in winapi would be an option?

**Comment by Pauan** [comment]
@sdroege It already is per-category. Specifically, it's per-type, since WebIDL segregates features based on type.

So, for example, if you enable the `Element` feature you will get access to all of the [Element methods](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Element.html).

The problem is that there are thousands of types for WebIDL. The web is huge!
