### ISSUE TITLE
Cannot `.dyn_into::<AngleInstancedArrays>()`

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-bindgen#2003]
```rust
#[wasm_bindgen_test]
fn angle_instanced () {
  // Works as expected - confirmed I am able to do instanced rendering
  // with the returned `AngleInstancedArrays`
  get_webgl()
  .unwrap()
  .get_extension("ANGLE_instanced_arrays")
    .unwrap()
    .unwrap()
    .unchecked_into::<AngleInstanceArrays();

  // Panics
  get_webgl()
  .unwrap()
  .get_extension("ANGLE_instanced_arrays")
    .unwrap()
    .unwrap()
    .dyn_into::<AngleInstancedArrays>()
    .unwrap(); // <--- Panics here
}


fn get_webgl() -> Result<WebGlRenderingContext, JsValue> {
    let canvas: HtmlCanvasElement = document().create_element("canvas")?.dyn_into()?;

    let gl = canvas
        .get_context("webgl")?
        .expect("WebGL Context")
        .dyn_into()?;

    Ok(gl)
}
```

I'm imagining that this has something to do with how WebGL extensions WebIDLs are handled/defined?

**Comment by Pauan** [comment]
In [the spec](https://www.khronos.org/registry/webgl/extensions/ANGLE_instanced_arrays/), `ANGLE_instanced_arrays` is marked as `[NoInterfaceObject]`, which means it doesn't actually exist.

You can verify this yourself: `ANGLE_instanced_arrays` and `AngleInstancedArrays` don't exist in the browser:

```js
Uncaught ReferenceError: ANGLE_instanced_arrays is not defined
Uncaught ReferenceError: AngleInstancedArrays is not defined
```

Since those classes don't exist, that means it's not possible to do any runtime checks, which is why `dyn_into` doesn't work. So using `unchecked_into` is correct.

**Comment by chinedufn** [comment]
Ahh - I didn’t actually know what dyn_into did I’ve just always used it without any trouble and never needed to think about it.

Makes sense - thanks!

**Comment by Pauan** [comment]
What `dyn_into` does is basically `foo instanceof Bar`, so it's doing a runtime check to make sure that the object is the right class.

Whereas `unchecked_into` just *assumes* that it's the right class, so it doesn't do any checks, so it's faster, but less safe (since you might make a mistake and use the wrong class).
