### ISSUE TITLE
Unify window and web worker API

### ISSUE THREAD

**Issue by chemicstry** [rustwasm/wasm-bindgen#2060]
### Motivation

There are multiple APIs that are available to both window thread and web workers such as `requestAnimationFrame` or `performance.now`, but they are in different scopes. As far as I understand, the only way to access these functions with `web_sys` is through `window()` which most libraries use. However, this makes the code unable to run on a web worker, even though those functions are available but under different scope.

I don't know what's the correct way to access them under web worker, but I've seen only two options:
- Writing a custom binding (like with console.log example in the book)
- Accessing through js-sys `js_sys::global().unchecked_into::<DedicatedWorkerGlobalScope>()`. EDIT: it seems that `DedicatedWorkerGlobalScope` doesn't have most of these either.

This requires that all crates that use these functions implement some differentiation between window and web worker and most of them don't

### Proposed Solution

Would it be possible to somehow unify the API? For exmaple, `requestAnimationFrame` exists under global scope in most browsers and web workers. Maybe it could be accessed without firstly getting access to window?

**Comment by alexcrichton** [comment]
Thanks for the report! We've discussed this previously and our conclusions have historically been that this is something that would be great to tackle, but we're unlikely to do so in this repository. The js-sys/web-sys APIs are intended to be low-level bindings and this level of abstraction is left to other crates (such as the `gloo` family of crates). 

I'm going to close this becaue this is unlikely to get fixed in this repository itself, but it would still be great to fix and if so we'd be happy to document it here if necessary!
