### ISSUE TITLE
Sudden drop of FPS in conditional branch

### ISSUE THREAD

**Issue by Nhyarlathotep** [rustwasm/wasm-bindgen#2063]
I'm having fun making a wolf3D clone in rust, but I'm encountering a troublesome problem:

```rust
pub fn ray_cast(map: &Map, player: &Player, camera_dir: Vector2f) -> Option<Ray> {
    let mut ray = Ray::new(player, &camera_dir);

    loop {
        ray.grow();

        match map.cell(&ray.pos) {
            None => {
                return None;
            }
            Some(Cell::Empty) => {
                //continue;
            }
            Some(Cell::Wall { .. }) => {
                break;
            }
            Some(Cell::Door(door)) => {
                /*if ray.grow_to_thin_wall(door.slide, 0.5) {
                    break;
                }*/
            }
        }
    }
   Some(ray)
}
```
When I call a method from the Ray object in the match braces, I lose 15 to 20 FPS.
This is due to calling the `memcpy` function when I look at the performance tab of my browser(Firefox).

You can check a live example of the problem here: https://nhyarlathotep.github.io/wasm-wolf32/

I there something I am doing wrong ?
Thank you for your help.

**Comment by alexcrichton** [comment]
Thanks for the report! This seems pretty unlikely to be due to wasm-bindgen, however, and more likely to be related to the runtime of the code itself. I'd recommend using the [time profiling section of the book](https://rustwasm.github.io/docs/book/reference/time-profiling.html) to try to narrow down what's taking so long, and also I'd remind to be sure you're compiling with `--release`!
