### ISSUE TITLE
Can it be used to "in reverse", to generate binding for loadable Wasm-based plugins?

### ISSUE THREAD

**Issue by vi** [rustwasm/wasm-bindgen#2107]
Suppose there is a Rust project using `wasmi` or `wasmtime` to embed WebAssembly runtime, which runs pluings, also typically compiled from Rust.
Can `wasm-bindgen` be used to streamline calls into/from plugins, with Rust at both sides, without Javascript anywhere nearby? Or are there other projects for this?

**Comment by alexcrichton** [comment]
Currently wasm-bindgen is only focused on going from Rust code to generating JS/wasm files, not the other way around (consuming the wasm). Currently that space is nebulous enough it's not entirely clear how wasm-bindgen fits into the picture, so there's not a huge amount that can be done at this time. I'm not personally aware of many projects since the space of running wasm outside the browser is still relatively new, but I suspect lots will happen in the near future!
