### ISSUE TITLE
SubtleCrypto.sign and SubtleCrypto.generateKey methods return wrong type

### ISSUE THREAD

**Issue by renatoathaydes** [rustwasm/wasm-bindgen#2126]
[`SubtleCrypto.generateKey`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey)'s methods (e.g. [`generate_key_with_str`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.SubtleCrypto.html#method.generate_key_with_str))'s return type is `Result<Promise, JsValue>`, but should be, according to MDN Docs, either `Result<Promise, CryptoKey>` or `Result<Promise, CryptoKeyPair>` instead.

I believe this would be a simple Rust `enum` with either `CryptoKey` or `CryptoKeyPair` similar to TypeScript's `CryptoKey | CryptoKeyPair`.

Similarly, [`SubtleCrypto.sign`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign) methods (e.g. [sign_with_str_and_buffer_source](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.SubtleCrypto.html#method.sign_with_str_and_buffer_source)) should return a Promise of [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer), but currently have return type `Result<Promise, JsValue>` in Rust.

Without the right types, creating a key and signing a payload is very hard in Rust.

**Comment by Pauan** [comment]
@renatoathaydes The types are correct. `Result` is used for errors: the first type is the successful type, and the second type is the error type.

In addition, even the WebIDL says that the return type is [`Promise<any>`](https://www.w3.org/TR/WebCryptoAPI/#subtlecrypto-interface), so we cannot provide a better type for it. So the WebIDL would need to be fixed first, since we generate our APIs from the WebIDL.

Although the lack of typing is slightly annoying, it isn't that big of a deal, since you can just do this:

```rust
let value = JsFuture::from(crypto.generate_key_with_str(...)?).await?;
let value = value.dyn_into::<CryptoKeyPair>().unwrap();
```

**Comment by renatoathaydes** [comment]
It's kind of a big deal I think, because it's completely type unsafe to do this:

```rust
    let crypto = window.crypto().expect("Crypto does not exist").subtle();

    let key_promise = crypto.generate_key_with_str("RSA-PSS", true, &JsValue::from("sign"))
        .expect("Key not generated");
    let key_pair: CryptoKeyPair = JsFuture::from(key_promise).await.unwrap().into();

    let private_key: CryptoKey = Reflect::get(&key_pair, &JsValue::from("privateKey"))
        .expect("privateKey").into();

    let signature_promise = crypto.sign_with_str_and_u8_array("RSA-PSS", &private_key, &mut [1u8, 2u8, 3u8])
        .expect("signature");
    let signature = JsFuture::from(signature_promise).await.unwrap();

```

When I run this , it just crashes in the browser and I have no idea why. The lack of type-safety is very contrary to using Rust in the first place :/

**Comment by renatoathaydes** [comment]
I suspect it's crashing for me because the last argument to `generate_key_with_str` is declared in Rust as `key_usages: &JsValue` while the real API expects an array of strings.

But I can't find out how to create an array of Strings for JS. The code happily compiles, again, because of the complete lack of real types in the Rust declarations.

**Comment by Pauan** [comment]
@renatoathaydes That's just the nature of JS. It's fundamentally impossible to fully statically type JS. It's not even possible to convert TypeScript types into Rust types, because JS and TypeScript are both far too dynamic.

We try to make the types as best as we can, but it's always an approximation, especially for web-sys (which is automatically generated from WebIDL). That's why we provide `JsCast` as an "escape hatch".

What you are asking for is essentially like saying, "Rust should be able to have a fully statically type safe FFI to C". It just cannot happen, because C's type system is too dynamic and unsafe. Instead the solution is to create safe Rust wrappers around the unsafe poorly typed C code.

Just like how the C FFI is unsafe and poorly typed, the same is true for JS: if you use the raw web-sys APIs then you need to deal with the quirks and issues of JS. Web-sys is very low level, it's intentionally designed to be as close to JS as possible (similar to how [the various `-sys` crates](https://crates.io/search?q=-sys) are designed to be as close to C as possible).

So the recommendation is to wrap the web-sys APIs in a high level safe API, like this:

```rust
pub enum CryptoKey {
    Single(web_sys::CryptoKey),
    Pair(web_sys::CryptoKeyPair),
}

pub async fn generate_key(algorithm: &str, extractable: bool, key_usages: &[&str]) -> Result<CryptoKey, JsValue> {
    let key_usages = key_usages.into_iter()
        .map(|x| JsValue::from(x))
        .collect::<Array>();

    let key = JsFuture::from(window()
        .unwrap()
        .crypto()?
        .subtle()
        .generate_key_with_str(algorithm, extractable, &key_usages)).await?;

    match key.dyn_into::<web_sys::CryptoKey>() {
        Ok(key) => Ok(CryptoKey::Single(key)),
        Err(key) => Ok(CryptoKey::Pair(key.dyn_into::<web_sys::CryptoKeyPair>().unwrap())),
    }
}
```

Creating these sorts of high level APIs is what [gloo](https://github.com/rustwasm/gloo) is designed for.

**Comment by renatoathaydes** [comment]
> It's fundamentally impossible to fully statically type JS.

We're talking about Web APIs here, not arbritary JS code. All Web APIs are properly typed, and I pointed to links where the types are declared. I don't know why the IDL you're using ignores those types, but I'm pretty sure the MDN docs are more correct than the IDL.

The `CryptoKey` type you declared above exactly matches the documented type, for example, for what `generate_key` methods should be returning (wrapped into `Promise` and `Result` but you know what I mean).

What I am actually saying is "web_sys should be able to provide types that are safe to use from Rust" but it is not currently doing that. You claim that it's because that's impossible is directly contradicted by your own example of what the type should've been in this example.

I will have a look at `gloo` because, as is, web_sys is basically un-usable by itself. Thanks for the assistance.

**Comment by Pauan** [comment]
> All Web APIs are properly typed, and I pointed to links where the types are declared.

According to the WebIDL, it returns `Promise<any>`. So please direct any complaints about incorrect types to them.

> I'm pretty sure the MDN docs are more correct than the IDL.

The WebIDL is the official standardized spec, which is implemented in all browsers.

MDN is a community-run wiki. We do not generate bindings from MDN, and we *cannot* generate bindings from MDN, because MDN does not list the types in a standard format, whereas WebIDL does.

As I have said multiple times, we do not create the web-sys bindings by hand, they are automatically generated. There are many thousands of web APIs, we do not have the manpower to create the bindings by hand. Therefore we must automatically generate them. But in order to generate them, we need a standard format specifying the types. That is what WebIDL is.

And in any case, JS types do not have generics, so the best we can do right now is `Promise`.

> What I am actually saying is "web_sys should be able to provide types that are safe to use from Rust" but it is not currently doing that.

The goal of web-sys has always been to provide the raw direct bindings to JS APIs.

Its goal was never to provide idiomatic Rust bindings, since that would be extremely impractical, because idiomatic APIs must be handcrafted, but there are far too many APIs to handcraft.

That's why gloo exists: to create handcrafted idiomatic APIs for only the most commonly used web APIs.

> You claim that it's because that's impossible is directly contradicted by your own example of what the type should've been in this example.

That is not true. The type I gave is a handcrafted Rust type which used dynamic type checking to create the correct enum variant. That sort of handcrafted code cannot always be automated.

Also, just because it's possible to take a *subset* of JS programs and give them Rust types does not invalidate anything I said, because there are APIs which truly cannot be made into Rust types (such as JS functions accepting a variable number of arguments of different types, or APIs that use type overloading).

> web_sys is basically un-usable by itself

It's perfectly usable as long as you're willing to use `JsCast` (which is almost always mandatory when dealing with JS code, because of its dynamic nature), and wrap the web-sys APIs in a high level API.

**Comment by Pauan** [comment]
P.S. If you use [console_error_panic_hook](https://crates.io/crates/console_error_panic_hook) it will greatly improve the error messages. This is very useful for debugging problems when writing JS code.

**Comment by renatoathaydes** [comment]
> The WebIDL is the official standardized spec, which is implemented in all browsers.

I supposed you're not familiar with how the web APIs have been evolving lately. I would like to agree with you, but the standards are really not as important as they should be: what matters is what the 2 big browsers do, and the most likely will agree with the MDN docs (which every dev in the world uses as a reference) instead of the standards IDL.

**Comment by Pauan** [comment]
@renatoathaydes I am quite familiar with how the web standards work, I have 14 years of experience with the JavaScript web ecosystem. You are correct that the top-down approach of the W3C is over, but you seem to be incorrectly conflating that with WebIDL.

WebIDL is just a format for specifying the types of web APIs. It is used by the W3C, but it is *also* used by [WHATWG](https://en.wikipedia.org/wiki/WHATWG), which is a collaboration of the major browser vendors. The browsers *do* follow the WHATWG specs, because the browsers *created* the WHATWG specs. The specs didn't go away, they just switched from the W3C to the WHATWG.

Also, the WebIDL that web-sys uses is directly taken from the Firefox source code, so it matches exactly with what Firefox itself does (which in turn is based on the WHATWG specs).

In any case, as I said, it is impossible for us to use MDN, because MDN does not provide a standard format for the types. And even if we used MDN, the type would still be `Promise`, because of the lack of generics.

**Comment by NeverGivinUp** [comment]
> Its [web-sys] goal was never to provide idiomatic Rust bindings [...] because idiomatic APIs must be handcrafted, but there are far too many APIs to handcraft.
> 
> That's why gloo exists: to create handcrafted idiomatic APIs for only the most commonly used web APIs.

Actually, since there has not been much going on in gloo lately, I was wondering where gloo is. If it is done, more or less.

Guessing from your statement @Pauan, I take it that list of the "the most commonly used web APIs" would be the "Are we Gloo yet", that would allow seeing, where gloo is headed and how far it is from being done, right?

**Comment by Pauan** [comment]
> @NeverGivinUp I was wondering where gloo is. If it is done, more or less.

It is definitely not done, there are still a lot of APIs that need to be written for it. It's been slow because of a lack of manpower (mostly on my end).

It would be great to find more collaborators (especially for code reviews, but nobody likes doing code reviews).

> I take it that list of the "the most commonly used web APIs" would be the "Are we Gloo yet", that would allow seeing, where gloo is headed and how far it is from being done, right?

Right now we don't have a list like that, instead we add in APIs in an ad-hoc fashion based on interest. So if somebody wants an API added to gloo, they can just create an RFC for it.

**Comment by renatoathaydes** [comment]
@Pauan sorry for my tone, I was very frustrated yesterday by not being able to achieve what I needed to achieve.

I don't want to continue a fruitless argument, but I think that maybe it would be useful to show that IDEs do know the exact types for these functions. For example, `generateKey` 's signature as seen from IntelliJ (in JS):

<img width="789" alt="Screenshot 2020-05-08 at 09 22 45" src="https://user-images.githubusercontent.com/1901277/81381871-ba095e80-910d-11ea-8c41-5632f6ba24c7.png">

Do you know how they do this? Could web_sys do the same perhaps?

**Comment by Pauan** [comment]
> @renatoathaydes I was very frustrated yesterday by not being able to achieve what I needed to achieve.

Indeed, JS is hard enough as-is, and it's even harder when trying to combine it with Rust. We've all experienced that frustration.

> Do you know how they do this?

The TypeScript team maintains [TypeScript type definitions](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts) for some (but not all) of the web APIs.

> Could web_sys do the same perhaps?

No, because the TypeScript types do not cover all of the web APIs, they are community maintained (and thus may not always match what the browsers do), and it's not possible to translate TypeScript types into Rust types (because TypeScript types are too dynamic).

It is possible to translate a *subset* of TypeScript types to Rust types, but that's a quite large project. We don't have the manpower to create a TypeScript->Rust generator, but I think it would be very cool if somebody else did it.

Also, in TypeScript it doesn't matter if the types are a bit wrong, since you can just use `as any` to bypass the type checker. But with Rust the types have to be correct. Right now, the only way to get that is through the WebIDL. The WebIDL may not always have the most precise types, but they will always be the correct types.

> Now, the question is why does TypeScript know the proper types but the Web IDL does not?

Because the TypeScript types are created by hand. That's why they only have *some* of the web APIs and not all. Microsoft has a lot more manpower than us, so they can actually maintain handcrafted bindings. But even they don't maintain bindings for *all* the web APIs.
