### ISSUE TITLE
no web_sys::console in the root

### ISSUE THREAD

**Issue by renatoathaydes** [rustwasm/wasm-bindgen#2127]
Trying to follow the guide at https://rustwasm.github.io/docs/wasm-bindgen/examples/console-log.html

It shows the following code:

```rust
use web_sys::console;

console::log_1(&"Hello using web-sys".into());
```

When I attempt to compile it, it errors:

```
error[E0432]: unresolved import `web_sys::console`
  --> src/lib.rs:34:9
   |
34 |     use web_sys::console;
   |         ^^^^^^^^^^^^^^^^ no `console` in the root
```

I can use other features of web_sys... for example, all these imports are working:

```
use js_sys::{Array, Intl, Object, Reflect};
use wasm_bindgen::prelude::*;
use web_sys::{CryptoKey, CryptoKeyPair};
use wasm_bindgen_futures::JsFuture;
```

What can be the issue? Has `console` been moved elsewhere recently?

**Comment by renatoathaydes** [comment]
Oh nevermind... just figured out using `console` also requires the feature `console`. Unexpected.

**Comment by Pauan** [comment]
Because there are so many thousands of web APIs, compile times would be extremely long. So to make the compile times reasonable we use Cargo features so it only compiles the things that you actually use.

Although this approach is rare, it is used for other very large crates like [winapi](https://github.com/retep998/winapi-rs/blob/9155425b703c69d503feb72debd7cff0b08e84d2/Cargo.toml#L28-L432).

This is explained on [the main page for web-sys](https://crates.io/crates/web-sys) and also on each [individual function](https://rustwasm.github.io/wasm-bindgen/api/web_sys/console/fn.log_1.html):

> This API requires the following crate features to be activated: `console`

I agree that we should change the console-log example to make this more clear.

**Comment by bbugh** [comment]
If anyone else gets here and is like *"argh, why didn't you post the answer?!"* the answer is:

```toml
[dependencies]
web-sys = { version = "0.3.49", features = ["console"] } # <!-- add the feature
```

You also don't need to `use web_sys::console;` like [the example here](https://rustwasm.github.io/docs/wasm-bindgen/examples/console-log.html?highlight=console#srclibrs) shows, just `console::log_X`.
