### ISSUE TITLE
web_sys: Inconsistent typing on some WebGlRenderingContext methods

### ISSUE THREAD

**Issue by fdb-hiroshima** [rustwasm/wasm-bindgen#2130]
### Motivation
The WebGl API is a lot about passing simple integers that are actually references to some underlying data. In js, that translate to code like this :
```js
aVertexPosition = gl.getAttribLocation(shaderProgram, "aVertexPosition");
gl.enableVertexAttribArray(aVertexPosition);
gl.vertexAttribPointer(aVertexPosition, [...]);

// taken from https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/enableVertexAttribArray#Example
``` 
where aVertexPosition is a number. 
However, current web_sys bindings makes [`getAttribLocation`](https://docs.rs/web-sys/0.3.5/web_sys/struct.WebGlRenderingContext.html?search=#method.get_attrib_location) returns an i32, and [`enableVertexAttribArray`](https://docs.rs/web-sys/0.3.5/web_sys/struct.WebGlRenderingContext.html?search=#method.enable_vertex_attrib_array) take a u32.

### Proposed Solution

Change `WebGlRenderingContext::get_attrib_location` so it returns a u32.

### Alternatives

Simply using `as u32` makes things works, but it kinda feels odd that the API don't accept the type it returns by itself without additional conversion.

**Comment by Pauan** [comment]
The web-sys bindings are automatically generated from the official specs.

According to the specs [glGetAttribLocation](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGetAttribLocation.xml) returns a `GLint` (`i32`), because it returns -1 if the name is invalid.

And [glEnableVertexAttribArray](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glEnableVertexAttribArray.xml) accepts a `GLuint` (`u32`). So the types in web-sys are correct.

Note that using `as u32` with an `i32` [has no performance cost](https://doc.rust-lang.org/nomicon/casts.html), it's a no-op.
