### ISSUE TITLE
How to remove private info from wasm file?

### ISSUE THREAD

**Issue by NateLing** [rustwasm/wasm-bindgen#2243]
![image](https://user-images.githubusercontent.com/9606668/87776691-bd7e3c00-c85a-11ea-9a82-e5f21ca84a9d.png)

I dont want people to see `/Users/ling/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/string.rs` `/Users/ling` is my pc path info.

**Comment by alexcrichton** [comment]
Thanks for the report! This is a general issue for Rust binaries rather than just WebAssembly, so I'm going to close this. This comes up most likely for panic strings and perhaps debuginfo if you're not stripping that. The solution I believe is to pass `-C remap-path-prefix` to the compiler to map these paths to different locations.
