### ISSUE TITLE
Support creating bindings for WebIDL dictionaries

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#241]
https://heycam.github.io/webidl/#idl-dictionaries

Dictionaries are passed by-value, and are structural rather than nominal (aka "duck typed").

For passing them from Rust to an imported function, we can translate dictionaries from

```c
dictionary SomeDict {
    bool on;
    long which;
}
```

into the AST equivalent of

```rust
#[wasm_bindgen(js_name = __SomeDict)]
pub struct SomeDict {
    pub on: bool,
    pub i32: which,
}
```

**Comment by alexcrichton** [comment]
I was looking into this today while looking at the warnings generated by `web-sys`'s build script, and it looks like we're currently ignoring 388 definitions of dictionaries which probably means we're missing up to 388 APIs!

In that sense I think it'd be good to try to get this sorted for `web-sys`'s first release. All dictionaries are basically `Object` newtype wrappers, so we may want to simply generate custom bindings for them perhaps?

@fitzgen the desugaring you listed above is for defining a dictionary in Rust but I think instead what we might want to do is something like:

```rust
#[wasm_bindgen]
extern {
    #[derive(Clone, Debug)]
    pub type SomeDict;
    #[wasm_bindgen(method, getter, structural)]
    pub fn on(this: &SomeDict) -> bool;
    #[wasm_bindgen(method, setter, structural)]
    pub fn set_on(this: &SomeDict, val: bool);
    #[wasm_bindgen(method, getter, structural)]
    pub fn which(this: &SomeDict) -> i32;
    #[wasm_bindgen(method, setter, structural)]
    pub fn set_which(this: &SomeDict, val: i32);
}

impl SomeDict {
    pub fn new() -> SomeDict {
        SomeDict { obj: Object::new().into() }
    }
}
```

A downside of this approach though is that because `SomeDict` isn't actually a JS class the `is_instance_of` check will probably cause an exception for something like `obj.is_instance_of::<SomeDict>()`. We could perhaps just leave that behavior, though. These are low-level bindings after all!

**Comment by Pauan** [comment]
> A downside of this approach though is that because SomeDict isn't actually a JS class the is_instance_of check will probably cause an exception for something like obj.is_instance_of::<SomeDict>(). 

Can't it use a custom implementation of `is_instance_of`, similar to what `JsValue` does?

**Comment by alexcrichton** [comment]
It could yeah! That would involve having some sort of way to change the generated implementation, and since we use the backend directly we also don't necessarily have to stabilize a user-facing interface.

**Comment by fitzgen** [comment]
Can you make the case for why we would want `extern` types for dictionaries instead of exported Rust types (which would ideally not emit JS bindings, only appear on the Rust side)?

> All dictionaries are basically Object newtype wrappers, so we may want to simply generate custom bindings for them perhaps?

I agree, but what you have written up doesn't look like an `Object` newtype wrapper. What if we actually just emitted normal newtypes over `Object` that have constructors with parameters for each of the dictionary members?

```rust
// dictionary SomeDict {
//     bool on;
//     long which;
// }
pub struct SomeDict {
    obj: js_sys::Object,
}

impl From<SomeDict> for js_sys::Object {...}

impl SomeDict {
    pub fn new(on: bool, which: u32) -> SomeDict {
        let obj = js_sys::Object::new();
        js_sys::Reflect::set(&obj, &JsValue::from("on"), &JsValue::from(on));
        js_sys::Reflect::set(&obj, &JsValue::from("which"), &JsValue::from(which));
        SomeDict { obj }
    }
}
```

> A downside of this approach though is that because SomeDict isn't actually a JS class the is_instance_of check will probably cause an exception for something like obj.is_instance_of::<SomeDict>(). We could perhaps just leave that behavior, though. These are low-level bindings after all!

If we went down the `extern` type route, I think we would want to emit a `JsCast::instanceof` implementation that always returns `false`, since nothing can be an `instanceof` a class that doesn't exist.

I *don't* think we want to have `instanceof` check if the object quacks like a duck; it is just too surprising and very much does not map onto the `instanceof` JS operator.

**Comment by Pauan** [comment]
> What if we actually just emitted normal newtypes over Object that have constructors with parameters for each of the dictionary members?

I like this idea.

> If we went down the extern type route, I think we would want to emit a JsCast::instanceof implementation that always returns false, since nothing can be an instanceof a class that doesn't exist.

That seems inconsistent with `JsValue`, which always returns `true`.

It's a tricky situation, but I would personally expect it to return `true` if the object is an actual `Object` (no duck-typing for properties), and `false` otherwise.

**Comment by ohanar** [comment]
I prefer the original desugaring idea. I feels a bit more ergonomic to construct, especially in the case of required fields. Given that dictionaries are primarily for method arguments (if not exclusively), constructing them is the main interaction users will have with them, so that should be what is prioritized in their API.

Also, it matches up with [Mozilla's C++ reflections for WebIDL Dictionaries](https://developer.mozilla.org/en-US/docs/Mozilla/WebIDL_bindings#Dictionary_types), and we already follow what they do pretty closely for other WebIDL constructs.

**Comment by alexcrichton** [comment]
I really like @fitzgen's [idea](https://github.com/rustwasm/wasm-bindgen/issues/241#issuecomment-411129556) as well. I like the idea of not "importing" a type that doesn't actually exist and that way there's no need to deal with `instanceof` and such like that. That, and you can pull out an `Object` if you need to (as that's what it actually is).

Do we need to also generate the ability to access a dictionary's fields? While it's true that it may be mostly constructed, it may be the case that it's returned sometimes too perhaps?

**Comment by alexcrichton** [comment]
I've started working on this locally, hope to have a PR up by tomorrow

**Comment by ohanar** [comment]
What about using a builder pattern here? I think this is basically an extension of what was previously proposed, the main difference being that setters return a mutable reference to self (or something along those lines). It would make constructing dictionaries more convenient.

I think many/most fields in dictionaries are optional (all fields are optional, unless they specify otherwise), so making it easy to only specify a subset of fields should be a top priority. The new method would include only required fields, rather than all fields.

**Comment by alexcrichton** [comment]
Good idea @ohanar! After learning everything was optional-by-default that's what I started implementing as well :)

The constructor currently is generated as only requiring the required arguments, and all optional arguments can be specified through builder methods.
