### ISSUE TITLE
How do I fetch a `blob` with web-sys?

### ISSUE THREAD

**Issue by felipellrocha** [rustwasm/wasm-bindgen#2424]
This might be a dumb question, but I'd like to fetch binary data using web-sys and fetch. How do I do that? I've spent a few hours trying to figure this out without success, any help would be appreciated!

**Comment by alexcrichton** [comment]
Thanks for the report! Questions like this are likely best left for other channels, though, since this issue tracker is intended to deal with technical questions about wasm-bindgen itself. For this, though, you'll need to find the right web API that does what you want and then you'll want to call the appropriate match in `web-sys` if it exists. If web-sys is missing an API though feel free to open an issue here!
