### ISSUE TITLE
Wrong docs section for typescript_type

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wasm-bindgen#2426]
[`typescript_type`](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/typescript_type.html) is currently documented under the [On Rust Exports](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/index.html) section, but all the examples show how to apply it on JS imports, and, upon manual testing, it looks like there is no way to actually use this attribute on exports instead.

The page should probably be moved to the [On JavaScript Imports](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/index.html) category.

**Comment by 9SMTM6** [comment]
The page itself is ripe for improvements, but as far as I understand it is better placed in Rust Export than in JS imports.

In JS Imports you declare things the Ecosystem delivers for use in Rust. I.e. most of the stuff in web_sys would be, if you were to do it manually, be done using techniques in the JS Imports section.

The Rust Exports section is where you declare how JS can access Rust code.

And typescript_type is meant to be used in the parameters and as return of Rust Functions. Heres an example (also using serde parsing to allow for manipulation in rust and more importantly to demonstrate the conversion from Rust data to JS data with the correct typescript type):

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen(typescript_custom_section)]
const ITEXT_STYLE: &'static str = r#"
type StringList = string[]
"#;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(typescript_type = "StringList")]
    pub type StringList;
}

#[wasm_bindgen]
pub fn add_to_str_list(list: StringList, to_add: String) -> StringList {
    let mut list: Vec<String> = list.into_serde().unwrap();
    list.push(to_add);
    StringList::from(JsValue::from_serde(&list).unwrap())
}
```

with 

```toml
#cargo.toml
[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
```

generates:

```ts
export function add_to_str_list(list: StringList, to_add: string): StringList;

type StringList = string[]
```

**Comment by RReverser** [comment]
> The Rust Exports section is where you declare how JS can access Rust code.

Not really, as the name of the actual page says, it's the documentation of the attribute itself:

![image](https://user-images.githubusercontent.com/557590/105372741-d4cd2600-5bfd-11eb-8974-646c855339f7.png)

As in, what you can put in `#[wasm_bindgen]` applies on JS imports - and `typescript_type` belongs there.

**Comment by 9SMTM6** [comment]
Well, while it does not literally get applied to exports it indirectly does, as you use it on the arguments and returns of Rust functions, as I demonstrated.

Issues if moved to JS Imports:
* The attributes in the JS Imports section so far refer to singleton instances that get exported from js code, this does not apply to `typescript_type`.
* `typescript_type` is meant to be used in conjunction with the type it refers to, you can use the type itself when declaring i.e. an object that you can then pass to the rust function. That is not at all the case with other attributes in the JS Import section. In one case you have a dependency of Rust code on the JS ecosystem, in the other the JS/TS code actually is the one that's depending on the Rust code.

If the page does have to be placed into `#[wasm_bindgen] Attributes` at all I'd still say it belongs to Rust-Exports.

But there's an alternative that may be acceptable to both of us. A totally separate section that's not concerned with splitting stuff into these, here indeed questionable, categorizations, but is about use of `wasm-bindgen` with typescript in general.

**Comment by RReverser** [comment]
> so far refer to singleton instances that get exported from js code

No they don't? JS doesn't export anything, these are imports from global JS scope (or anywhre else).

**Comment by 9SMTM6** [comment]
Oh come on. Really? Yeah, obviously its importing from global scope in most instances. And yeah maybe things in the global scope are not literally exported, but with just a tiny bit of thinking about it you could've gotten what I mean instead of going for what for me feels like a really cheap gotcha. Also, btw, while were at the cheap gotcha level, it may indeed refer to an export from i.e. an [JS Snippet](https://rustwasm.github.io/docs/wasm-bindgen/reference/js-snippets.html).

Yes, my suggestion would be a separate issue, and it would require re-categorization of a few pages (not "everything").

My point is that I don't believe placing this page in either category is entirely fitting, thus your supposed solution is not really an improvement. As such it is perfectly fitting to propose an alternative, even if that would have to be made into a separate issue, but say that you'd agree with that and it gets done. In that case we could close this issue as it no longer applies.

**Comment by bancek** [comment]
@9SMTM6 this `pub type` solution is really nice.

Now it is possible to have full Typescript integration using [tsify](https://github.com/madonoharu/tsify). I've created an [example repo](https://github.com/bancek/serde-wasm-bindgen-typescript-example) that demonstrates `serde-wasm-bindgen` and `tsify` integration.

[Now that `serde-wasm-bindgen` is an official recommendation](https://github.com/rustwasm/wasm-bindgen/pull/3031), maybe `tsify` should be mentioned somewhere in the docs because it bridges the Typescript types gap.

Rust code:

```rs
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Tsify)]
pub enum UserState {
    Active,
    Inactive,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Tsify)]
pub struct User {
    pub id: String,
    pub name: String,
    pub state: UserState,
}

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(typescript_type = "User[]")]
    pub type Users;
}

#[wasm_bindgen(js_name = "getUsers")]
pub fn get_users() -> Users {
    let users: Vec<User> = [
        User {
            id: String::from("586f89c3-f7d8-4371-9d2d-4c90ba9eacb9"),
            name: String::from("User 1"),
            state: UserState::Active,
        },
        User {
            id: String::from("fae6ae60-ee3a-4e02-a4e4-64b333fa2919"),
            name: String::from("User 2"),
            state: UserState::Inactive,
        },
    ]
    .to_vec();

    Users::from(serde_wasm_bindgen::to_value(&users).unwrap())
}
```

Generated Tyescript:

```ts
export type UserState = "Active" | "Inactive";

export interface User {
  id: string;
  name: string;
  state: UserState;
}

export function getUsers(): User[];
```
