### ISSUE TITLE
Borrowing a RefCell leads to a RuntimeError

### ISSUE THREAD

**Issue by mplsgrant** [rustwasm/wasm-bindgen#2467]
### Describe the Bug

Borrowing a RefCell in certain circumstances produces an error which breaks the program: Uncaught RuntimeError: unreachable executed.

I found the RuntimeError in Firefox's developer console. 

### Steps to Reproduce

I created a repo which can reproduce the error quickly: https://github.com/mplsgrant/bindg-error.git

I have also included relevant code:

````
#[wasm_bindgen]
pub fn run() -> Result<(), JsValue> {
    let f = Rc::new(RefCell::new(None));
    let g = f.clone();

    let timestamp = RefCell::new(0.0);
    let i = 0;
    *g.borrow_mut() = Some(Closure::wrap(Box::new(move |current_time| {

        if i > 300 {
            body().set_text_content(Some("All done!"));

            // Drop our handle to this closure so that it will get cleaned
            // up once we return.
            let _ = f.borrow_mut().take();
            return;
        }
        
        // uncomment the following to break wasm-bindgen
        let _this_breaks_wasm = timestamp.borrow();
        let replaced = timestamp.replace(current_time);

        let text = format!("requestAnimationFrame has been called {} times.", replaced);
        body().set_text_content(Some(&text));

        // Schedule ourself for another requestAnimationFrame callback.
        request_animation_frame(f.borrow().as_ref().unwrap());
    }) as Box<dyn FnMut(f64)>));

    request_animation_frame(g.borrow().as_ref().unwrap());

    Ok(())
}
````

### Expected Behavior

I expect the rust compiler or the wasm-bindgen ecosystem to catch unreachable code.

### Actual Behavior

I get the error: Uncaught RuntimeError: unreachable executed.

**Comment by chinedufn** [comment]
Replace [panics if the RefCell's inner value is currently borrowed](https://doc.rust-lang.org/std/cell/struct.RefCell.html#method.replace).

So, this panicking is expected behavior.

Make sure that you aren't running `wasm-opt` on your final binary and that you have debug symbols compiled into your binary.

Until https://github.com/rustwasm/wasm-pack/pull/872 lands you'll need to turn wasm-opt off in your Cargo.toml https://rustwasm.github.io/wasm-pack/book/cargo-toml-configuration.html

`CARGO_PROFILE_RELEASE_DEBUG=true wasm-pack build ...`

**Comment by mplsgrant** [comment]
Thank you chinedufn. I believe you solved my problem. The error hook you provided gives me a much better view as to what I needed to fix.

**Comment by mplsgrant** [comment]
chinedufn provided a workable solution to my issue.
