### ISSUE TITLE
Support emitting `&self` methods to access WebIDL regular attributes

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#250]
https://heycam.github.io/webidl/#idl-attributes

Given

```webidl
interface Foo {
  attribute long bar;
};
```

we should emit a `fn get_bar(&self) -> i32` method to get `Foo`'s `bar` attribute.

**Comment by ohanar** [comment]
This is implemented here: ohanar@2fbd4d9e3489e2b25b983ebf95c5f167737e98ec (based off of my pull request for snake case methods). The signature is `fn bar(&self) -> i32`, which follows the conventions in the examples more closely (this can be easily changed).

It currently fails the test suite since it now depends upon the `DOMHighResTimeStamp` type (it would also depend on `EventTarget` if nullable types were supported).

**Comment by fitzgen** [comment]
@ohanar, would you like to add support for `DOMHighResTimeStamp` to unblock your work on this issue?

**Comment by ohanar** [comment]
I'll look into it. It is a typedef in Performance.webidl, so it basically amounts to adding support for typedefs.
