### ISSUE TITLE
How to allow testing in both browser and Node.js?

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wasm-bindgen#2571]
### Summary

I have code that is only using standard JS APIs, and I want to ensure it works in both browser and Node.js environments.

If I use

```rust
wasm_bindgen_test_configure!(run_in_browser);
```

then running e.g. `wasm-pack test --headless --chrome` succeeds, but `wasm-pack test --node` fails with:

```
this test suite is only configured to run in a browser, but we're only testing node.js tests so skipping
```

If I comment out that `wasm_bindgen_test_configure!(...)` call, then instead `wasm-pack test --node` succeeds, but browser test command fails with:

```
This test suite is only configured to run in node.js, but we're only running
browser tests so skipping. If you'd like to run the tests in a browser
include this in your crate when testing:

    wasm_bindgen_test::wasm_bindgen_test_configure!(run_in_browser);

You'll likely want to put that in a `#[cfg(test)]` module or at the top of an
integration test.
```

Is there a way to allow either environment?

### Additional Details

Looks like this behavior & flags were introduced in https://github.com/rustwasm/wasm-bindgen/pull/1465 + https://github.com/rustwasm/wasm-pack/pull/630, but I don't see a way to allow either environment.

**Comment by simlay** [comment]
I think maybe you can do this with feature flags which was recently added to `wasm-pack test` in rustwasm/wasm-pack/pull/851.

**Comment by Saruniks** [comment]
Adding to simlay comment:

Maybe as a somewhat of a workaround (from wasm-pack v0.10.0) could be done:

```
#[cfg(feature = "in_browser")]
wasm_bindgen_test_configure!(run_in_browser);
```

In Cargo.toml:
```
[features]
in_browser = []
```

And then
```
wasm-pack test --node
wasm-pack test --firefox --headless -- --features "in_browser"
```

**Comment by RReverser** [comment]
Sure, something like that is possible, but I don't want to add feature and recompile tests just to switch testing. wasm-pack already has switch for Node.js vs browser (`--node` vs others), why can't it use that info to run same test Wasm in different environments if it's environment-agnostic?

**Comment by chinedufn** [comment]
There's no way to allow both environments to run right now as far as I know, but I don't think that there's a reason that this can't be done.

Right now the test runner looks at a custom section in the wasm binary to decide whether to run it using Node or the browser

https://github.com/rustwasm/wasm-bindgen/blob/44d577f6b89dc7cc572ea0747833d38ba680e93b/crates/cli/src/bin/wasm-bindgen-test-runner/main.rs#L93

I think you could change things so that there is one customer section per target environment (node, browser, etc) then have the test runner look for each.

Then run all of the environments that are in the custom sections.

I haven't spent any time thinking about how to make that all feel ergonomic and whatnot in terms of how errors are reported and whether or not tests run in parallel, etc..

But at a high level multiple target environments should be possible as far as I can tell.

**Comment by daxpedda** [comment]
I believe this should be covered by #4295. Let me know if there is something I missed!
