### ISSUE TITLE
cli panics with out of bounds error

### ISSUE THREAD

**Issue by kuviman** [rustwasm/wasm-bindgen#2679]
### Describe the Bug

Trying to just compile my project to the web, I stumbled upon this panic message.
I think this may happen because of version mismatch between the cli app and the dependency.
After running `cargo update` everything works fine.

### Steps to Reproduce

I can not really show the code. I may try to provide a simplified example if needed

OS: Windows
Rust version: rustc 1.55.0 (c8dfcfe04 2021-09-06)
`wasm-bindgen-cli` version: 0.2.77
`wasm-bindgen` dependency version: 0.2.76

Running command: `wasm-bindgen --target=web --no-typescript --out-dir tmp target/wasm32-unknown-unknown/release/theproject.wasm`

### Expected Behavior

`wasm-bindgen` does its magic without any errors

### Actual Behavior

`wasm-bindgen` panics with following message:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\myusername\.cargo\registry\src\github.com-1ecc6299db9ec823\wasm-bindgen-cli-support-0.2.77\src\descriptor.rs:205:15
```

### Additional Context

As I said, looks like problems with different versions. I remember `wasm-bindgen` would just panic instantly with message saying that versions should match. I guess it is not the case anymore? So this took me a while to even think about running `cargo update`

**Comment by alexcrichton** [comment]
Yes recently the version-match was removed because it was hoped to get caught by other things and/or not change much. I believe that's the cause of this.

**Comment by chinedufn** [comment]
Uh oh!

Yeah I worked on this in #2546 with the hope of removing this requirement.

It looks like something is going wrong.. Alex if you already know the issue definitely let me know and I can get it fixed it. 

Otherwise I can take a look into this later tonight and figure out what's going wrong!

IIRC this should have actually worked in theory.. so it's probably a minor oversight or something.. hopefully..!

**Comment by alexcrichton** [comment]
Oh I'm not sure what actually caused this, I'd assume that something about the schema probably changed and the version number of the schema was forgotten to get bumped, but I would have to track things down to be sure.

**Comment by chinedufn** [comment]
Ahh got it.

Yeah, just checked and this test is failing:

https://github.com/rustwasm/wasm-bindgen/blob/723674820fa78115cdafabadfb7a4b52fbd4285d/crates/shared/src/schema_hash_approval.rs#L13-L16

Seems like we just need to start running it in CI.

**Comment by chinedufn** [comment]
I'm on it one sec.

**Comment by chinedufn** [comment]
@kuviman (and anyone else that comes here) sorry about this.

In short.. we currently need to manually change the schema version whenever one of wasm-bindgen's internal data structures changes.

This is used to ensure that you get a nice error when trying to use two versions of wasm-bindgen with different schemas.

There's a test that fails when we forget to change this schema version.

But this test wasn't running in CI so no one noticed / remembered to change the schema version.

#2680 runs this test in CI so we shouldn't forget again!

In the future.. we could automatic this entirely using a proc macro that hashes the tokens and generated the schema version variable or something.. but since the schema doesn't change often we probably won't need to go that route.

Sorry!
