### ISSUE TITLE
When using #[wasm_bindgen(readonly)], The type output to .d.ts file is void

### ISSUE THREAD

**Issue by madonoharu** [rustwasm/wasm-bindgen#2721]
Hello.
Thank you for this great library!

### Describe the Bug

When `#[wasm_bindgen(readonly)]` is specified, the return value in d.ts file is `void`.

```rust
#[wasm_bindgen]
pub struct Foo {
    pub first: u32,

    #[wasm_bindgen(readonly)]
    pub second: u32,
}
```

output
```ts
export class Foo {
  free(): void;
/**
*/
  first: number;
/**
*/
  readonly second: void;
}
```

### Expected Behavior

```ts
export class Foo {
  free(): void;
/**
*/
  first: number;
/**
*/
  readonly second: number;
}
```

### Steps to Reproduce

https://github.com/MadonoHaru/wasm-bindgen-type-issue

**Comment by anicholson** [comment]
This occurs for me too:

Versions:

Rust: 1.58.0
wasm-bindgen: "0.2.63"

Current workaround is to do the following:

1. add `#[wasm_bindgen(skip)]` before the field, and
2. implement each getter manually via `#[wasm_bindgen(getter)]`

**Comment by Hywan** [comment]
The problem doesn't seem to be related to `readonly` but, when generating code for struct attributes, (i) a getter is generated, and (ii) a setter. In the case of `readonly`, only a getter is generated.

The bug seems to be in the getter parameter. The `ret_ty` is set to `Some("void")` everytime:

https://github.com/rustwasm/wasm-bindgen/blob/63872ee3514fa656f167e2d0a716501ecc299218/crates/cli-support/src/js/mod.rs#L2545-L2563

With your example, we have:

```
in AuxExportKind::Getter branch:
    field = "first"
    ret_ty = Some("void")

in AuxExportKind::Setter branch:
    field = "first"
    ret_ty = Some("number")

in AuxExportKind::Getter branch:
    field = "second"
    ret_ty = Some("void")
```

Unfortunately, all this code ends up in `push_accessor_ts`:

https://github.com/rustwasm/wasm-bindgen/blob/63872ee3514fa656f167e2d0a716501ecc299218/crates/cli-support/src/js/mod.rs#L3815-L3834

which overrides the `ty` variable (first item of a tuple stored in `typescript_fields`). So when we have a getter + a setter, the setter has the correct `ret_ty` and “fixes” the previous bug with the getter. That's why it appears only with `readonly`.

If we look at the `Adapter`'s content, we have `params`, `results` and `inner_results`. The first two are correctly set, but `inner_results` seems to always be empty:

https://github.com/rustwasm/wasm-bindgen/blob/63872ee3514fa656f167e2d0a716501ecc299218/crates/cli-support/src/wit/standard.rs#L24-L31

@alexcrichton What's the difference between `Adapter.results` and `Adapter.inner_results`?
