### ISSUE TITLE
Using `spawn_local` inside a task itself spawn with `spawn_local` will not run on the next microtick

### ISSUE THREAD

**Issue by WorldSEnder** [rustwasm/wasm-bindgen#2847]
### Describe the Bug

When spawning a task with [`wasm_bindgen_futures::spawn_local`](https://docs.rs/wasm-bindgen-futures/latest/wasm_bindgen_futures/fn.spawn_local.html), that itself spawns another task, the second task is run in the same tick as the first one. The documentation would lead me to believe that the second execution should be delayed until the next microtick.

### Steps to Reproduce

```rust
fn schedule_self(steps: u32) {
  if steps == 0 { return; }
  spawn_local(async move {
    schedule_self(steps - 1);
  });
}
schedule_self(1000);
```

### Expected Behavior

The code above should not block the browser event loop from running, i.e. it should always wait until the next microtick to run the next call to `schedule_self`. Overall, 1000 microticks happen.

From the documentation:
> Runs a Rust Future on the current thread.
> The future must be 'static because it will be scheduled to run in the background and cannot contain any stack references.
> **The future will always be run on the next microtask tick even if it immediately returns Poll::Ready**.

### Actual Behavior

A loop is entered and the runtime never yields to the browser. Only additional 1 microtick happens.

### Additional Context

As much as I can gather from the existing code, the task is added to the `QUEUE` of tasks, which is run until empty, which includes tasks only just scheduled in the current microtick. Maybe a double buffer approach where newly added tasks are added to a back-queue and only the front-queue is drained in each microtick is sufficient.

**Comment by alexcrichton** [comment]
It looks like there's a number of ways this could be tackled:

* As you mentioned change the order of queueing
* Periodically yield back the microtask tick if we ran too much work
* Seeing that a unit of work is associated with a different unit of Rust work and deferring it to another tick.

Anything seems fine by me, personally.

**Comment by Pauan** [comment]
[We discussed this issue before.](https://github.com/rust-lang/futures-rs/issues/738) This is not a bug, it *should* run newly scheduled tasks on the current tick, it should not delay them to the next tick.

Other Rust executors run newly scheduled tasks on the current tick, and JavaScript Promises also run newly scheduled Promises on the current tick. That is how the microtick loop is supposed to work:

```js
async function foo() {}

// This never yields to the browser
async function loop() {
    for (;;) {
        await foo();
    }
}
```

Spawning new microticks blocks the browser, [this is expected behavior](https://stackoverflow.com/questions/25915634/difference-between-microtask-and-macrotask-within-an-event-loop-context). If you want to yield then you must use a macrotask like `setTimeout`.

**Comment by WorldSEnder** [comment]
> This is not a bug, it _should_ run newly scheduled tasks on the current tick, it should not delay them to the next tick.

Well, this bug report was about inconsistent documentation, which still to this date states unambiguously:

> The future will always be run on the next microtask tick even if it immediately returns Poll::Ready.

If this was not the intended behaviour, then feel free to add a method that immediately starts polling the future, but this surely would be a breaking change. The bug is about it the inconsistency of calling `spawn_local` with a scheduler already running and without. If you want to immediately poll the future, surely you can also immediately start the scheduler in the local call.

>  JavaScript Promises also run newly scheduled Promises on the current tick.

Well, depends on what you mean by this. `new Function(executor)` calls `executor` immediately, that is true (not that there is any scheduling going on). But `Promise.resolve(value).then(continuation)` runs the `continuation` on the next microtick - actually this is caused by `Promise.prototype.then` always running stuff asynchronously. I suppose this behaviour was my initial impression of what the scheduler was trying to emulate.

In the PR resolving this, I initially started with a double-buffer queue, which scheduled `waker.wake()` calls to run on the same tick, but this was changed to simplify the implementation. I would have no problem with this change, and I do agree that for performance, this would be better. But the initial schedule *is still currently guaranteed as per docs* to run only on the next microtick.

**Comment by Pauan** [comment]
> Well, this bug report was about inconsistent documentation

Then the documentation should be fixed, not the behavior.

> If this was not the intended behaviour, then feel free to add a method that immediately starts polling the future, but this surely would be a breaking change.

Your code changes the existing behavior and is a breaking change. It causes *all* wakeups to happen on the next tick, even for already-running Futures.

Perhaps you thought you were only changing `spawn_local`, but in actuality you were changing the behavior of *all* Futures.

> But Promise.resolve(value).then(continuation) runs the continuation on the next microtick - actually this is caused by Promise.prototype.then always running stuff asynchronously. I suppose this behaviour was my initial impression of what the scheduler was trying to emulate.

No it does not, it runs it on the current microtick. The microtask queue will continuously run until it is empty, just like the old behavior of wasm-bindgen-futures. [This is mandated by the spec.](https://html.spec.whatwg.org/multipage/webappapis.html#perform-a-microtask-checkpoint)

That means any new microtasks (like Promises, or `queueMicrotask`) will run in the *current* microtick. They are not delayed to the next microtick.

> while starving the browser, it allows other microticks, including just-now-resolved promises, to run, which allows progress that the rust scheduler can not make.

After the Rust microtask queue is flushed, it will then give other JS microtasks a chance to run. Perhaps there are some obscure cases where it might starve other microtasks (such as an infinite loop, or some sort of crazy dependency deadlock). But in those situations Promises would likely also deadlock too.

It is an unavoidable fact that microtasks are intentionally designed so that they can starve both the browser and other microtasks. You can create deadlocks. You can create infinite loops. If you don't want that, then you must use a macrotask like `setTimeout`. Unlike microtasks, macrotasks are designed to not starve.

**Comment by Pauan** [comment]
By the way, [`gloo-timers`](https://crates.io/crates/gloo-timers) has a Future-based wrapper around `setTimeout`, so it's very easy to yield to the macrotask queue:

```rust
async fn yield_macro() {
    gloo_timers::future::TimeoutFuture::new(0).await;
}
```

Now you can just call `yield_macro().await;` and it will yield.

Similarly you could create a `yield_micro().await;` that will yield to the next JS microtask (still in the same microtick).

**Comment by WorldSEnder** [comment]
Before I write a wall of text, does "microtick" actually have a meaning I am not aware of? I used it in the context of and as a conflation of "next microtask tick" but even that seems to be not properly defined and, just working off the previously documented behaviour, does *not* mean "microtask checkpoint", so the linked spec just seems irrelevant.

**Comment by Pauan** [comment]
A microtick is a microtask checkpoint. It's a single atomic point in time where all of the current microtasks (and also any new microtasks created by the current microtasks) are run in a synchronous loop.

During the microtick (i.e. while the microtasks are being flushed), nothing else can run, the only thing that can run are new microtasks.

After all of the current and future microtasks are run (i.e. the microtask queue is completely empty), the microtick is now over, and the browser then runs other things like macrotasks (setTimeout, events, rendering, etc.)

So from the browser's perspective, running all of the microtasks counts as a single microtick event. The browser does NOT do `macrotask -> microtask -> macrotask -> microtask`, instead it always does `macrotask -> all microtasks -> macrotask`.

There is no interleaving, all microtasks are a part of a single microtick synchronous loop, and microtasks are not delayed to the next tick, they are always handled as part of the current microtick (microtask checkpoint).

The old implementation of wasm-bindgen-futures perfectly matches how the browser handles microtasks: keep running all pending Futures until the queue is empty. That's also how the microtick works in browsers.

----

A common misconception is that microtasks are asynchronous. They are not. According to the spec, microtasks are synchronously run at specific points.

The spec guarantees that microtasks are always run immediately [every time an event fires](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model). That means that this is guaranteed to synchronously run the Promise:

```js
addEventListener("click", () => {
    Promise.resolve().then(() => {
        console.log("Click!");
    });
});
```

So the `console.log("Click!")` code will run immediately after the event, before anything else can run (including rendering).

Microtasks are also always run [immediately after JS scripts are finished running](https://html.spec.whatwg.org/multipage/webappapis.html#clean-up-after-running-script). Just like with events, this also happens synchronously:

```js
Promise.resolve().then(() => {
    console.log("Hello!");
});
```

That means that it is guaranteed that the `console.log("Hello!")` will happen before anything else, including rendering.

And microtasks are also always run [when the JS stack is empty](https://html.spec.whatwg.org/multipage/webappapis.html#spin-the-event-loop). This also happens synchronously.

So that means that microtasks are always run synchronously, at very specific well-defined points, you can rely on their specific timing, they are not asynchronous. The only things that are truly asynchronous are macrotasks (which are handled *completely* differently from microtasks).

**Comment by Pauan** [comment]
Incidentally, NodeJS also has an event loop, just like the browsers, and it also has a distinction between "macrotask" and "microtask" (though it doesn't use those names).

For example, [the `process.nextTick()` function](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#process-nexttick) behaves the same as a microtask, it will keep running until the queue is empty, so it can stall and deadlock and go into infinite loops. If you are inside of a microtick and you call `process.nextTick()`, it will run in the current microtick, it won't be delayed. This is the same as how Promises work.

On the other hand, [`setImmediate`](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#process-nexttick-vs-setimmediate) runs on the next macrotick. It behaves like what you are expecting: if you call `setImmediate`, it will always be delayed until the next tick. This is similar to how `setTimeout` behaves.

**Comment by Pauan** [comment]
Also, just to confirm even more that microtasks are synchronous, this code will cause an infinite loop that completely stalls the browser:

```js
setTimeout(() => {
    console.log("This code will never run!");
}, 0);

function loop() {
    Promise.resolve().then(() => {
        console.log("Hello!");
        loop();
    });
}

loop();
```

This is guaranteed behavior according to the spec, because the spec guarantees that all microtasks (including new microtasks) are synchronously run until the microtask queue is empty.

So that means the `Promise.resolve()` and `.then` are guaranteed to run synchronously, and thus cause an infinite loop that completely stalls the browser. Which means that rendering cannot happen. Events cannot happen. `setTimeout` cannot happen. Nothing can happen except the infinite loop.

**Comment by WorldSEnder** [comment]
> "microtick" is a shorthand for "microtask checkpoint".

Thanks for clarifying. I'm [not the only one](https://stackoverflow.com/questions/59192133/) using it incorrectly and unless there is an official definition somewhere, I'd just avoid the term altogether. I thought one micro*tick* was the running of one micro*task* and one macrotick consists of multiple microticks. Anyway, that point is moot, I'll stick to not using tick from here on out, except when quoting the current docs.

How I interpreted the docs thus was that `spawn_local` always should run the future in a new microtask, that is possibly already enqueued, but guaranteed to be delayed until after the current microtask. This was not the case, and the target of the PR. A side-effect (from a review I got on that PR) was that waking now also runs inside such a future microtask - but, in your terminology, still inside the same "microtick" as far as I can tell. I do not care about the second part.

What I do care about, actually, is that all microtasks that have been enqueued before the call to `spawn_local(task)`, native ones included, happen before `task` is run. That's how I interpreted the docs in the first place, sorry if that was wrong, I think I was clear enough about this intention in the PR, someone could have corrected me then.

And I guess thanks for repeating the event loop of javascript, but for me it was really only the term "microtick" that was ill-defined and I don't think I've found a satisfactory, authorative definition of it, google seems to be resistant to finding the term in specs.

**Comment by Pauan** [comment]
> I thought one microtick was the running of one microtask and one macrotick consists of multiple microticks. 

That's not the case, a macrotask is completely different from microtasks, they're handled with a different mechanism, and they have different behavior. Macrotasks are completely separate from microtasks, they are not executed at the same time.

The biggest user difference is that macrotasks will *always* be delayed to the next macrotick (e.g. `setTimeout`), but microtasks always run in the current microtick. So the behavior you want is how macrotasks behave.

> I'm [not the only one](https://stackoverflow.com/questions/59192133/) using it incorrectly and unless there is an official definition somewhere, I'd just avoid the term altogether.

Yes, most people do not understand the event loop, it is arcane black magic. And the terminology is confusing. Which is why the Rust documentation does not try and go into the nitty-gritty details.

> How I interpreted the docs thus was that spawn_local always should run the future in a new microtask, that is possibly already enqueued, but guaranteed to be delayed until after the current microtask.

That is correct, and that is how it has always behaved:

```rust
spawn_local(async move {
    spawn_local(async move {
        log::info!("Future done");
    });

    log::info!("After spawn");
});
```

That will log `After spawn` and then `Future done`. That has always been the behavior of `spawn_local`.

Your confusion is that you thought new microtasks are run on the next tick, but they are run on the current tick.

> What I do care about, actually, is that all microtasks that have been enqueued before the call to spawn_local(task), native ones included, happen before task is run.

wasm-bindgen-futures has always worked like that, because it runs the task queue inside of a Promise:

https://github.com/rustwasm/wasm-bindgen/blob/564ce74168904e95a7905a828488ec3029bcaad4/crates/futures/src/queue.rs#L51-L56

This means that all pending microtasks (including JS microtasks / JS Promises) will run before `spawn_local`.

As for the behavior of Futures, that's not guaranteed by the Future contract. Pending Futures can be run in arbitrary order, and even at arbitrary times. In general you cannot rely upon the ordering or timing, you must use `.await` to synchronize between Futures.

It just so happens that the wasm-bindgen-futures crate does run them in order, and synchronously, because it's simple, fast, and matches how Promises behave.

> You seem to have more background on how executors should behave, but purely from a user perspective, it'd be confusing to have some calls to spawn_local run on another microtask, but some calls run in the same one.

That's how Rust executors work in general, including FuturesUnordered. Rust Futures follow the microtask model, similar to JS Promises. This is done partly for consistency, but also for simplicity and performance.

I think you are getting too hung up on the internal details of microtasks. That is all implementation details which can change or vary between implementations. What matters is this:

```rust
spawn_local(async move {
    log::info!("Future running!");
});

log::info!("After spawn");
```

It is guaranteed that it will log `After spawn` before `Future running!`. This is consistent. Whether it is actually spawning it asynchronously or synchronously is not defined by the Future contract. Some executors will spawn it synchronously, others will spawn it asynchronously. So you should not worry about it, and you certainly should not be relying upon it.

> Waking and running the task multiple times during the same microtask, in a loop, should be allowed and could be a worth-while improvement.

It is allowed by the Futures contract, because executors can run Futures whenever they wish (and in whatever order they wish).

However, for wasm-bindgen-futures, we try hard to be consistent with JS Promises, so we want to implement the same microtick behavior as JS.

> seems to be a non-issue given that your usage of delaying until the next "tick" is not actually what was implemented in the PR, it only schedules a new microtask to run in and it all runs in the same microtask checkpoint, even now.

Yes, but that still changes the behavior and hurts performance. Enqueing a new microtask is expensive, which is the reason why we have a `VecDeque` in the first place, so we only need to enque a new microtask one time. Your code enqueues multiple microtasks. Some Wasm apps rely upon very fast Future performance, because they spawn hundreds of thousands of Futures.

**Comment by WorldSEnder** [comment]
> wasm-bindgen-futures has always worked like that

No it did not used to work like that. If inside a task spawned with `spawn_local`, another call to `spawn_local` used to *not* enqueue a new microtask, and the spawned task used to run inside the currently active one by just being appended to the current task queue immediately. **Which is exactly why I opened this issue initially and what the PR fixes**. And yes, *that* detail is something one can observe and should be able to rely upon. You don't seem to acknowledge this.

> Yes, but that still changes the behavior and hurts performance

I know, change it then. That's what I initially had in the PR until the review, which is another point you don't seem to acknowledge from my responses.

---

I'm not going to engage further here, I think it's clear enough what the intended behavior is and how to fix it.

**Comment by Pauan** [comment]
> If inside a task spawned with spawn_local, another call to spawn_local used to not enqueue a new microtask, and the spawned task used to run inside the currently active one by just being appended to the current task queue immediately. Which is exactly why I opened this issue initially and what the PR fixes.

Enqueing a new microtask and running within the same microtask are behaviorally identical, because all microtasks are run synchronously in the microtick loop, as I explained in my earlier posts.

Whatever bad behavior you had before is not fixed by enqueing a new microtask, you will still have exactly the same synchronous behavior.

If I convert your code to JS Promises, it will behave exactly the same as the old wasm-bindgen-futures implementation:

```js
function scheduleSelf(steps) {
  if (steps === 0) { return; }

  Promise.resolve().then(() => {
    scheduleSelf(steps - 1);
  });
}

scheduleSelf(1000);
```

This will synchronously run all of the Promises immediately, it does not delay any of them to the next tick.

Your report is about "blocking the browser event loop", but blocking the event loop is *supposed* to happen, and *does* happen with JS Promises.

> And yes, that detail is something one can observe and should be able to rely upon. You don't seem to acknowledge this.

I'm not sure what you're talking about, as I said in my earlier posts, the synchronous behavior of microtasks is guaranteed by the spec, so of course you can rely upon it.

And the old behavior of wasm-bindgen-futures matched the behavior of microtasks.

> That's what I initially had in the PR until the review, which is another point you don't seem to acknowledge from my responses.

Once again, I'm not sure what you're talking about, I only noticed your changes 2 days ago, which is why I posted in this thread.

**Comment by WorldSEnder** [comment]
> Your report is about "blocking the browser event loop",

That part I can clarify. More to the core, the issue about not starving other microtasks that don't explicitly offer a future that one can await for their completion.

The "behaves exactly as the old wasm-bindgen-futures implementation" in javascript does *not* behave exactly the same, because the old behaviour of wasm-bindgen-futures *did* starve other microtasks if one repeatedly used `spawn_local` to continue running. The javascript based one does not and let's other microtasks have a turn.

**Comment by Pauan** [comment]
> More to the core, the issue about not starving other microtasks that don't explicitly offer a future that one can await for their completion.

That sounds like a *very* fragile situation, it's similar to a race condition. You are relying upon the browser running microtasks in a specific order.

I don't think we can or should guarantee that behavior in wasm-bindgen-futures.

If you want to avoid starvation, you can use the `yield_macro()` function that I showed earlier. That is guaranteed by the browser spec to not starve. Microtasks are never guaranteed to not starve.

Or if you explain more about your situation, maybe there is a better solution.

> the old behaviour of wasm-bindgen-futures did starve other microtasks if one repeatedly used spawn_local to continue running.

Even JS microtasks can starve other JS microtasks, it's just not something you should rely upon.

And you shouldn't be running `spawn_local` in a loop like that anyways. It's much better to use a single `spawn_local` with a loop inside of it, like this:

```rust
spawn_local(async move {
    loop {
        run_js_or_whatever();
        yield_macro().await;
    }
});
```
