### ISSUE TITLE
Futures created with `wasm_bindgen_futures::spawn_local` don't get executed

### ISSUE THREAD

**Issue by felipellrocha** [rustwasm/wasm-bindgen#2945]
I'm spinning a thread using `wasm_thread` (https://github.com/chemicstry/wasm_thread). Inside of it, I'm running some async functions inside of a `wasm_bindgen_futures::spawn_local` as such:

```rs
wasm_thread::spawn(move || {
  log::info!("1: spawn");
  while Ok(message) = channel_receiver.recv() {
    log::info!("2: message {:?}", &message);
    wasm_bindgen_futures::spawn_local(async move {
      log::info!("3: am i here?");
      download.asset().await;
    })
  }
});
```
Problem is that neither the 3rd `log::info!()` nor the `download.asset().await` get called.

Any idea why?

**Comment by Liamolucko** [comment]
The way the JS event loop works is that other tasks (such as your futures) only get run once the current task finishes. That's never happening because you're blocking the thread waiting for messages over the channel.

To get around that, you could use an async channel (e.g. from `futures-channel`) instead of a blocking one, which will yield to the event loop instead of blocking (if you also spawn it using `wasm_bindgen_futures::spawn_local).

**Comment by felipellrocha** [comment]
I have modified it to this:
```rs
wasm_thread::spawn(move || {
  log::info!("1: spawn");
  wasm_bindgen_futures::spawn_local(async move {
    log::info!("2: message {:?}", &message);
    while Ok(message) = channel_receiver.recv().await {
      log::info!("3: am i here?");
      download.asset().await;
    }
  })
});
```

I still get nothing

**Comment by Liamolucko** [comment]
Hmm - my suspicion is that because the thread entrypoint returns immediately, the worker is getting closed. There isn't really a good way to get around that unless `wasm_thread` were to support an async entrypoint directly (and only close the thread once it resolves).

**Comment by felipellrocha** [comment]
is there a safe way for me to keep it open? I suspect I can't just loop infinitely here since that would have the same issue?

**Comment by Liamolucko** [comment]
> throw errors on loop, or just the once?

Just the once, after spawning the future.

**Comment by felipellrocha** [comment]
Worked, thanks! Would've never figured this out on my own! :D

**Comment by Davidster** [comment]
Hello! I am currently encountering this issue and am wondering if it is even possible to fix this in wasm-bindgen? For now I plan on creating a wrapper along these lines:

```rust
fn spawn_thread<F, T>(f: F)
where
    F: FnOnce() -> T,
    F: Send + 'static,
    T: Send + 'static,
{
    if cfg!(target_arch = "wasm32") {
        thread::spawn(|| {
            f();
            wasm_bindgen::throw_str("Cursed hack to keep workers alive. See https://github.com/rustwasm/wasm-bindgen/issues/2945");
        });
    } else {
        thread::spawn(f);
    }
}
```

**Comment by drewcrawford** [comment]
I recently spent quite awhile tracking down why my futures are suddenly halting with no logs or warnings to this root cause (`close` call in wasm_thread's JS boilerplate).

It would be nice to get a log of some kind to provide any indication that workers are being closed.

Ideally, there would be some way to transfer 'close responsibility' into rust for workers that ought to be largely idle.  For example, a method on the builder that allows toggling the behavior, or a `park()` like function that uses a guard to wrap the close call.
