### ISSUE TITLE
Update openssl to v3?

### ISSUE THREAD

**Issue by DogsCodesStudio** [rustwasm/wasm-bindgen#3028]
### Summary

Could it be updated to v3 as the new ubuntu 22.04 has version 3.

**Comment by Liamolucko** [comment]
This is because of sfackler/rust-openssl#1645. Vendored OpenSSL is only enabled in the CI build, so a version of `wasm-bindgen` installed via. `cargo install` should use the system OpenSSL.

**Comment by DogsCodesStudio** [comment]
So i just gotta wait for that to be fixed for wasm-bindgen to get fixed?

**Comment by Liamolucko** [comment]
What do you mean by 'fixed'? Is the different version of OpenSSL causing some kind of problem?

But yes, you'll have to wait until `openssl-sys` updates to OpenSSL 3 for `wasm-bindgen` to use OpenSSL 3.

**Comment by DogsCodesStudio** [comment]
Yeah there is an issue, not 100% sure if the issue is my fault but the issue is when i run the command 
```
cargo install --locked wasm-bindgen-cli
```

i just get an error https://pastebin.com/P3Ki95FR

**Comment by Liamolucko** [comment]
Ah, I had assumed you were using the CI-built version of the CLI which uses vendored OpenSSL, since I found that issue about it not using v3. The issue I mentioned is unrelated, sorry about that.

The easiest fix would be to enable vendored OpenSSL, through `--features=vendored-openssl`; that sidesteps the system OpenSSL entirely, so should work.

I'll have a go at trying to reproduce this to see if it can be fixed for system OpenSSL, but vendored should work fine.

**Comment by DogsCodesStudio** [comment]
It seems to work by adding that. Unless you have something more you have found out i think this issue can be resolved.

**Comment by Liamolucko** [comment]
It looks like this was the relevant line of the error message:

```
  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
```

I was able to reproduce the issue, and installing `libssl-dev` fixed it.

Anyway, glad I could help!
