### ISSUE TITLE
Chrome Extension Manifest v3 refuses to evaulate unsafe-eval / wasm-unsafe-eval

### ISSUE THREAD

**Issue by cryptoquick** [rustwasm/wasm-bindgen#3098]
### Describe the Bug

In a Chrome Extension using the new Manifest v3 format, using more recent versions of Chrome (97+?), `wasm-unsafe-eval` is supposed to be used as the content security policy for calling wasm methods. It seems to work in some cases, but it still catches some wasm-bidgen generated calls as violating ordinary `unsafe-eval` rules. For example:

#### Error
Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'".

#### Stack Trace

```javascript
function __wbg_new_d87f272aec784ec0(arg0, arg1) {
  const ret = new Function(getStringFromWasm0(arg0, arg1));  // <-- highlighted line
  return addHeapObject(ret);
}
```

### Steps to Reproduce

1. Use wasm-pack to generate a pkg of a wasm-bindgen project
2. Bundle it into a project using webpack (might be unnecessary, but it's part of my build process, so it might bear mentioning)
3. Load the extension unpacked into the Chrome extensions page set to developer mode
4. Open the extension popup
5. View the Errors page for the extension

### Expected Behavior

The Chrome extension should be able to execute the wasm bundle without triggering an unsafe-eval exception.

### Actual Behavior

![Screenshot from 2022-10-03 07-38-22](https://user-images.githubusercontent.com/285690/193591704-a9e92275-2151-405a-b4fa-c627c1e62569.png)

### Additional Context

If I had to guess, Chrome is doing some form of static analysis, and there might be a way it expects to see WASM methods called that wasm-bindgen exceeds the bounds of in some ways (but not all). This might include creating a function from strings provided by the wasm binary, as highlighted in the stack trace.

**Comment by Liamolucko** [comment]
That looks to me like the generated bindings for [`Function::new_no_args`](https://docs.rs/js-sys/latest/js_sys/struct.Function.html#method.new_no_args); so, I think this is happening because there's some Rust code calling `new Function()`, rightfully triggering the CSP error.

Do you have the full stack trace of the error? That should show what crate is calling `new Function()` and causing the problem.

**Comment by cryptoquick** [comment]
Okay, figured it out. This should provide a more complete set of information:
[wasm-full-stack-trace-error-line-1181.zip](https://github.com/rustwasm/wasm-bindgen/files/9707392/wasm-full-stack-trace-error-line-1181.zip)

[module.zip](https://github.com/rustwasm/wasm-bindgen/files/9707389/module.zip)

![Screenshot from 2022-10-04 07-43-52](https://user-images.githubusercontent.com/285690/193836021-225237ef-b187-4900-8055-d63a75d0d3c3.png)

Let me know if there's anything else I can provide that might help!

**Comment by Liamolucko** [comment]
I managed to get the debug symbols working (thank you for providing the link to the repo!) and it turns out that it's coming from this line in a very old version of the now-deprecated `rand_os`:

https://github.com/rust-random/rand/blob/bce70e348242a3a4f91b85b0bf90de2d03527f08/rand_os/src/wasm32_bindgen.rs#L32

That's being depended on by `rand` v0.6.5, which is depended on by both `bitmask-core` and `secp256k1`. So, updating `rand` in both those places should fix this issue.

**Comment by cryptoquick** [comment]
Holy cow, that's awesome, thanks a ton, @Liamolucko ! You gotta tell me how you got proper debug symbols working!? :pray:

**Comment by cryptoquick** [comment]
Aha! Thank you very much! Also, thanks for chiming in, @alexcrichton. Your stewardship of all your work is appreciated. Closing this now.
