### ISSUE TITLE
What is the best way to use Object.prototype.toString.call ?

### ISSUE THREAD

**Issue by linzhipeng98** [rustwasm/wasm-bindgen#3103]
According to the documentation [JS Snippets](https://rustwasm.github.io/wasm-bindgen/reference/js-snippets.html).
I create javascript file in the crate root(where Cargo.toml is located):

```
// object.js
export function to_string(value) {
  return Object.prototype.toString.call(value)
}
```

in lib.rs:
```
#[wasm_bindgen(module = "/object.js")]
extern "C" {
    fn to_string(value: JsValue) -> JsValue;
}

#[wasm_bindgen]
pub fn test() -> JsValue {
    to_string(JsValue::undefined())
}
```

test() function run in browser expect return string "[object Undefined]" but received undefined。

**Comment by Liamolucko** [comment]
You need to actually return the result from `to_string`. object.js should look like this instead:

```js
export function to_string(value) {
  // note the `return`
  return Object.prototype.toString.call(value);
}
```

**Comment by linzhipeng98** [comment]
@Liamolucko Oh..I made a silly mistake, thank you. By the way, Can I use Object.prototype.toString.call only through JS Snippets?

**Comment by Liamolucko** [comment]
> By the way, Can I use Object.prototype.toString.call only through JS Snippets?

No, there are a few other ways to do it.

Adding `#[wasm_bindgen(final)]` to a method changes the generated JS to retrieve the method from the prototype of the class the method belongs to instead of just calling it directly on the object. In other words, instead of generating `object.method(...)`, it generates `Class.prototype.method.call(object, ...)`, which is what you want. (See https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-js-imports/final.html for more details.)

So, you can bind to `Object.prototype.toString` like so:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    type Object;

    #[wasm_bindgen(method, final, js_name = "toString")]
    fn to_string(this: &Object) -> String;
}
```

and it will always use the version from `Object.prototype`.

Another option is to treat `Object.prototype.toString` as a namespace containing the function `call`:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = ["Object", "prototype", "toString"], js_name = call)]
    fn to_string(value: &JsValue) -> String;
}
```

This approach has the benefit that you don't need to downcast to your custom `Object` first.

**Comment by linzhipeng98** [comment]
@Liamolucko Thank you very much!
