### ISSUE TITLE
How do I create a Web Component

### ISSUE THREAD

**Issue by ianpurton** [rustwasm/wasm-bindgen#3119]
I can't find any examples (that work) of creating a web component in rust.

So I want to do something like

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen(extends=web_sys::HtmlElement)]    
pub struct HelloWorld;

#[wasm_bindgen]
impl HelloWorld {
    #[wasm_bindgen(constructor)]
    pub fn new() -> HelloWorld {

        HelloWorld {}
    }
}

#[wasm_bindgen(start)]        
pub fn main() {

    let window = web_sys::window().unwrap();
    let document = window.document().unwrap();

    window.custom_elements().define(
        "hello-world",
        &HelloWorld::new(),

    ).unwrap();
}
```

I'm not sure how to get the `&HelloWorld::new()` into a `js_sys::Function` so that it can be passed into `custom_elements().define`

and then how would I handle the call backs?

if anyone has a minimal working example that would be great.

**Comment by jonboj** [comment]
Also looked into this once. There are a bunch of open issues related to construction/inheritance of JS objects #2853, #1721 and especially #621, #210 involving designers of `wasm-bindgen`. So looks like that defining Custom Elements from Rust wasn't supported by the framework.

**Comment by ianpurton** [comment]
@jonboj Thanks. In the end I found a library that works. https://github.com/gbj/custom-elements

I'll close this out.

**Comment by martinitus** [comment]
Funny enough I started today with the goal to port [this example](https://www.webassemblyman.com/webcomponents.html) to the current version of web-sys and wasm-bindgen. I got stuck at the same point. However, if above example ever worked, then it at least used to be possible without any javascript glue like done in (https://github.com/gbj/custom-elements). I assume some of the features where dropped from wasm-bindgen because they were to experimental/hacky?
