### ISSUE TITLE
js-sys Math::random() will interrupt program 

### ISSUE THREAD

**Issue by linzhipeng98** [rustwasm/wasm-bindgen#3149]
### Steps to Reproduce

1. In official repo [examples/add](https://github.com/rustwasm/wasm-bindgen/tree/main/examples/add)
2. Add js-sys dependency
3. Add Math::random() call in add function

```rust
use js_sys::Math;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn add(a: u32, b: u32) -> u32 {
    let value = Math::random();
    a + b
}
```

4. build the example locally with `npm run serve`

### Expected Behavior

Browser will display a dialog

### Actual Behavior

Browser not display a dialog

**Comment by Liamolucko** [comment]
This looks to be another case of #3102.

TL;DR: because the function doesn't need any JS glue, wasm-bindgen passes it to the wasm binary using `export const ...` instead of `export function ...`. Webpack then attempts to reference it before use because of some circular dependency weirdness, which happens to work out for `function`s since they get hoisted, but not for `const`s.
