### ISSUE TITLE
`JsValue` arguments to async functions are undefined

### ISSUE THREAD

**Issue by breqdev** [rustwasm/wasm-bindgen#3199]
### Describe the Bug

When calling an async Rust function which accepts a `JsValue` from JavaScript, the value becomes undefined once it reaches Rust. This does not happen for non-async functions.

### Steps to Reproduce

Rust code:
```rust
use log::info;

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen]
pub async fn main(my_object: JsValue) {
  console_error_panic_hook::set_once();
  console_log::init().unwrap();

  info!("{:?}", my_object);
}
```

JavaScript code:

```javascript
let my_object = { my_property: 1 };

wasm.main(my_object);
```

### Expected Behavior

I expected to be able to see the passed-in object in Rust. (e.g., `JsValue(Object({"my_property":1}))`)

### Actual Behavior

The object is undefined. `JsValue(undefined)`

### Additional Context

This issue does not appear when using a non-async function, only when using an async function.

**Comment by Liamolucko** [comment]
I can't reproduce this. It sounds similar to #3167, but that only happens when taking `&JsValue`, not an owned `JsValue`. Could you provide a bit more info on how to reproduce this on the JavaScript end? I can't see how you're actually initialising the wasm module, so it's possible that something you're doing there is causing this.

**Comment by breqdev** [comment]
I've pushed a reproduction here: https://github.com/breqdev/bindgen-reproduction

To cause this bug, I'm doing the following:
* run `wasm-pack build`
* `cd www` and `npm start`
* open the tab in http://localhost:8080/ and open the console log

(While creating the reproduction repo, it seems like some of what I posted in the issue description oversimplified what was actually needed to cause the issue -- sorry about that!)

**Comment by Liamolucko** [comment]
I've figured out the source of the problem. `wasm-bindgen` supports Rust binary targets (i.e. using a `main.rs` instead of a `lib.rs`), treating `main` the same as a function annotated with `#[wasm_bindgen(start)]`. The problem is, it checks for `main` by looking for a function which is:
- named `main`
- has the wasm signature `(i32, i32) -> i32`

Your function is named `main` and happens to have that signature, which results in it getting called at initialization time with bogus values which end up getting interpreted as `undefined`. It then runs a second time when you call it normally, but panics because of `console_log::init()` getting run twice.

I'll try to find a better way to detect `main` that doesn't result in false positives like this, but in the meantime the easiest workaround is just to name it something other than `main`.

**Comment by breqdev** [comment]
Thank you so much for looking into this! I can confirm that the workaround works for my project.
