### ISSUE TITLE
Is this a bug, or am I still doing something wrong?

### ISSUE THREAD

**Issue by uberFoo** [rustwasm/wasm-bindgen#3209]
All done jumping to conclusions. Below is what started me down the path of running wasm-pack for testing. Mostly because when I ran this _before_ I figured out what geckodriver is, it crashed Safari. It was really annoying.

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.50s
     Running `target/debug/wasm-bindgen-test-runner /Users/uberfoo/projects/github/wasm-bindgen/target/wasm32-unknown-unknown/debug/deps/headless-db6a363b767c341a.wasm`
Set timeout to 20 seconds...
Running headless tests in Firefox on `http://127.0.0.1:54255/`
Try find `webdriver.json` for configure browser's capabilities:
Not found
driver status: signal: 9 (SIGKILL)                
driver stdout:
    1671504789604       geckodriver     INFO    Listening on 127.0.0.1:54255

Error: non-200 response code: 500                 
{"value":{"error":"session not created","message":"Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line","stacktrace":""}}
```

Thanks for helping me navigate this rather sprawling project!

**Comment by Liamolucko** [comment]
It looks like `geckodriver` is failing to find Firefox. It looks for either Firefox or Firefox Nightly in either `/Applications` or `~/Applications` (assuming you're using macOS, since you mentioned Safari), so that's probably happening because either:

- You don't have Firefox installed
- You have some other edition of Firefox installed, e.g. Firefox Developer Edition
- You have Firefox installed in some other location.

`geckodriver` will also look for `firefox-bin` in `PATH`, so to work around this problem if you have Firefox installed in a way it can't detect, you can add it to `PATH` manually:

```sh
export PATH="$PATH:$FIREFOX_APP_PATH/Contents/MacOS"
```

where `FIREFOX_APP_PATH` is the path to `Firefox.app` (or `Firefox Nightly.app`, `Firefox Developer Edition.app`, etc.)

**Comment by uberFoo** [comment]
OK, that makes sense. I've got Firefox Developers Edition installed. I'll get it sorted out. Thanks again for the help!

**Comment by Liamolucko** [comment]
No problem!
