### ISSUE TITLE
Window::create_image_bitmap_with_canvas_rendering_context_2d throws error

### ISSUE THREAD

**Issue by JohnScience** [rustwasm/wasm-bindgen#3227]
### Describe the Bug

I wanted to conveniently create an `ImageBitmap` from `CanvasRenderingContext2d`. When I found `Window::create_image_bitmap_with_canvas_rendering_context_2d`, I expected that it's a convenience method for doing so.

However, when I used it, I received the following error:

```text
TypeError: Failed to execute 'createImageBitmap' on 'Window': The provided value is not of type '(Blob or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or ImageData or OffscreenCanvas or SVGImageElement or VideoFrame)'.
```

### Steps to Reproduce

```rust
async fn update_buf_dims_gracefully(
    canvas: &HtmlCanvasElement,
    ctx: &CanvasRenderingContext2d,
    window: &Window,
) {
    let client_width= canvas.client_width();
    let client_height = canvas.client_height();

    let image_bitmap: JsFuture = window.
        create_image_bitmap_with_canvas_rendering_context_2d(ctx)
        .unwrap()
        .into();

    let image_bitmap = image_bitmap.await;
    match image_bitmap {
        Ok(image_bitmap) => { log(&image_bitmap) },
        Err(err) => { log(&err) }
    }

    canvas.set_width(client_width as u32);
    canvas.set_height(client_height as u32);
}
```

The code above is an incomplete implementation of a function relying on `Window::create_image_bitmap_with_canvas_rendering_context_2d`.

### Expected Behavior

`Window::create_image_bitmap_with_canvas_rendering_context_2d` should either be removed or be functional

### Actual Behavior

Results in an error.

### Additional Context

No additional context.

**Comment by jneem** [comment]
My reading of [this](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#imagebitmapsource) is that `ImageBitmapSource` should be defined as `CanvasImageSource or Blob or ImageData`, and then inlining the definition of `CanvasImageSource` gives the `HTMLXXElement`s, `ImageBitmap`, `VideoFrame`, and `OffscreenCanvas`. The `BufferSource` variant seems to come from [here](https://w3c.github.io/mediacapture-worker/#webidl-1303695453), but I can't find any source for the `CanvasRenderingContext2d` variant.

**Comment by Liamolucko** [comment]
Yeah, that shouldn't be there. It's there because `wasm-bindgen`'s WebIDL was initially taken from Firefox, which for whatever reason non-standardly supports passing `CanvasRenderingContext2D` to `createImageBitmap`.

The `BufferSource` variant is also broken, since the overload it's supposed to be a part of has a completely different signature to the regular `createImageBitmap`:

```webidl
Promise<ImageBitmap> createImageBitmap (BufferSource buffer, long offset, long length, ImageFormat format, ImagePixelLayout layout);
```

It doesn't seem like that standard ever really went anywhere, either ([the repo is archived](https://github.com/w3c/mediacapture-worker)).

So, I think they should both be removed. That is of course a breaking change, but I think it makes sense to do since any attempt to use them wouldn't work anyway (cc @alexcrichton).
