### ISSUE TITLE
Using "ptr" as struct field name causes infinite loop

### ISSUE THREAD

**Issue by emccorson** [rustwasm/wasm-bindgen#3388]
### Describe the Bug

If a struct has `ptr` as a field name, instantiating the object will cause the application to enter an infinite loop and eventually error with "Error: too much recursion".

### Steps to Reproduce

```rust
#[wasm_bindgen] 
pub struct UhOh {
    pub ptr: *const u8
}

#[wasm_bindgen]
pub fn test() -> UhOh {
    UhOh { ptr: 0 as *const u8 }
} 
```

1. Run the above `test` function in JavaScript.
2. Notice the error about too much recursion in the console.

### Expected Behavior

The UhOh object should be returned from the test function.

### Actual Behavior

The following error appears in the console:
```
Uncaught (in promise) Error: Error: too much recursion
```

### Additional Context

I believe it is caused by the following part of the generated JS:
```javascript
export class UhOh {

    static __wrap(ptr) {
        const obj = Object.create(UhOh.prototype);
        obj.ptr = ptr;    // <---- entering infinite loop here

        return obj;
    }
```

**Comment by snOm3ad** [comment]
Some additional context to Eric's comments, the issue happens because we create getters and setters for the public struct fields which are part of the generated JS. This means that when the assignment happens in `__wrap` it uses the setter which in turn uses the getter which also uses the getter:

```js
    /**
    * @returns {number}
    */
    get ptr() {
        const ret = wasm.__wbg_get_uhoh_ptr(this.ptr); // right here
        return ret;
    }
```

I'd like to submit a PR for this if no one else has started working on it. The issue seems to be with the generation step in `write_class`:

https://github.com/rustwasm/wasm-bindgen/blob/0753bec4c6f51d7e27b82c357e65cefab3c61dd3/crates/cli-support/src/js/mod.rs#L925-L941

Instead of using `obj.ptr` we can use a templated property `obj.{ptr_prop}` which we construct after examining the list of readable properties. If any properties end with "ptr" we can just append an extra underscore and work with that instead.

**Comment by daxpedda** [comment]
I think it would be better to just rename `ptr` to `__wbg_ptr` (like in #3349).
