### ISSUE TITLE
Unable to instantiate logger due to error message which originates from wasm-bindgen

### ISSUE THREAD

**Issue by alexisart** [rustwasm/wasm-bindgen#3447]
### Summary

When running `console_log::init().unwrap();` from the below code, I get the error message: `function not implemented on non-wasm32 targets` on Firefox.

```rust
if cfg!(any(target_arch = "wasm32", target_arch = "wasm64")) {
    console_log::init().unwrap();
}
```

### Additional Details

The build script is really complicated right now. I currently call SDL_main as I have not been able to get any indication of the code running in console if I attached the wasm_bindgen macro at all.

```rust
// Run as Library (e.g. Android and WebAssembly)
#[no_mangle]
#[allow(non_snake_case)]
pub extern fn SDL_main(_argc: libc::c_int, _argv: *const *const libc::c_char) -> libc::c_int {
    game::start();
    return 0;
}
```

I'm using:

```toml
console_log = { version = "1.0.0", features = ["color", "wasm-bindgen"] }
wasm-bindgen = "0.2.86"
```

I'm calling my wasm file with the below code after I generate both the js and wasm file with emmc:

```html
<script type="text/javascript">
var Module = {
    onRuntimeInitialized: function() {
        Module._SDL_main(); // SDL_main was exported
    }
};
</script>
<script src="/main.js"></script>
```

My project is located at https://github.com/alexisart/catgirl-engine

**Comment by daxpedda** [comment]
> ```rust
> if cfg!(any(target_arch = "wasm32", target_arch = "wasm64")) {
> ```

FWIW this can be shortened with `target_family = "wasm"`.

> [..] I get the error message: `function not implemented on non-wasm32 targets` [..]

There's really very little info to go by here. But I'm going to assume that the issue here is the compile target. `wasm-bindgen` officially only supports `wasm32-unknown-unknown`, you might have tried a different target. Looking at your repo, did you maybe try to use Emscripten?

It would be really helpful to put up a minimal reproducible example.

**Comment by alexisart** [comment]
Here's the minimal reproducible example

[min.zip](https://github.com/rustwasm/wasm-bindgen/files/11549982/min.zip)

**Comment by alexisart** [comment]
Okay, so I was trying to remove wasm-bindgen from my project, but it refused to do it. It turns out that the [console-log crate depends on wasm-bindgen](https://github.com/iamcodemaker/console_log/blob/main/Cargo.toml#L21C16-L23).

I'm going to reimplement the logger from scratch because I need proper logging to work and I can't use wasm32-unknown-unknown due to other dependencies banning using unknown target OS and requiring specifying using an "OS" even if it's emscripten.

I would like to reopen this issue as a feature request to start supporting emscripten

**Comment by daxpedda** [comment]
Unfortunately that's not possible, as `wasm-bindgen` considers Emscripten to be out of scope.

The deeper problem here is that `wasm32-unknown-unknown` isn't compatible with the C ABI: https://github.com/rust-lang/rust/issues/71871. This is a common problem that appears when wanting to use `wasm-bindgen`: https://github.com/rustwasm/wasm-bindgen/issues/2317.

Unfortunately there is currently not solution for this, though the Rust team is aware of it and trying to find a solution: https://github.com/rustwasm/team/issues/291. One proposal that might solve that problem is a new Wasm ABI: https://github.com/rust-lang/rust/issues/83788. Though it is currently still unstable.

So as it stands today, `wasm-bindgen` is not compatible with C, you will either have to drop `wasm-bindgen` or C to proceed.

**Comment by alexisart** [comment]
Thanks! I dropped wasm-bindgen as I wasn't using it myself, it was just a dependency of one of my dependencies. I've successfully implemented my own logger by using Emscripten's EM_ASM. This requires writing both very basic C and continuing Rust as usual, but it at least works.
