### ISSUE TITLE
Add URLSearchParams::new_with_form_data(&FormData);

### ISSUE THREAD

**Issue by jquesada2016** [rustwasm/wasm-bindgen#3473]
### Motivation

Cannot currently do:

```javascript
const form = new FomrData();

const params = new URLSearchParams(formData);
```

Using `web-sys`.

### Proposed Solution

Create a new constructor that accepts `&FormData`.

### Alternatives

Create instead a constructor which takes any arbitrary `JsValue`.

### Additional Context

N/A

**Comment by Liamolucko** [comment]
There's already a constructor that takes an arbitrary `JsValue`: [`UrlSearchParams::new_with_str_sequence_sequence`](https://docs.rs/web-sys/0.3.63/web_sys/struct.UrlSearchParams.html#method.new_with_str_sequence_sequence).

The reason it's called that is because `web-sys` is generated from WebIDL, where 'sequence' effectively means 'iterable'. So, by `str_sequence_sequence` the method really means `Iterable<Iterable<string>>`, which includes `FormData` since it's an iterator over `[key, value]` pairs.

**Comment by jquesada2016** [comment]
Ah perfect, thank you!
