### ISSUE TITLE
Docs for `Storage::get` and `Storage::set`

### ISSUE THREAD

**Issue by bonsairobo** [rustwasm/wasm-bindgen#3518]
### Motivation

When reading the docs for `web-sys`, it's very unclear what are the differences between `Storage::get_item` and `Storage::get`. Same for the setters. The docs just say "indexing getter" but I have no idea what that means. When trying to open the source code, it just links to some opaque macros business, requiring the reader to go learn how these macros work.

### Proposed Solution

Probably just a description with more detail than "indexing getter" would be sufficient.

**Comment by Liamolucko** [comment]
`Storage::get_item(key)` returns `this.getItem(key)` and `Storage::get(key)` returns `this[key]`, both of which do the same thing. More generally, an 'indexing getter'/setter/deleter is a function that gets/sets/deletes `this[key]`. I agree that the docs should probably be a bit better.

Personally, I think it's unnecessary to have both functions when they do the same thing, but it looks like this was discussed before in https://github.com/rustwasm/wasm-bindgen/pull/665#issuecomment-411253469 and is an intentional choice.

**Comment by daxpedda** [comment]
I actually think that "indexing getter" should be sufficient, but I'm happy to review a PR improving the documentation further.

**Comment by bonsairobo** [comment]
@daxpedda My confusion comes from the fact that the function signatures of `get_item` and `get` are identical, but the names are slightly different, and one has a link to "MDN documentation" while the other does not. Because the `Index` and `IndexMut` traits are not being implemented, it's confusing what "indexing" actually means in the context of these bindings.

> Storage::get_item(key) returns this.getItem(key) and Storage::get(key) returns this[key], both of which do the same thing. More generally, an 'indexing getter'/setter/deleter is a function that gets/sets/deletes this[key]

Perhaps in this case, the functions behave identically. If the bindings would *always* behave the same, then I don't think there is any use in generating both `get_item` and `get`, but I am guessing there are cases where `this.getItem(key)` and `this[key]` don't do the same thing.

As for how to improve the docs, now that @Liamolucko described the semantic difference between those APIs, I think it would be appropriate to say in the docs:

> Indexing getter. As in the literal Javascript `this[key]` instead of `this.getItem(key)`.

And similarly:

> Indexing setter. As in the literal Javascript `this[key] = value` instead of `this.setItem(key, value)`.

**Comment by daxpedda** [comment]
> Because the `Index` and `IndexMut` traits are not being implemented, it's confusing what "indexing" actually means in the context of these bindings.

I would probably be good to implement those, but I didn't dig through old issues to figure out why this wasn't in fact done.

> > Indexing getter. As in the literal Javascript `this[key]` instead of `this.getItem(key)`.
> 
> And similarly:
> 
> > Indexing setter. As in the literal Javascript `this[key] = value` instead of `this.setItem(key, value)`

This might not be possible, because WebIDL is probably not aware that the other function "looks similar". But I think showcasing what "indexing" getter means would be fine with me.

Again, PR's are welcome.

---

You have to keep in mind that all those types and methods are auto-generated through the WebIDL. `web-sys` just contains bindings to the Web API and doesn't intend to expose a nice Rusty API or document what any of these methods actually do, we just link to the MDN documentation.

A different project that is working on wrapping these Web APIs in nice Rusty libraries is [Gloo](https://crates.io/crates/gloo), so you might want to look there if you want something more then just "sys" bindings.

**Comment by bonsairobo** [comment]
@daxpedda

> PR's are welcome.

Yea I'm happy to work on this, just going through the necessary step of figuring out what people actually want so I don't do the wrong thing.

> You have to keep in mind that all those types and methods are auto-generated through the WebIDL. 

Yea I didn't expect anything more than that. I just came across these APIs and could not understand what they did. Could be my lack of Javascript experience showing.

> This might not be possible

It seems like all I would do is add to the doc strings that are defined [here](https://rustwasm.github.io/wasm-bindgen/api/src/web_sys/features/gen_Storage.rs.html#5). Or maybe I'm misunderstanding you; I don't really know how the codegen works.

**Comment by daxpedda** [comment]
> > This might not be possible
> 
> It seems like all I would do is add to the doc strings that are defined [here](https://rustwasm.github.io/wasm-bindgen/api/src/web_sys/features/gen_Storage.rs.html#5). Or maybe I'm misunderstanding you; I don't really know how the codegen works.

That's the generated code, but we need to adjust the WebIDL generator, somewhere around [here](https://github.com/rustwasm/wasm-bindgen/blob/0853bb7fa7727b0cc5a93974449970ce4bbf1970/crates/webidl/src/generator.rs#L424).

**Comment by bonsairobo** [comment]
Oh I see now why the message can't be *too* specific or it will proliferate to any types that have indexing. I think I can probably just make the message more generic then and still get the point across.
