### ISSUE TITLE
Unify `*Event::new_with_event_init_dict` function names

### ISSUE THREAD

**Issue by hillin** [rustwasm/wasm-bindgen#3583]
### Motivation

Most, if not all of the `*Event` types generated by the web-sys crate, has a function which is used to construct such an event object with an initial value dictionary. Most of them are named `new_with_event_init_dict`, however for `MouseEvent` it's named `new_with_mouse_event_init_dict`.

### Proposed Solution

Change the name of the said function of `MouseEvent` to `new_with_event_init_dict` too.

**Comment by daxpedda** [comment]
The names are generated by our WebIDL generator, so it has to be adjusted there.
In any case, we can't change it as it would be a breaking change.

But generally speaking yes, when the next breaking change comes we should improve the naming output of the WebIDL generator.

**Comment by Liamolucko** [comment]
The name differences are happening because the names are different in the WebIDL the names are generated from:

https://github.com/rustwasm/wasm-bindgen/blob/4d4851d45200d0d1aeaa07108072dfa0f1f185f7/crates/web-sys/webidls/enabled/MouseEvent.webidl#L13

https://github.com/rustwasm/wasm-bindgen/blob/4d4851d45200d0d1aeaa07108072dfa0f1f185f7/crates/web-sys/webidls/enabled/PointerEvent.webidl#L14

This is yet another quirk inherited from Firefox: [the standard's WebIDL for `MouseEvent`](https://www.w3.org/TR/uievents/#idl-mouseevent) calls it `eventInitDict`. So the real solution to this is (whenever we make breaking changes) to replace all our all old WebIDL files from Firefox with the standard versions (plus `[Throws]` and such).

Another case of this that personally annoys me is [`Window::create_image_bitmap_with_image_bitmap_and_a_sx_and_a_sy_and_a_sw_and_a_sh`](https://docs.rs/web-sys/0.3.64/web_sys/struct.Window.html#method.create_image_bitmap_with_image_bitmap_and_a_sx_and_a_sy_and_a_sw_and_a_sh); for some reason Firefox's WebIDL prefixes all the names with `a` and makes this name even longer than it needs to be.
