### ISSUE TITLE
`inputType` may be `undefined` for `input` event

### ISSUE THREAD

**Issue by bicarlsen** [rustwasm/wasm-bindgen#3608]
### Describe the Bug

For an `input` event on `<input type='number'>` if you click the up/down arrows to increment/decrement the value and try to get the [`inputType`](https://docs.rs/web-sys/latest/web_sys/struct.InputEvent.html#method.input_type) can be `undefined`. 

### Steps to Reproduce
https://github.com/bicarlsen/input_type-tauri

### Expected Behavior
[`InputEvent.input_type`](https://docs.rs/web-sys/latest/web_sys/struct.InputEvent.html#method.input_type) should return an `Option<String>` to handle the `undefined` case.

### Actual Behavior
[`InputEvent.input_type`](https://docs.rs/web-sys/latest/web_sys/struct.InputEvent.html#method.input_type) returns a `String`, causing an error when the value is `undefined`.

### Additional Context
It appears the `inputType` is inconsistent across browsers.

**Comment by bicarlsen** [comment]
I made a [JSFiddle with an MRE](https://jsfiddle.net/vzqLo690/3/). If you click on the up/down buttons in Chrome or Edge it gives me `undefined`.

**Comment by bicarlsen** [comment]
Confirmed as `undefined` in Safari, too.

**Comment by daxpedda** [comment]
So apparently this is a more complicated issue. The reason why `inputType` is undefined is because the type here is not an `InputEvent` at all, but an `Event`. This happens on both Chrome and Safari when the input isn't done by the user but by the browser, some level of autocomplete.

Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1349207
Safari: https://bugs.webkit.org/show_bug.cgi?id=217693

This isn't actionable from us here, I guess you will just have to take an `Event` and then figure out if it is an `InputEvent` manually.

**Comment by bicarlsen** [comment]
Cool. Thanks for figuring that out.
