### ISSUE TITLE
Macro to generate getters and setters

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [rustwasm/wasm-bindgen#3613]
### Motivation

After spending too long (60 seconds) writing getters and setters, i resolved to write a macro to add them automagically.

### Proposed Solution

I got this far: ~~(does not work, future readers!)~~ scroll down for working version

```rs
use paste::paste;

macro_rules! generate_getters_and_setters {
    ($struct: ty, $name:ident, $type:ty) => {
        paste! {
            impl $struct {
                #[wasm_bindgen(getter)]
                pub fn $name(&self) -> $type {
                    return self.$name.clone();
                }

                #[wasm_bindgen(setter)]
                pub fn [< set_ $name >](&mut self, $name: $type) {
                    // ^^^^^^^^^^^^^^^^ this syntax is part of `paste`
                    self.$name = $name;
                }
            }
        }
    };
}

//usage
pub struct Thing {
    foo: String,
    bar: u32,
}
generate_getters_and_setters!(Thing, foo, String);
generate_getters_and_setters!(Thing, foo, u32);
```
Unfortunately I got this error which I couldn't google-fu my way through:
```
error: custom attribute panicked
  --> src/colony.rs:8:17
   |
8  |                 #[wasm_bindgen(getter)]
   |                 ^^^^^^^^^^^^^^^^^^^^^^^
...
74 | generate_getters_and_setters!(Colony, name, String);
   | --------------------------------------------------- in this macro invocation
   |
   = help: message: arguments cannot be `self`
   = note: this error originates in the macro `generate_getters_and_setters` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by SIGSTACKFAULT** [comment]
I'm an idiot. I forgot the `#[wasm_bindgen]` on the impl block the macro generates. There should probably be a better error message for that.

**This Works:**

```rust
macro_rules! generate_getters_and_setters {
    ($struct: ty, $name:ident, $type:ty) => {
        paste! {
            #[wasm_bindgen]
            impl $struct {
                #[wasm_bindgen(getter)]
                pub fn $name(&self) -> $type {
                    return self.$name.clone();
                }

                #[wasm_bindgen(setter)]
                pub fn [< set_ $name >](&mut self, $name: $type) {
                    self.$name = $name;
                }
            }
        }
    };
}
```

Would of course need much better error messages to actually ship, but you can copy-paste this into your project right now.

**Comment by daxpedda** [comment]
I'm not sure what the proposal here is exactly, but we don't plan to add a macro like this.

**Comment by SIGSTACKFAULT** [comment]
@daxpedda instead of writing
```rust
[wasm_bindgen(getter)]
fn foo(&self) -> i32 { ... }
[wasm_bindgen(setter)]
fn set_foo(&mut self, value: i32) -> i32 { ... }
```
for every. single. member.
you can do
```rust
generate_getters_and_setters!(Thing, foo, i32);
```
much easier. This should be a builtin.

**Comment by daxpedda** [comment]
I see.

This is still probably not something I would add to `wasm-bindgen`. Generally speaking I'm not a big fan of adding more and more convenience functions to `wasm-bindgen` & co that aren't absolutely necessary. I would prefer to delegate this to other crates, e.g. [Gloo](https://crates.io/crates/gloo). `wasm-bindgen` & co should remain foundational crates and basically should provide only bindings and what is absolutely necessary to get things working.

In any case, I'm not aware of any other crate trying to use `wasm-bindgen` to make it easier to generate nice JS/TS bindings, probably because `wasm-bindgen` needs a lot of improvements on this front. But I would also not recommend using a macro like this, but more like a attributes on fields. Just doing a quick search on Crates.io I saw this: [`derive-getters`](https://crates.io/crates/derive-getters).

**Comment by SIGSTACKFAULT** [comment]
Ah, makes sense.

**Comment by Liamolucko** [comment]
By the way, `wasm-bindgen` already generates getters and setters automatically if the fields are public - so if you changed the definition of `Thing` to this:

```rs
#[wasm_bindgen]
pub struct Thing {
    #[wasm_bindgen(getter_with_clone)]
    pub foo: String,
    pub bar: u32,
}
```

`foo` and `bar` would already have getters and setters, you wouldn't need to write them by hand. The `#[wasm_bindgen(getter_with_clone)]` attribute is there because by default only `Copy` types are allowed to be public like this.
