### ISSUE TITLE
Not working when using u64 type in safari14

### ISSUE THREAD

**Issue by hancy87** [rustwasm/wasm-bindgen#3710]
### Describe the Bug
Still not working when using u64 type in Safari14 

### Steps to Reproduce

The web-sys: performance.now sample on the guidebook site still doesn't work in Safari 14.

WebAssembly.compile error occurs when going to the sample website after running ios14 with xcode simulation.

https://rustwasm.github.io/wasm-bindgen/exbuild/performance/ 

Works fine in IOS15 and later simulations

**Comment by Liamolucko** [comment]
What specific version of iOS 14 are you using? According to https://webassembly.org/roadmap/, the `i64`-to-`bigint` integration that `wasm-bindgen` is relying on was added in iOS 14.5, so it won't work on versions earlier than that.

**Comment by Liamolucko** [comment]
Wait a minute - that example doesn't pass `u64` to/from JS in the first place. Are you sure that's the issue you're running into?

**Comment by hancy87** [comment]
So what are the other reasons why it doesn't work on Safari 14?

**Comment by daxpedda** [comment]
Could you share the error with us?

**Comment by hancy87** [comment]
When you access the sample page in the ios14 browser, the following error occurs in the DevTools console.

CompileError: WebAssembly.Module doesn't parse at byte 316: invalid opcode 193, in function at index 4

**Comment by daxpedda** [comment]
I believe Opcode 193 (C1) is the `extend16_s` instruction, which is part of the sign-extension operations proposal.
The [roadmap](https://webassembly.org/roadmap) seems to indicate that this requires at least Safari v14.1.

Though this isn't an issue with `wasm-bindgen` but with Rust. Since Rust v1.70 [this proposal is enabled by default](https://github.com/rust-lang/rust/blob/19079cf804330a0d3d767a19a935c5eebdfeba0f/RELEASES.md#compatibility-notes-4). I've read somewhere that you can disable that by using `-Ctarget-cpu=mvp` but I've never tried it, but compiling with a Rust version below v1.70 should solve your problem.

**Comment by hancy87** [comment]
I have confirmed that it works fine with rust v1.69. Thanks for your help.

But I have one more question.

In 1.69, when I build with dev, it works fine, but when I build with release, I get an invalid opcode 192 error.

So I set the release defaults in the dev profile and it works fine,

On the contrary, if I build with dev default to release, it doesn't work.

I wonder if there is any difference between the build profiles?

**Comment by daxpedda** [comment]
Build profiles should have no effect on which Wasm proposals are enabled or not. But some optimizations might use them, considering what you are describing though, it might just be a bug in Rustc/LLVM codegen.

Opcode 192 (C0) is `extend8_s`, which is still an instruction from the sign-extension operations proposal.
In any case, this is unrelated to `wasm-bindgen`.
