### ISSUE TITLE
Unable to resolve version issue

### ISSUE THREAD

**Issue by adityakak27** [rustwasm/wasm-bindgen#3900]
### Summary

I am new to rust, and unable to understand what this means. I have tried updating the package, but every time something fails to install, and causes an error.

### Additional Details

Photos of the error are provided below:

![image](https://github.com/rustwasm/wasm-bindgen/assets/146877885/df5a252a-c44e-4414-a3dd-2e43ddf5efab)
![image](https://github.com/rustwasm/wasm-bindgen/assets/146877885/863a9614-e22d-407e-a473-97a1bc142dec)

**Comment by Liamolucko** [comment]
Updating `wasm-bindgen-cli` isn't working because `cargo leptos` doesn't use it, it has `wasm-bindgen` 0.2.92 baked in.

I'm not aware of any way to change which version it uses (without just cloning their repo and changing the Cargo.toml), so the simplest solution would be to follow the other instruction and update the wasm-bindgen library to 0.2.92 instead.

**Comment by wildwestrom** [comment]
I'm encountering the same issue. I followed the instructions but the error persists.

**Comment by adityakak27** [comment]
The other instruction is also not working, it shows me the same issue i think, one or more packages fail to install

**Comment by juntuu** [comment]
I encountered this same issue when using the starter template for Leptos.

Trying the suggestion from the error message:

```
You should be able to update the wasm-bindgen dependency with:

    cargo update -p wasm-bindgen --precise 0.2.92
```

gave an error:

```
error: failed to select a version for the requirement `wasm-bindgen = "=0.2.89"`
candidate versions found which didn't match: 0.2.92
```

Changing the project's dependency in `Cargo.toml` fixed the issue for me:

```patch
-wasm-bindgen = "=0.2.89"
+wasm-bindgen = "=0.2.92"
```

The suggested update didn't work, because the `Cargo.toml` had precise version. But updating the version requirement manually was fine.

---

I think this is an issue with `cargo-leptos` specifically as it sets the `wasm-bindgen-cli` version. I think it could warn about version mismatch with more helpful message.

**Comment by adityakak27** [comment]
> I encountered this same issue when using the starter template for Leptos.
> 
> Trying the suggestion from the error message:
> 
> ```
> You should be able to update the wasm-bindgen dependency with:
> 
>     cargo update -p wasm-bindgen --precise 0.2.92
> ```
> 
> gave an error:
> 
> ```
> error: failed to select a version for the requirement `wasm-bindgen = "=0.2.89"`
> candidate versions found which didn't match: 0.2.92
> ```
> 
> Changing the project's dependency in `Cargo.toml` fixed the issue for me:
> 
> ```diff
> -wasm-bindgen = "=0.2.89"
> +wasm-bindgen = "=0.2.92"
> ```
> 
> The suggested update didn't work, because the `Cargo.toml` had precise version. But updating the version requirement manually was fine.
> 
> I think this is an issue with `cargo-leptos` specifically as it sets the `wasm-bindgen-cli` version. I think it could warn about version mismatch with more helpful message.

This worked for me! Thank you so much for this, I hope others will also find this solution to be as helpful as I did.
