### ISSUE TITLE
IDBDatabase webidl is incomplete

### ISSUE THREAD

**Issue by kegsay** [rustwasm/wasm-bindgen#3959]
The [IDBDatabase.webidl](https://github.com/rustwasm/wasm-bindgen/blob/main/crates/web-sys/webidls/enabled/IDBDatabase.webidl#L27) has:
```
    IDBTransaction transaction ((DOMString or sequence<DOMString>) storeNames,
                                optional IDBTransactionMode mode = "readonly");
```
However, this is missing the `options` field as detailed on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/transaction). The main (only?) option this presents is a critical one however: https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/transaction#options as it provides the only way to actually make IndexedDB durable.

Is there any reason why this field is missing, and if not, can it be added? Otherwise it makes creating robust WASM code via Rust effectively impossible as you can't be sure your writes are tolerant to power failures / OS crashes.

**Comment by Liamolucko** [comment]
`wasm-bindgen`'s WebIDL files were all copied from Firefox several years ago, and have been manually updated to add new APIs over the years. [Firefox only seems to have implemented `options` recently](https://bugzilla.mozilla.org/show_bug.cgi?id=1878143), meaning that it wasn't in their WebIDL file back when we copied it and we still don't have it because nobody's added it since.

Feel free to make a PR adding it! There are instructions at https://rustwasm.github.io/wasm-bindgen/contributing/web-sys/supporting-more-web-apis.html. The WebIDL function definition should be the same as the one provided by the spec at https://w3c.github.io/IndexedDB/#idl-index.

In the long term, #2983 is the solution for how to stop things getting outdated like this in the first place.

**Comment by kegsay** [comment]
Firefox's support was only adding the durability property to the IDBTransaction. It's supported the option when creating the transaction much longer I thought.
