### ISSUE TITLE
"extern blocks must be unsafe" for 2024 edition

### ISSUE THREAD

**Issue by zroug** [rustwasm/wasm-bindgen#4218]
### Describe the Bug

`wasm_bindgen` attribute doesn't work for extern blocks in 2024 edition.

### Steps to Reproduce

1. Use `rustc 1.84.0-nightly` and configure project to use 2024 edition.
2. Try to compile
   ```rust
   use wasm_bindgen::prelude::*;

   #[wasm_bindgen]
   extern {
	   pub fn test();
   }
   ```
3. [Playground link](https://play.rust-lang.org/?version=nightly&edition=2024&code=use+wasm_bindgen%3A%3Aprelude%3A%3A*%3B%0A%0A%23%5Bwasm_bindgen%5D%0Aextern+%7B%0A%09fn+test%28%29%3B%0A%7D) (but it can't be reproduced on the playground because it only affects the WASM target).

### Expected Behavior

The example should compile.

### Actual Behavior

```
error: extern blocks must be unsafe
 --> src/test.rs:5:9
  |
5 |     pub fn test();
  |            ^^^^
```

Note: Adding the unsafe keyword to the extern block doesn't help, same error.

**Comment by daxpedda** [comment]
See https://github.com/rust-lang/rust/issues/132425.

**Comment by ehuss** [comment]
After some investigation, I don't believe there is anything that rustc can do to avoid this. It uses hygiene data of the spans to determine which edition something is from, and because of the behavior with [`respan`](https://github.com/rustwasm/wasm-bindgen/blob/f1d60abe8244eceff2d08d0e7e9b55b07a8b2e1f/crates/backend/src/codegen.rs#L1417-L1441) mentioned in https://github.com/rust-lang/rust/issues/132425, that edition information is getting overridden.

@daxpedda Would you be willing to try to find some way to adjust `respan` (or the way it is called) so that it doesn't change the hygiene data? I think the only token that matters is the `extern` keyword that starts the extern block, and we need to avoid changing the hygiene on that token to the caller's edition.

One option is to avoid calling `respan()` or `set_span()` on that token.

Another option, and I'm not certain this is correct, is to use `located_at()` which will use the edition from the proc-macro, but with the position data from the caller. So, something like this:

```diff
diff --git a/crates/backend/src/codegen.rs b/crates/backend/src/codegen.rs
index e5f3cfb9..d5d14743 100644
--- a/crates/backend/src/codegen.rs
+++ b/crates/backend/src/codegen.rs
@@ -1894,9 +1894,9 @@ fn respan(input: TokenStream, span: &dyn ToTokens) -> TokenStream {

     for (i, token) in spans.into_iter().enumerate() {
         if i == 0 {
-            first_span = token.span();
+            first_span = Span::call_site().located_at(token.span());
         }
-        last_span = token.span();
+        last_span = Span::call_site().located_at(token.span());
     }

     let mut new_tokens = Vec::new();
```

I'm not familiar with wasm-bindgen, so I don't know how to test that this still gives the kinds of error messages that you want.

**Comment by daxpedda** [comment]
Thank you for looking this deeply into it and even suggesting a solution @ehuss.

I'm going to take the lazy route here and simply add `unsafe` to all `extern "C" { ... }` blocks, as this is still compatible with our MSRV. This should avoid any changes to error messages.

**Comment by ehuss** [comment]
> I'm going to take the lazy route here and simply add `unsafe` to all `extern "C" { ... }` blocks, as this is still compatible with our MSRV. This should avoid any changes to error messages.

Ah! I was going to suggest this, but I saw `rust-version = "1.57"` in your Cargo.toml, which seemed far too old to support it (since `unsafe extern` was added in 1.82). I assumed you are not willing to bump it that high?

**Comment by daxpedda** [comment]
Indeed you are right, I was [reading the reference from v1.57](https://doc.rust-lang.org/1.57.0/reference/items/external-blocks.html) and assumed that it supports `unsafe extern`, but missed this paragraph:
> The `unsafe` keyword is syntactically allowed to appear before the extern keyword, but it is rejected at a semantic level. This allows macros to consume the syntax and make use of the `unsafe` keyword, before removing it from the token stream.
