### ISSUE TITLE
Linked JS file not being built properly (regression after 0.2.93)

### ISSUE THREAD

**Issue by zdimension** [rustwasm/wasm-bindgen#4233]
### Describe the Bug

A file linked to using `link_to!` is not being bundled properly starting with 0.2.94.

### Steps to Reproduce

1. clone [zama-ai/tfhe-rs](https://github.com/zama-ai/tfhe-rs) repository
2. run make build_web_js_api_parallel and check content of tfhe/pkg/snippets/wasm-bindgen-rayon-<hash>/src
3. change version constraint for wasm-bindgen to 0.2.95
4. remove tfhe/pkg folder
5. run again make build_web_js_api_parallel and check content of tfhe/pkg/snippets/wasm-bindgen-rayon-<hash>/src -> you'll see that workerHelpers.worker.js file is missing

### Expected Behavior

Should work as in 0.2.93.

### Actual Behavior

File is not bundled.

### Additional Context

https://github.com/RReverser/wasm-bindgen-rayon/issues/17

**Comment by daxpedda** [comment]
Its a feature, not a bug.

See https://github.com/rustwasm/wasm-bindgen/issues/3330#issuecomment-1870338632 for context, but basically `wasm-bindgen-rayon` was depending on a bug in `wasm-bindgen` that was fixed.

Its quite unfortunate that this caused breakage, but it was already considered a bug by many more users.

**Comment by zdimension** [comment]
My bad, hadn't seen that discussion thread, I understand better now, thanks. I'll stay on 0.2.93 for now (unfortunately some of my deps specify 0.2.95 so I have to patch them until wasm-bindgen-rayon is itself fixed)

**Comment by jthemphill** [comment]
@daxpedda: even if "it's a feature, not a bug"... isn't this a semver break?

**Comment by daxpedda** [comment]
> @daxpedda: even if "it's a feature, not a bug"... isn't this a semver break?

Depends on how you define a semver break. Unfortunately, the official [Semver guidlines](https://doc.rust-lang.org/1.82.0/cargo/reference/semver.html) don't mention bugfixes.

But following in Rustc's footsteps, there is concept called [future incompatible changes](https://doc.rust-lang.org/1.82.0/rustc/lints/index.html#future-incompatible-lints), which break semver to fix bugs. Historically this has already happened in Rust before, where fixes to lifetime correctness have caused breaking changes, without even time to add a lint beforehand.

**Comment by jthemphill** [comment]
Thanks for answering!

> Unfortunately, the official Semver guidlines don't mention bugfixes.

Semver's purpose is to help consumers manage their change and migration risk. The guidelines are just listing example changes that might break consumers' code, and hoping you'll see the pattern underlying the examples. Whether you consider a change to be a bugfix or not is irrelevant to whether that change introduces migration risk to downstream projects.

Migrating a project to `0.2.95` incurs more risk to the project than migrating to `0.2.93` did, so ideally the version numbers would be chosen to communicate this risk in a way that Cargo understands. 

If the release had bumped the minor version instead of the patch, `cargo update` would not automatically bring in this release at the same time as all the other packages whose patch numbers had updated. I would then manually update the package in isolation in `Cargo.toml`, and when my code broke, I would know what the breakage was and what caused it.

**Comment by daxpedda** [comment]
I understand and completely agree that this change has caused breakage. This is simply a fact.

But we are talking about two different things:
1. What literally "a breaking change" means.
2. The technical concept as it is used in ecosystem.

I am talking about 2. The [Rust semver guidelines](https://doc.rust-lang.org/1.82.0/cargo/reference/semver.html) are just that, "guidelines". But they still represent what is popularly considered a semver breaking change in the Rust ecosystem. Every ecosystem has its own rules and culture around what is and what isn't considered a semver breaking change. It has no bearing on the fact that some changes are nevertheless breaking somebodies world.

`wasm-bindgen` is just following the example of the Rust ecosystem and Rust itself. You are of course free to just pin your dependency on `wasm-bindgen` if our semver guarantees don't fit your bill. After all, Cargo offers this option for a good reason.

> It's very cheap to bump a minor or even major number instead of always bumping the patch number with every release. I would love to see more projects default to bumping higher numbers, leaving patch number bumps free to communicate which changes we know for sure are very low-risk.

Unfortunately this is not the case for `wasm-bindgen`. A minor/major bump to `wasm-bindgen` will break the entire Rust ecosystem and it will most likely take a *very* long time for the ecosystem to sync to this new version. These are the downsides of such a foundational and old crate.

**Comment by daxpedda** [comment]
I think maybe the initial premise was also not clear:
Relying on *unintended* side-effects of the `wasm-bindgen` post-processor is unsupported.

This was not a change to intended behavior that was already in place. The feature, as it was outlined, should not have caused this side-effect in the first place. It is unfortunate that there was a part of the ecosystem that started to rely on it.

**Comment by noname0310** [comment]
So is there still no alternative to use wasm-bindgen-rayon with the latest version of wasm-bindgen?

there should be at least some option for migration.

**Comment by daxpedda** [comment]
Depends. If you are just looking for a way to spawn threads, see https://crates.io/crates/wasm_thread. I'm also working on a more comprehensive implementation, but have yet to complete it before its release.

It might be a good idea if `wasm-bindgen-rayon` could depend on another crate with a functioning thread spawning implementation.

**Comment by RReverser** [comment]
> It might be a good idea if `wasm-bindgen-rayon` could depend on another crate with a functioning thread spawning implementation.

The point of wasm-bindgen-rayon is _to be_ that crate.

It really is unfortunate that #3330 was merged despite clear report that it will break end users, and released as a semver-compatible patch, despite drastically changing the behaviour of the previous version of the macro from the way it worked basically ~forever.

An approach like taken for e.g. `wasm_bindgen(thread_local)` -> `wasm_bindgen(thread_local_v2)` and such would be a lot less disruptive.

**Comment by RReverser** [comment]
Could we just revert https://github.com/rustwasm/wasm-bindgen/pull/4066 instead? It wasn't really a bugfix, since the snippets were - as described in the original issue / PR - unused anyway, so them being emitted did not constitute any issues for end users, and they'd be stripped by bundlers anyway so it's not even an optimisation, but the behaviour _after_ that PR does break end users.

With that in mind, it still seems to constitute a pretty clear breaking change that doesn't serve a clear purpose other than nice-to-have refactoring.

**Comment by daxpedda** [comment]
> > It might be a good idea if `wasm-bindgen-rayon` could depend on another crate with a functioning thread spawning implementation.
> 
> The point of wasm-bindgen-rayon is _to be_ that crate. That's what it was created for all those years ago and maintained to support end users.

I mean a thread spawning only crate. `wasm-bindgen-rayon` does way more than that.

> It really is unfortunate that #3330 was merged despite clear report that it will break users of a popular crate, and was released as a semver-compatible patch, despite drastically changing the behaviour of an existing macro from the way it worked basically ~forever.

I disagree that it drastically changed the behavior of `link_to!`. You [said yourself](https://github.com/rustwasm/wasm-bindgen/issues/3330#issuecomment-2285014673) that what you are doing is "hacky behaviour". I'm assuming because you knew you were relying on an unintended side-effect that was considered a bug, or was that unclear? Because https://github.com/rustwasm/wasm-bindgen/issues/3330 was clearly labeled as a bug.

I would have also happily waited and not gone ahead with this breaking change if there was a proposal to actually implement the feature you want here, which I offered you in https://github.com/rustwasm/wasm-bindgen/issues/3330#issuecomment-2285019198.
> An approach like taken for e.g. `wasm_bindgen(thread_local)` -> `wasm_bindgen(thread_local_v2)` and such would be a lot less disruptive.

These are not the same. `wasm_bindgen(thread_local)` wasn't buggy, it just doesn't work for `no_std`.
> Could we just revert #4066 instead? It wasn't really a bugfix, since the snippets were - as described in the original issue / PR - unused anyway, so them being emitted did not constitute any issues for end users, and they'd be stripped by bundlers anyway so it's not even an optimisation, but the behaviour _after_ that PR does break end users.
> 
> With that in mind, it still seems to constitute a pretty clear breaking change that doesn't serve a clear purpose other than nice-to-have refactoring.

It does serve a clear purpose: users should know what they need to ship and what they don't need to ship. I said this already here: https://github.com/rustwasm/wasm-bindgen/issues/3330#issuecomment-2286686050. Not all users are using bundlers that apparently just strip this away. The bug also affected the `web` target, not just the `bundler` target.

This was a bug and the fix serves a purpose and is not a "nice-to-have" refactoring.

---

I think I already made it abundantly clear what my stance on this being a breaking change is. Please see https://github.com/rustwasm/wasm-bindgen/issues/4233#issuecomment-2506740993 and https://github.com/rustwasm/wasm-bindgen/issues/4233#issuecomment-2506747208.

**Comment by daxpedda** [comment]
> > I would have also happily waited and not gone ahead with this breaking change if there was a proposal to actually implement the feature you want here, which I offered you in [#3330 (comment)](https://github.com/rustwasm/wasm-bindgen/issues/3330#issuecomment-2285019198).
> 
> You see how that's shifting the responsibility for API breakages to users instead of library maintainer? It shouldn't be users responsibility to fix their code when library breaks existing usages without correctly bumping semver. What bothers me most is, it's not like in this case consequences were unknown - the issue was reported upfront, yet instead of coming up with an alternative migration path, you decided to put that onto end users and go ahead with a breaking change.

In no way did I mean to shift responsibility on anybody. I was trying to say that I don't have a proposal for your desired feature, but `link_to!` is not it. If there was a proposal I would have waited, but without one I'm not sure what to wait for. I'm not in a position to design a proposal for a feature I don't properly understand. If you want to sit down together to discuss this feature I'm happy to, but I guess that's off-topic at this point.

> > It does serve a clear purpose: users should know what they need to ship and what they don't need to ship. I said this already here: [#3330 (comment)](https://github.com/rustwasm/wasm-bindgen/issues/3330#issuecomment-2286686050). Not all users are using bundlers that apparently just strip this away. The bug also affected the web target, not just the bundler target.
> 
> Users "not knowing what they need to ship" is not a bug by any reasonable definition. It's a docs issue at worst.
> 
> The reality is, before this change no code was broken - it didn't emit incorrect results, it didn't crash with exceptions, nothing of the sort, it was just... I don't know what to even call it, confusing users? But after the change, code _is_ broken and throwing exceptions.
> 
> How can one in good conscience call it a library bugfix when it goes from "end users applications work with no issues" to "end users applications crash"? By any definition of a bug, this would constitute _introduction of a bug_ that now needs to be fixed.

Moving away from the word "bug": its an *issue*. Only because its not *breaking* anything doesn't mean its not an issue. It may not have been an issue for you, but it was an issue for other users.

To clarify further: its unclear to users what parts of the `snippets` folder need to be included. Some users would just not include it and then encounter errors because `snippets` are still used by `#[wasm_bindgen(inline_js = ...)]`.

To the point of it being a docs issue: yes, it is. It is also where I'm coming from: `wasm-bindgen-rayon` was relying on completely undocumented behavior, a side-effect, without any stability guarantees whatsoever.

---

I can only speculate but you have hinted multiple times that the change was only a "nice-to-have refactoring" or "not a bug by any reasonable definition". This obviously makes this all very frustrating and you might not empathize with where this is coming from.

To prevent any more future problems I also feel I have to mention the following: the whole atomics implementation in `wasm-bindgen` is unstable and is provided without any stability guarantees whatsoever, this also applies to the Rust compiler itself. AFAICS `wasm-bindgen-rayon` can't be stable to begin with and both `wasm-bindgen` and Rust should be pinned if that's the desire. You even [mention that in your README](https://github.com/RReverser/wasm-bindgen-rayon#:~:text=In%20order%20to%20reduce%20risk%20of%20breakages%2C%20it%27s%20strongly%20recommended%20to%20use%20a%20fixed%20nightly%20version.%20This%20crate%20was%20tested%20with%20nightly%2D2024%2D08%2D02.). Maybe I'm missing something here, if so please enlighten me!

I also want to clarify that this isn't a desirable outcome nevertheless! Even if users are relying on unstable features or undocumented side-effects, WBG shouldn't just break them without a further thought! Preferably I would want to offer a migration path, but in this case no migration path was present. So I was left with two choices: leave all users with this issue unresolved or break code of users who are relying on an unstable library that is relying on unstable and undocumented features.

Again: in no way do I mean to shift responsibility, downplay the issue, or say something is "worse" because its unstable. This is purely technical: stability guarantees are only offered on certain things. Some features are unstable and marked as such. Side-effects and undocumented behavior MUST NOT be relied on. AFAIK this is a reasonable stance in the ecosystem.

I hope you can see my perspective on this and that the underlying differences are not simply overlooked or downplayed. This wasn't done haphazardly. I do appreciate your input on this very much!

And on a final note: I'm happy to work together on a feature proposal to support your use-case.

**Comment by RReverser** [comment]
> In no way did I mean to shift responsibility on anybody.

I understand that wasn't the intention, just saying it was the result of that decision - if the breakage isn't fixed on wasm-bindgen side, then it's downstream libraries and users who have to work around it now.

> If there was a proposal I would have waited, but without one I'm not sure what to wait for. 

I do think that in this case - where, it sounds, we both agree it wasn't a bug, but a non-critical issue - it was worth waiting longer, until someone, even if it's another 3rd-party contributor and not one of us, comes up with a solution that addresses the original issue but doesn't break existing usecases.

Alternatively, it could be labeled as `breaking-change` - god knows, wasm-bindgen collected tons of those over years https://github.com/rustwasm/wasm-bindgen/issues?q=is%3Aopen+is%3Aissue+label%3Abreaking-change where various UX issues are not fixed because they would be semver-breaking.

This issue seems like a clear contender for the same category. I know what you said about bumping minor, and I concur it will be a slow and difficult upgrade process, but sooner or later it will have to happen to address all of those bugs  together anyway, so a change to `link_to!` could go in the same bucket.

> AFAICS `wasm-bindgen-rayon` can't be stable to begin with and both `wasm-bindgen` and Rust should be pinned if that's the desire. You even [mention that in your README](https://github.com/RReverser/wasm-bindgen-rayon#:~:text=In%20order%20to%20reduce%20risk%20of%20breakages%2C%20it%27s%20strongly%20recommended%20to%20use%20a%20fixed%20nightly%20version.%20This%20crate%20was%20tested%20with%20nightly%2D2024%2D08%2D02.). Maybe I'm missing something here, if so please enlighten me!

I do recommend pinning Rust nightly, but mostly to prevent unrelated breakages which do happen on nightly from time to time. Nightly is required for `-Z build-std`, so the pinning suggestion is just a way for users to get some degree of stability rather than accidentally upgrading to latest nightly every day.

wasm-bindgen, however, never had to be pinned before this, and I'd very much like that to stay that way.

> If you want to sit down together to discuss this feature I'm happy to, but I guess that's off-topic at this point.

> And on a final note: I'm happy to work together on a feature proposal to support your use-case.

I managed to find a workaround for now - which, as all solutions, is not ideal, and something we moved from in the past when migrating to `link_to!` - but should work as a stopgap solution.

But yes, for easier and less hacky support in the future there are definitely things that could be done on the wasm-bindgen side that I never got around to working on. If you have spare time, I'd love to get together and discuss them as well (like, in a 30 min Google Meet call?) - I think they'd simplify wasm-bindgen-rayon's job substantionally in a few areas.

**Comment by daxpedda** [comment]
> But yes, for easier and less hacky support in the future there are definitely things that could be done on the wasm-bindgen side that I never got around to working on. If you have spare time, I'd love to get together and discuss them as well (like, in a 30 min Google Meet call?) - I think they'd simplify wasm-bindgen-rayon's job substantionally in a few areas.

Wrote you an email!

**Comment by jthemphill** [comment]
Thank you both for all your work on these awesome Rust crates!
