### ISSUE TITLE
Simplify optional argument generated interface by using `Into` trait

### ISSUE THREAD

**Issue by jonathanKingston** [rustwasm/wasm-bindgen#582]
WebIDL has the possibility of having `attribute DOMString? crossOrigin;`
There are 46 attribute definitions in `available/` and `enabled/` that would benefit from this (once long and other attribute types are supported). 

```
scriptEl.set_cross_origin(Some("crossorigin"));
```
Could be simplified to:
```
scriptEl.set_cross_origin("crossorigin");
```

By changing the implementation to:
```
impl HTMLScriptElement {
...
    pub fn set_cross_origin<'a, T: Into<Option<&'a str>>>(cross_origin: T) -> String {
        cross_origin.into();
        ...
    }
...
```

There are many more methods that would benefit:

```
boolean isSameNode(Node? node);
```

Could be: `node.is_same_node(node)` instead of `node.is_same_node(Some(node))`

This shouldn't increase any runtime cost, and make the interface less boilerplate.

**Comment by alexcrichton** [comment]
Perhaps yeah! Although the webidl bindings are intentionally intended to be low-level rather than ergonomic. There's a whole host of reasons they're not super ergonomic to use, this only being one of them! 

I'd personally be inclined to avoid this for now, leaning on concrete types in the low-level bindings and community abstractions to make it less boiler-plate-y

**Comment by jonathanKingston** [comment]
Yeah OK, I'm going to close this for now :+1: thanks for the super fast explanation!
