### ISSUE TITLE
Accessing filesystem 

### ISSUE THREAD

**Issue by Cyres** [rustwasm/wasm-bindgen#641]
Is there a way to read a file into the rust program? I'm in an std-environment, but this isn't supported as far as I can see.

```rust
info!("{}", fs::read_to_string("assets/models/cube.obj")?);
```

The file was copied with [`copy-webpack-plugin`](https://www.npmjs.com/package/copy-webpack-plugin) at the desired address, so i can open it with `localhost:8080/assets/models/cube.obj`.

**Comment by alexcrichton** [comment]
If the file is available at compile time you can use `include_str!` or `include_bytes!` to import it as a literal into your program, but otherwise wasm has no support for reading the filesystem so you'll need to do something different on the web or use node.js's functions in Node

**Comment by Pauan** [comment]
If you need to load the file at runtime (rather than compile-time), you can use either of these JavaScript APIs:

* [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) (new but not supported by all browsers)
* [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest) (old but supported by all browsers)

There is work being done on making those APIs available in Rust (with the web-sys crate).

**Comment by Cyres** [comment]
Unfortunately, the files have to be loaded dynamically. (My files are quite large and not all are always needed). Anyway, thanks for the recommendations. Until the functions can be used from Rust, I will use them from JS.
