### ISSUE TITLE
Doc link no longer working?

### ISSUE THREAD

**Issue by robertDurst** [rustwasm/wasm-bindgen#733]
## Reproduce:
Click: https://docs.rs/wasm-bindgen/0.2.17/wasm_bindgen/

and see:

<img width="1440" alt="screen shot 2018-08-19 at 12 13 59 pm" src="https://user-images.githubusercontent.com/16689974/44312214-6f7c0780-a3a9-11e8-97be-2eb2430cade1.png">

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately this is due to the fact that docs.rs doesn't always have a new enough nightly for more recent wasm-bindgen versions. The master branch version of the documentation is [here](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/) though and this crate should be stable soon enough!
