### ISSUE TITLE
Add "Reading Wasm Memory from JavaScript" reference section to the guide

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#771]
Would document `import { memory } from "whatever_bg";`

Have an example of rust returning a pointer (and length?) to JS and then JS constructing a `Uint8Array` from the `memory.buffer`.

Have an example of using [`wasm_bindgen::memory()`](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/fn.memory.html), casting that to `js_sys::WebAssembly::Memory`, getting its underlying `buffer` and constructing a `js_sys::Uint8Array` from that that is returned to JS.

**Comment by twilco** [comment]
Looking forward to this!

**Comment by alexcrichton** [comment]
This is now done in the [wasm-in-wasm](https://github.com/rustwasm/wasm-bindgen/blob/ebe73a537c920271a4681e8b24dc6e80e29744fc/examples/wasm-in-wasm/src/lib.rs#L24-L38) example, but it's notoriously tricky because the value returned by the `buffer` property from wasm's memory can change at any time when Rust does a memory allocation, so this needs to be done very carefully

**Comment by alexcrichton** [comment]
I think we've documented this effectively enough in the meantime, so closing.
