### ISSUE TITLE
Keeping js-sys bindings up to date

### ISSUE THREAD

**Issue by bakkot** [rustwasm/wasm-bindgen#859]
(Please forgive the drive-by comment.)

I'm curious if there's a process for keeping the work done in #275 up to date as JavaScript evolves. For example, the Array.prototype.{flat,flatMap} [proposal](https://tc39.github.io/proposal-flatMap/) is [in all major browsers](https://github.com/tc39/proposal-flatMap/issues/71) and will probably reach stage 4 of the TC39 [process](https://tc39.github.io/process-document/) next week, at which point it will (shortly thereafter) land in the living version of ECMA262 and subsequently ship in the ES2019 edition of the spec. Is there a way for people to tell if this project provides bindings for those functions?

If there's not something similar in place already, I think it would be useful for this project to have something like Babel's [proposals tracking repo](https://github.com/babel/proposals) to note which things are implemented.

Personally I'd recommend that stage 4 be considered the appropriate time to ship bindings. (I am on TC39, but am not speaking for the rest of the committee.)

PS: The link in [CONTRIBUTING.md](https://github.com/rustwasm/wasm-bindgen/blob/a85e49a2b4d405e766b2ec78146fec59ed386813/CONTRIBUTING.md) is broken.

**Comment by fitzgen** [comment]
> (Please forgive the drive-by comment.)

No need to apologize; great point to bring up!

We don't have a process yet, but it is a something we need to figure out!

I agree that stage 4 makes sense, since they are shippuing and expected to be in the next release of the standard. Stage 4 seems like something you can fairly reliably program against.

Assuming that stage 4 makes sense to @alexcrichton and others, then I think we can document this somewhere in the js-sys contributing docs.

> PS: The link in [CONTRIBUTING.md](https://github.com/rustwasm/wasm-bindgen/blob/a85e49a2b4d405e766b2ec78146fec59ed386813/CONTRIBUTING.md) is broken.

Thanks for the heads up!

**Comment by alexcrichton** [comment]
Adding stage 4 apis sounds great to me! I'd be totally down for such a strategy
