### ISSUE TITLE
Gecko's WebIDL can be wrong for other browsers

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#908]
We originally lifted our WebIDL definitions from Gecko, which means we're highly likely to work in Firefox which uses that exact WebIDL (yay!). Over time though we're discovering that Gecko's WebIDL isn't what's used by other browsers.

Examples discovered so far:

* [`AudioScheduledStartNode`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.AudioScheduledSourceNode.html) exists in our WebIDL, but in webkit the methods [are defined inherently](https://github.com/WebKit/webkit/blob/d779d13d239e5f893fd23864d5c9b48d5b6e925c/Source/WebCore/Modules/webaudio/OscillatorNode.idl#L51-L52) in classes which inherit from `AudioScheduledStartNode` (like `OscillatorNode`)
* [`BaseAudioContext`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.BaseAudioContext.html) doesn't exist in Safari, looking like [it's also inlined on `AudioContext`](https://github.com/WebKit/webkit/blob/d779d13d239e5f893fd23864d5c9b48d5b6e925c/Source/WebCore/Modules/webaudio/AudioContext.idl#L79-L90).

These definition issues aren't generally a problem for the web platform but they're a problem for us in that we're plucking our raw function pointers for maximal performance, and those raw function pointers are located in different places.

Ok with that in mind, how do we want to solve this? I don't think we want to include WebIDL from all browsers and take the union, but rather what I think we can do is to basically just massage our WebIDL to become more browser-agnostic over time. Put another way, we should do this:

* For `AudioScheduledStartNode`, switch it to a mixin.
* All classes which inherit from `AudioScheduledStartNode` now have `Foo includes AudioScheduledStartNode` and inherit from `AudioScheduledStartNode`'s original parent

Transformations like that mean that we're modeling the web platform slightly differently, but it should effectively have the same result. The `wasm-bindgen` generated bindings [already look up the inheritance chain](https://github.com/rustwasm/wasm-bindgen/blob/11bcaf42d5300adc99fd3d10ac726e568c304e88/crates/cli-support/src/js/mod.rs#L1609-L1616) for the right function pointer, which means that we'll still use all the native methods on `BaseAudioContext` in Firefox and we'll otherwise use the methods on `AudioContext` in Safari. 

The downside of this approach is that it's a breaking change for `web-sys`, although I think we may be able to get around that by, for example, moving all the methods in `interface AudioScheduledStartNode` into a `interface mixin rustAudioScheduledStartNode` and then include that in various interfaces. That... shouldn't be a breaking change I think in general but it doesn't fix methods which take `AudioScheduledStartNode` as a parameter, for example (as that type just doesn't exist in WebIDL).

In any case, do others have thoughts on this? Other ideas on how we'll cope with these differences?

**Comment by sendilkumarn** [comment]
I like this idea, we should always try to minimize the overhead.

**Comment by alexcrichton** [comment]
@froydnj perhaps! I fear though that we're still a small enough project that others may not take us too seriously. I'm not even sure how to find the webidl Edge uses! For now I think the path of least resistance is probably figuring out how we fit best into the ecosystem as-is, but perhaps eventually we could influence webidl changes!

**Comment by upsuper** [comment]
@froydnj I'm not familiar with this particular case, but web-platform tests have IDL tests, which is supposed to check every web-exposed behavior testable based on WebIDL from specs.

What I'd like to raise is that, difference on WebIDL definition between different browsers is probably more than just whether they are spec-conforming. At least, Gecko's WebIDL definition is a superset of the standard WebIDL, because it is used for internal codegen as well, and thus there are implementation details around. They generally doesn't matter for web-sys, but there is case does.

Specifically, `[Throws]` is an attribute that is not defined in the standard WebIDL, which seems to be affecting the codegen of web-sys. Generally, simply adding or dropping the `[Throws]` attribute doesn't affect the web-exposed behavior of a function itself. Certainly without this attribute, you cannot throw from a function, but a function which never throws can also have that attribute present, because no one would care. So it can be quite arbitrarily added (when one suddently needs to throw from a function) or removed (when one refactors the code and wants to remove unused stuff).

Conceptually, making a function throw isn't consider a breaking change for the web, but it is for web-sys, because it uses `Result<_, JsValue>` for those who can throw. So from the perspective of web-sys, probably everything from the Web API should be considered to be able to throw, and it shouldn't rely on Gecko's `[Throws]` attribute. But that would make everything really hard to use.

I don't have good solution to this situation. Maybe we should treat JS exception just as panic, and ask users to use `catch_unwind` if they really care.

**Comment by upsuper** [comment]
Oh, and, all functions certainly can throw simply because they may not have been implemented in a browser.

**Comment by fitzgen** [comment]
Argh, I didn't realize `[Throws]` was a gecko-ism!

Don't have much to add to Alex's response about whether to pessimistically treat everything as if it can throw. Let's see if it becomes an issue or not.

**Comment by alexcrichton** [comment]
I'm gonna go ahead and close this as I don't think there's much we can do about this, and https://github.com/rustwasm/wasm-bindgen/pull/909 shows a strategy of handling changes to our WebIDL in a non-breaking fashion and we should be able to catch this as new issues arise!

**Comment by dbrgn** [comment]
Hm, I'm a bit surprised that the W3C and/or WHATWG don't maintain their own "official" IDL... Maybe someone knows some relevant people involved in this? Definitely seems a worthwhile project to me...

CC @lgrahl, maybe you know & can ping some people that are involved in this area?

**Comment by lgrahl** [comment]
I don't believe such a project exists but it doesn't seem like a bad idea. @annevk - thoughts? :slightly_smiling_face:

**Comment by annevk** [comment]
I'm not sure I understand the question. Standards contain IDL that is official. If you scraped standards instead of the source code of a particular browser, you'd have "official IDL".

Depending on the use case (I haven't read the thread) implementation IDL might contain useful annotations though that aren't standardized (such as whether the implementation of something can throw).

**Comment by annevk** [comment]
As it happens, wpt does such automated scraping: https://github.com/web-platform-tests/wpt/tree/master/interfaces.

**Comment by fitzgen** [comment]
Interesting! If we had known about that from the start, we probably would have used it!

We should consider switching, although it is probably technically a breaking change.

We would also have to consider any discrepancies between our sets of interfaces. If our gecko-baded webidl has anything that the standards-scraping-derived set doesn't then hopefully that just means it is a non-standard interface we shouldn't generate bindings for and not a missing hole in the standards-scraping-derived interfaces.

**Comment by alexcrichton** [comment]
Ok I think we fixed the original issue that cropped up here and we should have a path forward to fixing any other incompatibilities in the future, so for now I think this is probably just an unfortunate fact of life!
