### ISSUE TITLE
Cannot extend types defined in other crates/modules without importing them

### ISSUE THREAD

**Issue by Migi** [rustwasm/wasm-bindgen#916]
In short, this works:

```rust
extern crate js_sys;

use js_sys::Error;

#[wasm_bindgen]
extern {
	#[wasm_bindgen(extends = Error)]
	type MyError;
}
```

but this doesn't:

```rust
extern crate js_sys;

#[wasm_bindgen]
extern {
	#[wasm_bindgen(extends = js_sys::Error)]
	type MyError;
}
```

It gives the error "expected `,`". Using `extends = ::js_sys::Error` or wrapping it in quotes gives "expected an identifier".

Having to import the types that you want to extend can lead to naming conflicts. This can be worked around by naming the type differently and using `js_name = ...`, but that's not very ergonomic.

**Comment by alexcrichton** [comment]
You can also use `extern "C" { ... }` to get better errors (the bad error mesage there is a compiler bug). Otherwise the [syntax of `extends`](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-js-imports/extends.html) currently only allows identifiers, so you'll need to import the type into the module. That being said supporting arbitrary Rust paths also makes sense to me!

**Comment by Migi** [comment]
Thanks for the quick fix!

I had actually begun writing a fix myself, and wrote pretty much the same code, except less elegant (I didn't know that you could just convert `Ident` `into()` `syn::Path`, for example).

**Comment by alexcrichton** [comment]
Ah sorry about that! Feel free to comment if you're working on a fix and I can help out as well if necessary!
