### ISSUE TITLE
why wasm32-unknown-unknown?

### ISSUE THREAD

**Issue by takkuumi** [rustwasm/wasm-bindgen#979]
there is no a better name?
why wasm32-unknown-unknown? there is a wasm32-known-known?
why wasm32? there is a wasm64 or wasm 128?

i think we need new name, like rust-wasm?

**Comment by Pauan** [comment]
@NateLing To expand on what others have already said: yes there will eventually be a `wasm64-unknown-unknown`, and there [were discussions](https://github.com/rustwasm/team/issues/38) about adding in things like `wasm32-unknown-node`, `wasm32-unknown-web`, etc.

The `wasm32-unknown-unknown` name is consistent with [Rust's existing names for compilation targets](https://forge.rust-lang.org/platform-support.html). Since Rust supports so many different targets, it's important to have consistent names.

**Comment by vincentes** [comment]
> So you an think of unknown-unknown as
> “Compile on almost any machine, run on almost any machine”
> If you look at other targets “unknown” is commonly used so this is in line with the other targets.



Isn't `--target` the platform we're going to compile this for? A [target](https://doc.rust-lang.org/nightly/rustc/platform-support.html) or platform is identified by a [target triple](https://wiki.osdev.org/Target_Triplet), which has a `machine-vendor-operatingsystem` format. 


Target triplet does not mean "memory address", "system I'm compiling on", and "executing for".  Our target or platform is the architecture we're running the generated bytecode on. In this case it's the Web Assembly runtime, that's our "target" platform.  Correct me if I'm wrong.

Rust uses the target triplet format but platforms or targets don't always include the three elements (vendor, machine, operating system). There are ambiguities.

For example: [x86_64-apple-darwin](https://doc.rust-lang.org/nightly/rustc/platform-support/apple-darwin.html) and aarch64-pc-windows-msvc.

The naming is still odd to me. I think just `--target=wasm32` would be just fine.

**Comment by zzz6519003** [comment]
+1 too confusing, should be self-explanatary
